### ISSUE TITLE
[Bug]: @carbon/react/icons module does not provide IDE import auto-complete

### ISSUE THREAD

**Issue by jharvey10** [carbon-design-system/carbon#11317] opened 2022-04-29 03:21 UTC
### Package

@carbon/react

### Package version

1.1.0

### React version

not specific to a version of react

### Description

When importing icons via the `@carbon/react/icons` re-export, no auto-completions are provided in VS Code:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/51208233/165878756-b1397c2c-e9cf-4038-ba5f-97fb5b6e2fbe.png">

versus `@carbon/icons-react` which looks like:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/51208233/165878804-6ec1b99c-7d9c-4259-8e15-7289178c59ea.png">

It doesn't look like the IDE auto-completion is smart enough to follow the combination of `Object.keys` and `Object.defineProperty` to provide the exhaustive list of icons that are available at runtime/build time.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/51208233/165880445-2d411f46-da0d-4fe0-b5fe-6c07a3b42a2d.png">

Though I'm not sure exactly how to accomplish it, it seems like a more direct re-export of the icons from the `require`d module would be what is needed to get past this.

There's also an info message that pops up in vscode for this import which is not present on the icons-react version:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/51208233/165880083-9aaa055e-101a-4774-9e6f-a652c4945b78.png">

versus icons-react which has a full-blown `d.ts` file to which it links that provides type info:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/51208233/165880286-ae203da3-a578-490a-ba8a-817683d61895.png">

### CodeSandbox example

n/a

### Steps to reproduce

1. Install `@carbon/react` into a React project
2. Open a component file in an IDE like VS Code
3. Attempt to import an icon from `@carbon/react/icons`
4. Observe that the auto-complete list does not show any of the available icons

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment] 2022-04-29 18:09
@jdharvey-ibm trying a quick change over in: https://github.com/carbon-design-system/carbon/pull/11318 that matches what other icon libraries with sub-folder imports do just in case it's a quickfix.

Otherwise, we may need to just generate types for this folder to help out since what VSCode is doing is downloading the types from `@types/carbon__icons-react` from DT

**Comment by jdharvey-ibm** [comment] 2022-04-30 06:44
@joshblack sweet! What can I do to help out with testing?

**Comment by joshblack** [comment] 2022-05-02 14:53
@jdharvey-ibm something that would help out a ton when it's merged in would be to:

- Pull down latest updates from `main`
- Run a build (can use `yarn lerna run build --scope='@carbon/icons-react' --include-dependencies` to target just the icons package)
- Link the package with `npm link` to connect it to your project 
- See if autocomplete works as expected or if it's still messed up

**Comment by joshblack** [comment] 2022-05-03 15:19
@jdharvey-ibm if you have a sec to test out latest, let me know! Should be available now

**Comment by jdharvey-ibm** [comment] 2022-05-09 16:38
Testing it now!

**Comment by joshblack** [comment] 2022-05-09 18:05
@jdharvey-ibm thanks for trying it out! Super interesting 🤔 

I assume you don't run into problems with packages like `react-icons` with its subpaths, correct?

**Comment by joshblack** [comment] 2022-05-09 18:06
I wonder if we should try having the default `index.js` file and then only set `module` in `package.json` similar to what they do 🤔

**Comment by jdharvey-ibm** [comment] 2022-05-10 20:53
When trying the example from their docs, I do indeed get autocomplete, but it looks like they're repo must be broken down into some different folders:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/51208233/167719692-7087a419-5688-4477-aa7b-39f9a2106d33.png">

Interestingly, I just realized that if I switch to using `@carbon/react/icons/es` as my import, that does work as far as autocomplete goes:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/51208233/167719818-014b4bfb-3954-4e94-9bc2-677219eb84ed.png">

**Comment by joshblack** [comment] 2022-05-16 19:06
Looks like in the latest update this is still an issue 😞 it seems unable to resolve any kind of type file for that entrypoint.

Similarly, it seems like the default types for the package are incorrect on DefinitelyTyped which is causing some of the oddity for imports.

It seems like our only way to address this is to offer an `index.d.ts` file that either directly exports the types or explicitly re-exports from the `@carbon/icons-react` (which also needs to be updated)

**Comment by TannerS** [comment] 2022-06-16 17:38
Any update?

**Comment by joshblack** [comment] 2022-06-16 21:18
Hey @TannerS! 👋 It seems like the big thing for incorrect imports is that there is a local cache of packages which are probably being pulled from for completion.

In the case of @jdharvey-ibm above, it seemed like a local cache was being used:
![Screen Shot 2022-06-16 at 4 08 52 PM](https://user-images.githubusercontent.com/3901764/174165664-7f39e0d0-3b71-42d1-8d22-25dc3cdbeb5d.png)

Deleting that cache entry seemed to fix the issue of "invalid imports" but I would love to hear from you if this helps in the IntelliJ use-case 👀

**Comment by TannerS** [comment] 2022-06-16 21:21
How do I check? Is this released ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joshblack** [comment] 2022-06-16 21:23
@TannerS it should require no updates to the package itself, it seems like the behavior comes from the TypeScript cache versus the package

**Comment by TannerS** [comment] 2022-06-16 21:37
Hmm so I clear....IDE cache?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jdharvey-ibm** [comment] 2022-06-17 20:21
For me on Mac, when I stepped into the definitions file it was pulling from, it was in the node modules cache in my typescipt 4.7 directory (`~/Library/Caches/typescript/4.7/node_modules/@types/carbon__icons-react`). I'm guessing it's an IDE feature to attempt to download types for packages from the `@types` namespace in an effort to be helpful. I'm not aware of a way to turn that off for VS Code (or other editors)

As a stopgap, what I might do is pull down the type definitions from over in #11533 into a local folder in my repo and include a `typeRoots` property in our tsconfig file to search there first.

This is definitely being actively worked on though! @joshblack and I have had some discussions about it.

@joshblack Is this enough of an issue to where we should look into deleting the definitions from DefinitelyTyped?

**Comment by joshblack** [comment] 2022-06-22 16:26
@jdharvey-ibm good question, I think most downloads are still coming from pre-v11 and so would be helpful for teams wanting to use TS + pre-v11 icons. TypeScript support is definitely one of the biggest blocker for folks moving to v11, though, so I feel kind of stuck with what to do. 

Do we know if there is a way for the types on DefinitelyTyped to only correspond to pre-v11 versions?

**Comment by metonym** [comment] 2022-08-05 02:15
`@types/carbon__icons-react` have been updated to [v11.5.0](https://www.npmjs.com/package/@types/carbon__icons-react).

You should now see the correct types for v11 icons.

<img width="600" alt="@types:carbon__icons-react@11 5 0" src="https://user-images.githubusercontent.com/10718366/182986702-6fda0202-d640-49d7-8cb4-10906eb227ea.png">

**Comment by jdharvey-ibm** [comment] 2022-08-05 15:18
Confirmed that when I import via `@carbon/react/icons/index.esm`, I get the right set of imports available, which is awesome.

The main thing still outstanding for this issue is that I don't get the auto-complete from the standard `@carbon/react/icons` import; I have to use the more-specific `index.esm` one. Not a huge deal, but wanted to note it.

**Comment by metonym** [comment] 2022-08-05 15:24
> I don't get the auto-complete from the standard @carbon/react/icons import

Is that something that #11533 would solve?

Ideally, types/JSDocs would be shipped with `@carbon/icons-react` (see [approaches](https://github.com/carbon-design-system/carbon/pull/11533#issuecomment-1205968217)) so that `@types/carbon__icons-react` could be removed altogether.

**Comment by jdharvey-ibm** [comment] 2022-08-05 15:31
@metonym unfortunately for my use case I don't believe that would help. The issue I have when working with the icons through the `@carbon/react` export is that the index.js file at `@carbon/react/icons/index.js` does not appear to be defined in a way in which VS Code can compute the available imports for the icons package. Something about the cjs syntax in it and the use of defineProperty isn't properly recognized. `index.esm.js` works fine though since the only contents of that file are `export * from '@carbon/icons-react';`

**Comment by metonym** [comment] 2022-08-07 17:36
@jdharvey-ibm Follow-up thought: why not import icons from `@carbon/icons-react` directly since it's a direct dependency of `@carbon/react`?

**Comment by jdharvey-ibm** [comment] 2022-08-10 18:19
@metonym that's definitely doable! As a general strategy though, we want the `@carbon/react` package to be a one-stop shop for everything you need to develop with React + Carbon. As a workaround, that and using the es import will both do the trick; it's just not the *intended* behavior.

**Closed as completed** 2023-10-20 12:54 UTC
Labels: severity: 3, type: bug 🐛, role: dev 🤖, version: 11, package: @carbon/react
