### ISSUE TITLE
Assigning disabled='true' property to TableSelectRow component dose not disable  the Checkbox

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#7450] opened 2020-12-14 00:13 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react` ----  "carbon-components-react": "^7.24.0",

## Detailed description

> Describe in detail the issue you're having.
disabled='true' property to TableSelectRow component dose not disable  the Checkbox

> Is this issue related to a specific component?
TableSelectRow 
> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
^7.24.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code

[testcase.js.zip](https://github.com/carbon-design-system/carbon/files/5689996/testcase.js.zip)

- Notes

**Comment by zhenwan** [comment] 2020-12-16 15:17
is someone looking into this issue? it is blocking our project

**Comment by tw15egan** [comment] 2020-12-16 15:33
@zhenwan Do you have a reduced test case on [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) so we can take a look at the code?

**Comment by zhenwan** [comment] 2020-12-16 15:40
I have attached a test case file testcase.js.zip. this issue can be easily seen by copying and paste the code into the

**Comment by tw15egan** [comment] 2020-12-16 15:44
https://codesandbox.io/s/bold-swirles-7jlc3?file=/src/index.js

It seems to be working properly as long as the prop getter comes before the disabled state:
```jsx
<TableSelectRow
   {...getSelectionProps({ row })}
   disabled={true}
/>
```

Going to close this but feel free to reopen if this does not solve your issue.

**Closed as completed by tw15egan** 2020-12-16 15:44 UTC
Labels: type: bug 🐛

**Comment by DenisCor** [comment] 2023-02-22 16:01
> https://codesandbox.io/s/bold-swirles-7jlc3?file=/src/index.js
> 
> It seems to be working properly as long as the prop getter comes before the disabled state:
> 
> ```js
> <TableSelectRow
>    {...getSelectionProps({ row })}
>    disabled={true}
> />
> ```
> 
> Going to close this but feel free to reopen if this does not solve your issue.

For me disabled={true} will only work with TableSelectAll, but wont work with TableSelectRow.. no idea why

**Comment by tay1orjones** [comment] 2023-03-06 16:11
@DenisCor could you open a new issue reporting this with a fresh code reproduction? Thank you 🙏
