### ISSUE TITLE
[Bug]: Inline Notifications inside Modals CSS is messed up

### ISSUE THREAD

**Issue by dabrad26** [carbon-design-system/carbon#10098] opened 2021-11-11 23:34 UTC
### Package

carbon-components, carbon-components-react

### Browser

Safari

### Package version

10.46.0, React: 7.46.0

### Description

Inline Notifications Inside a Modal have messed up styling due to https://github.com/carbon-design-system/carbon/blob/2da12d0d99e45563d78431a0e6a19df92ac1ff54/packages/components/src/components/modal/_modal.scss#L134 targeting the `p` tag that Inline Notifications uses.

Probably avoid targeting tags or add `:not` for all possible parent components that can render in modal and use `p` (or switch InlineNotifications to div instead of `p`...

![Screen Shot 2021-11-11 at 3 32 49 PM](https://user-images.githubusercontent.com/8028956/141383702-6bbf8ebb-18e6-4fd0-8dc1-adb93f7bc39f.png)
![Screen Shot 2021-11-11 at 3 33 49 PM](https://user-images.githubusercontent.com/8028956/141383776-cc55ae74-bb65-495a-a804-cc0a52e08afa.png)

Product: IBM Aspera Starter

### CodeSandbox example

https://codesandbox.io/s/youthful-framework-cp4zh

### Steps to reproduce

Add InlineNotificaiton to Modal.
See Title/Subtitle in notification styling is wrong.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tomleah** [comment] 2022-12-09 14:11
Adding to this instead of a new bug as title suggests all styling within a modal - specially we are interesting the title of the inline notification being **bold** when used within a modal

Browser: Chrome
React: v16.13.1
carbon-components-react: v7.57.0

Another sandbox - https://codesandbox.io/s/bold-modal-notifications-fbi13k

**Comment by tw15egan** [comment] 2022-12-09 15:03
It seems like with V11, `Notification` does not render ` p` element anymore, so the issue isn't happening, but there are instances where those styles would leak further down than we'd like. I'll scope them so that those styles only target top-level `p` elements inside of a `Modal`

**Comment by tomleah** [comment] 2022-12-09 15:09
Ah gotcha! So we can expect this is already fixed in v11? 

Thank you @tw15egan

**Comment by tw15egan** [comment] 2022-12-09 15:20
Yes, I tested it out and didn't see the issue, but scoped the styles better regardless. I'll backport this fix to v10 as well.

**Closed as completed** 2022-12-19 16:59 UTC
Labels: severity: 3, type: bug 🐛, component: notification
