### ISSUE TITLE
Data Table - Alignment issue in expansion row arrow when table size is short 

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon#4833] opened 2019-12-09 05:53 UTC
Having alignment issue in expansion row arrow when table size is short.

<img width="775" alt="imggg" src="https://user-images.githubusercontent.com/29912424/70410780-42f46f00-1a76-11ea-8bf4-a218dc114bfc.png">

**Comment by joshblack** [comment] 2019-12-09 18:58
Hi there @abhisheksinghrana! 👋 Thanks so much for taking the time to report this issue 🙏 I believe this is a duplicate of https://github.com/carbon-design-system/carbon/issues/4796 so I am going to close this in favor of the original ticket. Let me know if they are separate issues and I can re-open!

**Closed as completed by joshblack** 2019-12-09 18:58 UTC
Labels: type: bug 🐛, component: data-table
