### ISSUE TITLE
[Bug]: Tooltip doesn't work when trigger has tabindex="-1"

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#15214] opened 2023-11-16 13:05 UTC
### Package

@carbon/react

### Browser

Chrome, Safari

### Package version

1.42.0

### React version

18.2.0

### Description

When the trigger button of a `Tooltip` has `tabindex` set to `-1` the tooltip doesn't appear at all on hover and only for a flicker on click.

Context / use case: the button is within a widget that manages the focus (e.g. grid).

### Reproduction/example

https://stackblitz.com/edit/github-mje2hg?file=src%2FApp.jsx

### Steps to reproduce

```jsx
// ✅ works
<Tooltip>
  <button>Trigger</button>
</Tooltip>
```

```jsx
// ✅ works
<Tooltip>
  <button tabindex="0">Trigger</button>
</Tooltip>
```

```jsx
// ⛔️ doesn't work
<Tooltip>
  <button tabindex="-1">Trigger</button>
</Tooltip>
```

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment] 2023-11-21 22:07
I would love to work on this issue!

**Comment by kuri-sun** [comment] 2023-11-23 04:45
Hi, everyone!
I took a look at this bug, but I found the code that we intentionally prevent opening a Popover(black content box) element when a user does not have an interactive HTML element inside of <Tooltip> component. following is the reference. (`getInteractiveContent` function in useNoInteractiveChildren.js file)

![note](https://github.com/carbon-design-system/carbon/assets/62743644/689b1cfe-4e53-49dd-91ea-1f43a0cb4dff)

So, I concluded that this behavior is not a bug, and If a user wants to fix this to be opened, make sure that the user needs to eradicate the `tabIndex` property or set `tabIndex` to not `-1`.

If this is the case, I will request the reporter or maintainer to close this issue.
Thank you so much!

**Comment by guidari** [comment] 2023-11-23 18:19
You are right @kuri-sun, this is a intended behavior. The `tabIndex="-1"` removes the tooltip from the navigation.

If somehow you want to remove the tooltip from the navigation you could disabled the trigger element, although I don't see a use case where a disabled `Tooltip` would make sense or even removing from the navigation.

I'm gonna close this issue @janhassel, but feel free to comment here.

**Comment by janhassel** [comment] 2023-11-23 20:15
@guidari For more complex widgets described by the [APG](https://www.w3.org/WAI/ARIA/apg/patterns/) the developer is responsible to manage focus manually either with `aria-activedescendant` or a roving tabindex. In both cases, the tab indices of the individual elements must be removed from the standard tab order as they'd otherwise pollute it.

One example of such a widget is the [grid pattern](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/).

**Comment by guidari** [comment] 2023-11-28 19:22
This issue was re-open after talking to @janhassel via slack.

The use case is this cenario:

The user might want to remove the `Tooltip` from the `TAB` key navigation using the `tabIndex="-1"` and add arrowkey navigation. 

When that happens, the arrowkey navigation works showing the `Tooltip` as expected, but if you hover over it doesn't show the `Tooltip`.

**Comment by kuri-sun** [comment] 2023-12-03 21:24
Hi @guidari and @janhassel!
Thank you for the explanation! I would love to work on this issue! May I?

From the conversation, I understand that we should not pass the `tabIndex` prop to the component. Because otherwise, it is going to be the destruction of the user experience.
Is this correct?

**Comment by kuri-sun** [comment] 2023-12-04 20:11
@guidari, I see. So that means the user still can see `tabIndex="-1"` through the HTML DOM(Chrome Dev tool). But it detects the user's browser interactions(i.e. hovering).

**Comment by kuri-sun** [comment] 2023-12-06 17:50
Hi @guidari, I want to ask you a question to solve this.

(Cause)
I concluded that this happens because of the `useEffect` (line 203 in Tooltip.tsx). |
https://github.com/carbon-design-system/carbon/blob/8c0130499a08892c6e89e7f6d198d10462b1e017/packages/react/src/components/Tooltip/Tooltip.tsx#L204-L213
When the user has a `tabIndex=-1` element, `interactiveContent` is always `null` since `getInteractiveContent` checks whether the elements are focusable or not by `if (element.tabIndex === undefined || element.tabIndex < 0` condition in the `isFocusable` function.
https://github.com/carbon-design-system/carbon/blob/8c0130499a08892c6e89e7f6d198d10462b1e017/packages/react/src/internal/useNoInteractiveChildren.js#L87-L90

**Question:** 
Should I create an alternative function for `isFocusable` to detect a focusable state even though an HTML element has `tabIndex=-1`?
Or we can just remove this `useEffect` since we don't need the focusable state detection that makes TooltipContent always hidden.

**Comment by tw15egan** [comment] 2023-12-19 11:19
I am not sure; this may be a leftover effect from before we created `Toggletip` so that we changed the behavior of the `Tooltip` based on whether or not it has interactive content inside. `Toggletip` should open on click, not hover (used when there is interactive content inside) and `Tooltip` opens on hover (cannot have an interactive element inside of it)

**Comment by kuri-sun** [comment] 2024-01-11 18:35
Hello! 
Do we have any updates on this? Thank you!

**Comment by guidari** [comment] 2024-01-12 11:45
Hey @kuri-sun 
We might want to remove the `useEffect` since might be a leftover code like @tw15egan said

**Comment by kuri-sun** [comment] 2024-01-12 17:32
Hi @guidari, Thanks for the response! I will make a PR for this. Thank you!

**Closed as completed** 2024-01-18 18:54 UTC
Labels: type: bug 🐛, role: dev 🤖, component: tooltip
