### ISSUE TITLE
Date picker: bugs on mobile devices

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#1981] opened 2019-03-04 19:29 UTC
## Detailed description

On mobile devices the date picker is not rendering correct styles for single date picker and date range.

![img_0723](https://user-images.githubusercontent.com/11670886/53757367-17a67900-3e81-11e9-8b1e-9619b753e44b.PNG)
![img_0724](https://user-images.githubusercontent.com/11670886/53757369-19703c80-3e81-11e9-841b-12d2030fb3ec.PNG)
![img_0725](https://user-images.githubusercontent.com/11670886/53757373-1b3a0000-3e81-11e9-8464-9972edac484e.PNG)

> What did you expect to happen? What happened instead? What would you like to see changed?

Should still look and preform like date pickers on the desktop view

> What browser are you working in?

iOS Chrome

> What version of the Carbon Design System are you using?

10 beta

**Comment by emyarod** [comment] 2019-03-04 19:38
related: https://github.com/IBM/carbon-components/issues/1775

if I'm not mistaken, the website uses the React version of the component and its dependencies are outdated by several versions

opened https://github.com/IBM/carbon-components-react/issues/1965 to sync the vanilla and React date pickers

**Comment by asudoh** [comment] 2019-03-04 19:39
@emyarod Component demos for most components use vanilla, if it was your question above. Only React-only components use React for demos.

**Comment by tw15egan** [comment] 2019-03-04 19:42
Would throwing a `-webkit-appearance: none;` on the input work? I can't replicate the problem on my computer even using the iPhone 8 user agent. I can see the problem on my phone though

**Comment by emyarod** [comment] 2019-03-04 19:51
we should update the site dependencies or examine the latest component library examples first so we can figure out which issues still persist, since I think some of these have already been addressed

**Comment by aagonzales** [comment] 2019-05-02 20:01
Still rendering wrong on mobile. Need to fix.

**Comment by aagonzales** [comment] 2019-05-16 21:20
Stop it stale bot,  still a bug.

**Comment by alisonjoseph** [comment] 2020-02-05 14:37
I'm no longer seeing this issue on my phone, closing this issue. If someone is still seeing please re-open with steps to reproduce.

**Closed as completed by alisonjoseph** 2020-02-05 14:37 UTC
Labels: type: bug 🐛, severity: 1, role: dev 🤖, component: combobox, component: date-picker
