### ISSUE TITLE
AAT style Before-After violation

### ISSUE THREAD

**Issue by pkegbeto** [carbon-design-system/carbon#418] opened 2017-11-09 19:42 UTC
## Detailed description

Content must provide sufficient contrast between text and its background to enable moderately low vision users to read text without contrast-enhancing technology.

 #### Error message:
```
Message: wcag20.g1069.styleBeforeAfter
XPath: /html[1]/head[1]/style[3]
Snippet: <style type="text/css">
```

#### AAT violation
```
 https://aat.w3ibm.mybluemix.net/token/ce020aa2-f761-46a8-8925-2deeda4c9f69/a763761a-383e-4445-8e73-dbf86b61c844/latest/doc/w3/help/en-US/idhi_accessibility_check_g1069.html
```

## Additional information
<img width="1202" alt="screen shot 2017-11-09 at 1 58 40 pm" src="https://user-images.githubusercontent.com/29408678/32626039-20f85018-c55c-11e7-97e4-e4f237d7ff2c.png">

**Comment by tw15egan** [comment] 2017-11-09 20:09
Do you have any more information / which element this is occurring in? This issue is unactionable as-is

**Comment by pkegbeto** [comment] 2017-11-09 21:49
## Instances of issue wcag20.g1069.styleBeforeAfter

#### 1. First instance

<img width="506" alt="screen shot 2017-11-09 at 4 43 33 pm" src="https://user-images.githubusercontent.com/29408678/32631327-e2d660a6-c56d-11e7-8d62-74384a04dd51.png">


<img width="212" alt="screen shot 2017-11-09 at 4 43 44 pm" src="https://user-images.githubusercontent.com/29408678/32631338-eee46078-c56d-11e7-9daf-1548a339802f.png">

**Comment by asudoh** [comment] 2017-11-09 22:09
@pkegbeto If you inspect the `::before` yourself, you’ll find that the `content` property there is an empty string. Therefore it has nothing that https://aat.w3ibm.mybluemix.net/token/ce020aa2-f761-46a8-8925-2deeda4c9f69/a763761a-383e-4445-8e73-dbf86b61c844/latest/doc/w3/help/en-US/idhi_accessibility_check_g1069.html is complained against?

**Comment by pkegbeto** [comment] 2017-11-09 22:57
I dont understand what you mean.  Can you elaborate? We used a carbon class. Do you mean we are using it wrong?

**Comment by asudoh** [comment] 2017-11-10 01:55
@pkegbeto My apologies if my earlier response confused you. AAT sometimes reports false-positives and I believe your particular case is one of them. Please feel free to ask if you have any further questions. Thanks!

**Comment by tw15egan** [comment] 2017-11-10 17:29
@pkegbeto As Akira explained, these false-positives are part of the reason why we moved away from AAT as our accessibility testing tool. I'm going to close this as I do not believe this is an accessibility violation caused by Carbon, but feel free to re-open if you disagree.

**Closed as completed by tw15egan** 2017-11-10 17:29 UTC

**Comment by pkegbeto** [comment] 2017-11-10 22:10
The violated rule is the following:


>The CSS ::before and ::after pseudo-elements specify the location of content to be inserted before and after an element's document tree content. For users who need to customize or turn off style information so that they can view content according to their needs, assistive technologies might not be able to access the information that is inserted using CSS. These properties should not be used to insert non-decorative content. 

The rule is clear on what it is complaining about. We may think that it is not serious enough to be flagged but we cannot say it is false-positive.

**Comment by asudoh** [comment] 2017-11-11 01:06
This rule is against web page contents dictated by style. The problem with the AAT implementation is that it treats `::before`/`::after` pseudo elements as violations no matter it actually dictates web page content or not. You can search for `author:asudoh is:issue g1069` in our internal GHE for further details. Thanks!

**Comment by asudoh** [comment] 2017-11-11 02:00
Had a talk with @devanshah2 and he confirmed that the fix to treat empty `content` as non-violation has been in. I can see that in the source code. (Thanks @ devanshah2!)

@pkegbeto It’d be nice if you can upgrade your AAT tool to the latest version to see if the AAT tool still reports the issue. Thanks!

**Comment by pkegbeto** [comment] 2017-11-14 15:04
Ok. Thank you for following it up on the issue. I will upgrade thanks.
