### ISSUE TITLE
Carbon Icons could not shown in IE11

### ISSUE THREAD

**Issue by ChenCheress** [carbon-design-system/carbon#2942] opened 2019-06-03 09:05 UTC
#### 2. Icon name
All the carbon10 icons;
And components with carbon10 icons
#### 4. Box Link

Add in a box link (or other cloud) link to your completed Icon Contribution Template sketch file. Please make sure the permissions are set so anyone can view the icon.

#### 5. Screen Shot

Please add the following screen shots to this issue:
https://angular.carbondesignsystem.com/?path=/story/search--toolbar-search
visit the above link on ie, it won't display search icon
1.  Close-up screen shot of the icon with the pixel grid turned on
2.  Screen shot of the icon in context with your use case.

**Comment by dakahn** [comment] 2019-06-06 22:58
Tested Angular implementation on IE11 in Browserstack and confirmed the issue. ❌ 
Tested React implementation of Search in IE11 on Browserstack and no issue is present. ✔️

**Comment by cal-smith** [comment] 2019-06-08 04:03
Seems like the actual SVG content isn't rendering. My guess is these lines are at fault: https://github.com/carbon-design-system/carbon/blob/14fdd5c64b3250c43ecef455b7fbb3527bf795a2/packages/icons-angular/src/templates.js#L63-L65

On further research it appears that IE11 doesn't support `innerHTML` on SVG nodes. Because of course it doesn't.

**Comment by cal-smith** [comment] 2019-06-08 04:10
Based on the work done in [innerSVG](https://code.google.com/archive/p/innersvg/), it seems like some messing around with [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) will sort it out.

**Comment by cal-smith** [comment] 2019-06-10 19:02
closing in favor of #2826

**Closed as completed by cal-smith** 2019-06-10 19:02 UTC
Labels: type: bug 🐛, status: help wanted 👐, severity: 1, browser: ie11
