### ISSUE TITLE
DataTable - How to make rows disabled in order not to be selected when clicking on the SelectAll checkbox?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#6972] opened 2020-10-05 14:51 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
I disabled the `<TableSelectRow>` but when clicking on SelectAll these rows are selected, and I need them to be unselected.

## Relevant information
Tried to apply the disabled attribute to `<TableRow>` but it didn't help!
**Note**: I have a menu near the name of the row with "Info" option, so disabling the row might block this functionality -which is not wanted-

`<TableBody>
                                        {rows.map(row => (
                                            <TableRow key={row.id}>
                                                <TableSelectRow {...getSelectionProps({
                                                                        row, onClick: event => {
                                                                            //console.log(row.id, event.target.checked);
                                                                            this.selectRule(row.id, event.target.checked)
                                                                        }
                                                                    })
                                                                }
                                                                disabled={this.state.unattachedRulesTables[row.id] &&
                                                                this.state.unattachedRulesTables[row.id].length > 0}/>
                                                {row.cells.map(cell => (
                                                    <TableCell key={cell.id}>{cell.value}</TableCell>
                                                ))}
                                            </TableRow>
                                        ))}
                                    </TableBody>`

**Comment by zbeedatm** [comment] 2020-10-05 15:11
If I remove the `{...getSelectionProps}` from `<TableSelectRow>` it takes affect.
I need the SelectionProps to control the selection event, so how to make sure it's not overriding the disabled property?

**Comment by tw15egan** [comment] 2021-01-25 21:55
Hey there @zbeedatm, it seems like this may have been fixed as I am unable to reproduce your experience.

![table-select](https://user-images.githubusercontent.com/11928039/105770977-c429f200-5f14-11eb-9cfc-04a4e674a220.gif)

Going to close this as resolved, but feel free to comment here if you're still experience issues and I'll go ahead and reopen this.

**Closed as completed by tw15egan** 2021-01-25 21:55 UTC
Labels: type: question ❓, status: waiting for maintainer response 💬

**Comment by enriqueavilac** [comment] 2021-09-14 21:03
@tw15egan Can you share the code of the example that you show? I have the same problem as @zbeedatm.

**Comment by OmranAbazid** [comment] 2024-02-21 13:16
I had the same issue and It seems that adding a `disabled` attribute to the row object will make it work correctly.

**Comment by SaloniRathi** [comment] 2024-02-28 16:43
Hi @OmranAbazid ,
can you please share the code.

**Comment by OmranAbazid** [comment] 2024-02-28 16:48
It would be something like this:
```
<DataTable
        rows={[{...yourRowProperties, disabled: true}]}
...
```
