### ISSUE TITLE
IBM grid template causes Sketch to crash

### ISSUE THREAD

**Issue by rutgerhofste** [carbon-design-system/carbon#7957] opened 2021-03-03 10:46 UTC
## Detailed description

> Describe in detail the issue you're having.

When I download the file from the [Sketch cloud](https://www.sketch.com/s/3a3f3f2d-94d7-4c16-8e2e-88ba80a6382e) double click to open causes Sketch to crash. File -> import also fails

> Is this issue related to a specific component?

no

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

Sketch Version 70.6 (109241)
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1554.80.3.0.0 (iBridge: 18.16.14347.0.0,0)

System Software Overview:

  System Version:	macOS 11.2.2 (20D80)
  Kernel Version:	Darwin 20.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

**Comment by tw15egan** [comment] 2021-03-03 17:56
Do you have any more steps to reproduce the issue? I'm able to download and open the sketch file without any issues

Running Sketch v70.6, MacOS 11.3 Beta. Just to troubleshoot, can you restart your Mac and try downloading the link again? If not that, perhaps try reinstalling Sketch?

@carbon-design-system/design can you confirm you are also able to download and open the link?

**Comment by laurenmrice** [comment] 2021-03-03 18:29
I am able to download and open the file with that link without it crashing. I also am using v70.6, MacOS 11.2.1.

This may be a Sketch program specific problem if the issue is not fixed after doing the steps @tw15egan mentioned.

**Comment by johnbister** [comment] 2021-03-03 19:08
Sketch v70.6, MacOS 11.2.1 worked OK for me ✅

**Comment by mariuszmickiewicz** [comment] 2021-03-05 23:18
Sketch had a lot of crashes related to the plugins recently, this is what they were trying to fix in 70.5 and again 70.6 - maybe they didn't manage to fix it all.

**Comment by tw15egan** [comment] 2021-03-12 01:57
Closing as we are unable to reproduce

**Closed as completed by tw15egan** 2021-03-12 01:57 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬
