### ISSUE TITLE
[Bug]: Module parse failed: Export 'Infinity' is not defined 

### ISSUE THREAD

**Issue by IRediTOTO** [carbon-design-system/carbon#15360] opened 2023-12-09 06:35 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

1.45.0

### React version

18.2.0

### Description

Hi, I am trying to install Carbon react to Nextjs 14.0.4, I am learning from tutorial https://carbondesignsystem.com/developing/react-tutorial/step-1/
I get this error 
```
./node_modules/@carbon/icons-react/es/generated/bucket-8.js
Module parse failed: Export 'Infinity' is not defined (2622:1217)
|     WatsonHealthLaunchStudy_2.propTypes = iconPropTypes;
| }
```

### Reproduction/example

https://github.com/carbon-design-system/carbon-tutorial-nextjs/tree/v11-next-step-5

### Steps to reproduce

Just need upgrade nextjs to 14.0.4
@carbon/react to 1.45.0

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment] 2023-12-10 07:31
Hi there! This is a duplicate of [this issue](https://github.com/carbon-design-system/carbon/issues/15306). Thank you!

**Comment by tay1orjones** [comment] 2023-12-12 14:28
Duplicate of https://github.com/carbon-design-system/carbon/issues/15306

**Closed as not planned by tay1orjones** 2023-12-12 14:28 UTC
Labels: type: bug 🐛
