### ISSUE TITLE
ContentSwitcher: icon only variant

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#9843] opened 2021-10-11 23:48 UTC
For certain use cases and context an icon only variant of the ContentSwitcher is required
![image](https://user-images.githubusercontent.com/40970507/136868115-19ec2a95-253e-4802-a1ed-4ed41d5be9be.png)

**Comment by tay1orjones** [comment] 2022-06-17 21:03
Duplicate of https://github.com/carbon-design-system/carbon/issues/6982

**Closed as completed by tay1orjones** 2022-06-17 21:03 UTC
Labels: type: enhancement 💡, component: content-switcher, proposal: accepted
