### ISSUE TITLE
<Dropdown /> doesn't render title tooltip on hover in firefox

### ISSUE THREAD

**Issue by SwapnilAhire** [carbon-design-system/carbon#8864] opened 2021-06-09 05:32 UTC
BUG -

    [Firefox 88.0.1] Tool tip is not rendered when I hover over any of the option in drop down .
    [Chrome/Firefox] There's a blue bottom line shows when I select any option from the drop down, instead it should show blue rectangle outline.

Description -

    I am on Firefox 88.0.1 and @carbon/ibm-security is at 1.41.0
    Attached screenshots that explains the issues.

![image](https://user-images.githubusercontent.com/6366084/121298707-ef383f80-c911-11eb-98eb-3584b57899cd.png)
![image](https://user-images.githubusercontent.com/6366084/121298729-feb78880-c911-11eb-9f31-31173194a334.png)

Actual implementation:
![image](https://user-images.githubusercontent.com/6366084/121298783-155ddf80-c912-11eb-8fb2-3e97da914d30.png)
![image](https://user-images.githubusercontent.com/6366084/121298802-1abb2a00-c912-11eb-9489-9a55294dae1e.png)
![image](https://user-images.githubusercontent.com/6366084/121298833-227ace80-c912-11eb-9b3e-901296a76aa2.png)

Expected behavior -

    Tool tip should render while hovering over any of the options in the drop down on Firefox browser
    On Chrome/Firefox, the blue outline rectangle should display for the selected option in the drop down

Actual behavior -

    Tool tip does not render on Firefox version 88.0.1, for Chrome browser it works as expected.
    On Chrome/Firefox, it shows just blue bottom outline below the selected option in the drop down

Steps for reproducing -

(TRY it in both Chrome and Firefox and hover over ellipsised text option)
Sandbox URL - https://codesandbox.io/s/stupefied-bush-ntvn0?file=/src/index.js

Browsers

    Firefox 88.0.1
    Chrome 90.0.4430.212

Optional information
 - none

**Comment by joshblack** [comment] 2021-06-22 20:37
Hi @SwapnilAhire! 👋 Thanks so much for taking the time to make this issue. Can confirm the text truncation browser tooltip issue, having a hard time re-creating the focus border issue though. Could you share more steps to reproduce?

**Comment by SwapnilAhire** [comment] 2021-06-23 09:12
@joshblack Thanks for you valuable feedback. After global css fix for dropdown, I can confirm that the focus border issue has been resolved and its not related to component at all but the tooltip issue still exists.

**Comment by SwapnilAhire** [comment] 2021-07-20 05:51
@joshblack @tay1orjones Could anyone of you please help me with the list of packages that need to be updated to fix this issue?

**Comment by tay1orjones** [comment] 2021-07-26 15:55
@SwapnilAhire A fix for this hasn't been delivered yet. 

I looked into this a bit, it doesn't look like there is a way to control the browser based title tooltips. I'm not sure why they're not being shown in Firefox. We may need to lump this in with moving all browser-based `title` tooltips to use the Carbon tooltip, https://github.com/carbon-design-system/carbon/issues/9208

**Comment by toeikmei** [comment] 2022-02-21 12:54
Hi @tay1orjones @joshblack has there been some progress? We are still facing the issue with the tooltip.

**Comment by dakahn** [comment] 2022-05-02 22:10
Im looking at this issue now. It seems like `title` is being unset in Firefox 😕 
_Firefox_
![image](https://user-images.githubusercontent.com/40970507/166335238-aca24008-6f0e-425f-85f1-937d2ad340d4.png)
_Chrome_
![image](https://user-images.githubusercontent.com/40970507/166335352-34f43f04-ee6d-4bc6-b4c1-29737bd1503a.png)

**Comment by dakahn** [comment] 2022-06-02 22:13
Seems to be a rounding issue unique to Firefox, commented on a closed issue here
https://bugzilla.mozilla.org/show_bug.cgi?id=1250824

**Comment by tay1orjones** [comment] 2022-06-17 20:52
Leaving this open as it's outstanding, just blocked by firefox. 

The intent is still to more broadly fix/avoid this issue by implementing https://github.com/carbon-design-system/carbon/issues/9208. It's an accepted proposal but is not yet planned for the core team to implement. Contributions definitely welcome! 🙏

**Comment by guidari** [comment] 2023-11-27 15:03
I just tested on Firefox and now we have the tooltip working as expected.

The tooltip
![Image](https://github.com/carbon-design-system/carbon/assets/52183462/caf4903b-3800-4172-a9ff-a7d6d5be28c6)

The code with `title` showing up
![Image](https://github.com/carbon-design-system/carbon/assets/52183462/be159c80-55dc-4cde-bdbb-5774074395af)

**Closed as completed by guidari** 2023-11-27 15:03 UTC
Labels: type: bug 🐛, severity: 2, role: dev 🤖, package: react, component: dropdown, browser: firefox
