### ISSUE TITLE
[TableToolbarSearch] useEffect should be controllable for persistent mode

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#3240] opened 2019-07-01 15:15 UTC
## What package(s) are you using?

- [x] `carbon-components` `10.3.2`
- [x] `carbon-components-react` `7.3.2`

## Detailed description

By now the `useEffect` hook fires on every component update.

It should be possible to control the useEffect, because the input focus is executed each time the component updates and in some use cases this may lead to user experience issues.

In my current project case I use the `TableToolbarSearch` component in persistent mode. At the bottom of the table I've placed a button to append more rows to the end of the table. Unfortunately the useEffect causes the browser to scroll to the top of the window instead of just staying at the position of the page to see the new rows.

https://github.com/carbon-design-system/carbon/blob/10b9d2c07584e490aad463dcda580f9454d166eb/packages/react/src/components/DataTable/TableToolbarSearch.js#L48-L52

## Steps to reproduce the issue

1. `TableToolbarSearch` in persistent mode.
2. Perform some runtime updates on the `DataTable` (i.e. add rows to the table)

[![Edit codesandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/codesandbox-82cvg?fontsize=14)

**Comment by abbeyhrt** [comment] 2020-03-24 19:58
Hi @IOIO72! 👋 Thank you for providing a code sandbox! At version `10.3.2` and `7.3.2` this problem does appear but when you update the version, the issue is gone! It seems like this has been addressed in more recent versions of Carbon. I'm going to close this for now but feel free to let me know if it needs to be reopened.

**Closed as completed by abbeyhrt** 2020-03-24 19:58 UTC
Labels: type: bug 🐛
