### ISSUE TITLE
Tabs react error on safari mobile

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#7320] opened 2020-11-19 23:43 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
When the tabs component is scrolled forward and back several times, it results in an error due to exceeding max stack size.

https://reactjs.org/docs/error-decoder.html/?invariant=185

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

![IMG_261081643215-1](https://user-images.githubusercontent.com/20601623/99736705-d743c000-2a94-11eb-84e7-6d320356b9ed.jpeg)

> Describe in detail the issue you're having.

Tabs component causes react error on safari mobile

> Is this issue related to a specific component?

Tabs

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Error fixed

> What browser are you working in?

Safari on IOS 14.2

> What version of the Carbon Design System are you using?

x.23.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Docs

## Steps to reproduce the issue

1. On an iphone, go to https://react.carbondesignsystem.com/iframe.html?id=tabs--default
2. Keep scrolling left and right until the error appears (I'm unable to pinpoint a scenario that reproduces the error in a consistent time frame, the video I captured took about 40 seconds but I have seen the error in as little as 5 seconds of scrolling)

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information
I have a 40 second mp4 screen recording, let me know if you would like me to upload this to your preferred file sharing site or I can send it to you directly on slack.

**Comment by dakahn** [comment] 2021-01-11 17:45
Hey, thanks for reporting. We can recreate this (on various mobile), but we're not sure why it's happening yet. Watch this space for an update.

**Comment by joshblack** [comment] 2021-03-08 16:11
Duplicate of #6933

**Closed as completed by joshblack** 2021-03-08 16:11 UTC
