### ISSUE TITLE
React UI Shell components don't set 'aria-label' attribute

### ISSUE THREAD

**Issue by ZhekaVasil** [carbon-design-system/carbon#3195] opened 2019-06-27 08:12 UTC
## Environment

> Operating system Windows 10

> Browser Chrome, FF

## Detailed description

> What version of the Carbon Design System are you using?
```
"carbon-components": "^10.2.0",
"carbon-components-react": "^7.2.0",
```

> What did you expect to happen?
When I pass `aria-label` prop to a React UI Shell components like :
```
<HeaderMenu aria-label="Recommended">
```
I would expect the label will be rendered in DOM

> What happened instead?
There is an error in console:
![image](https://user-images.githubusercontent.com/18385315/60247636-ad9b5f00-98c9-11e9-9347-a221adaf38d6.png)

## Steps to reproduce the issue

1. Add `aria-label` attribute to <HeaderMenu> React component inside UI Shell
2. Open the UI Shell in browser
3. There is an error in console

> Please create a reduced test case in CodeSandbox
> - React:
https://codesandbox.io/embed/codesandbox-8bmtz

**Comment by tw15egan** [comment] 2019-06-27 17:54
Can you try bumping up to `10.3` / `7.3`? Seems like the issue is resolved with that release: 

https://codesandbox.io/s/codesandbox-murxm

**Comment by ZhekaVasil** [comment] 2019-06-27 19:49
Thanks, indeed, it works fine in `10.3 / 7.3`

**Closed as completed** 2019-06-27 19:49 UTC
Labels: type: a11y ♿
