### ISSUE TITLE
[Bug]: Some components are missing "index" files (both .js and .d.ts), which breaks auto-complete

### ISSUE THREAD

**Issue by rwibm** [carbon-design-system/carbon#14569] opened 2023-09-01 17:14 UTC
### Package

@carbon/react

### Package version

1.36.0

### React version

18.2.0

### Description

When using some components in the react package they are missing index files, which WebStorm uses for parsing imports.
This causes auto-complete to break and shows loads of linting errors on pages where these components are used.

I've looked into this and it seems to be due to the components I'm using (anything in UIShell and StructuredList) not including index files within the components. This works fine when I go to compile with vite (WebPack/WebStorm doesn't like it unless I import from @carbon/react/es/components/UIShell, but this full import path doesn't work in vite), but the IDE never detects these imports unless I manually add an index file to the correct place within node_modules, which fixes it (WebPack, WebStorm, and Vite are all happy importing from "@carbon/react" with the index files added to UIShell and StructuredList).

Most other components have these indexes, and work fine just like these do after adding the missing indexes, but obviously manually creating an index every time I update carbon is not a reasonable workaround.

![image](https://github.com/carbon-design-system/carbon/assets/85178678/07de5f34-ecd1-4cf3-bf32-ed038035a5ea)

Left: node_modules/@carbon/react/js/components/UIShell/index.d.ts [new file], right: project file using the imported components.

The screenshot above shows the working import for Toggle, and broken imports for everything inside UIShell other than the few items I manually added to an index file as a test fix.

I've tried so many different config options and things that make webstorm work break vite, and vice versa, so it would be really nice if the carbon team can add these missing indexes to the official repo pretty please.

P.S. this isn't a typescript issue,  when I was using JS in carbon v10 it also used to have the exact same problem with these 2 components too!

### Reproduction/example

N/A as vite processes these imports correctly, WebStorm and WebPack don't

### Steps to reproduce

1. Create a blank project using Carbon within WebStorm
2. Try to use any component within UIShell or StructuredList
3. WebStorm and WebPack will not recognise the import paths due to missing indexes

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM Internal

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by rwibm** [comment] 2023-10-13 12:51
Just noting here for reference: this issue also seems to affect both Modal and MultiSelect components too

**Comment by tay1orjones** [comment] 2023-11-09 16:00
@rwibm Thanks for reporting. This looks to me like the IDE is flagging the items that don't have a TypeScript definition file yet. I think this might be a duplicate of https://github.com/carbon-design-system/carbon/issues/13091?

**Comment by rwibm** [comment] 2023-11-22 16:41
Ah yes, apologies, I must have missed that one. Feel free to close this issue if it's not needed.

**Comment by tay1orjones** [comment] 2024-03-12 00:10
Duplicate of https://github.com/carbon-design-system/carbon/issues/13091

**Closed as not planned by tay1orjones** 2024-03-12 00:10 UTC
Labels: severity: 3, type: bug 🐛, status: help wanted 👐, role: dev 🤖, area: typescript, needs: community contribution
