### ISSUE TITLE
Combobox - filter search is inconsistent between single and multi-select versions

### ISSUE THREAD

**Issue by yashgarg17** [carbon-design-system/carbon#7589] opened 2021-01-18 14:36 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
There are primarily 2 versions of the `Combobox` component are available - 
`single-selection` - https://angular.carbondesignsystem.com/?path=/story/components-combobox--basic
`multi-selection` - https://angular.carbondesignsystem.com/?path=/story/components-combobox--multi-select

We have observed inconsistent behaviour while applying same filter in both the versions. 
In case of `single-select`, if the search value is not present, then all the options are displayed - 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/43729292/104694319-0e4eee80-5731-11eb-8bca-3f5cb23ee0c9.png">

But in case of `multi-select`, if the searched value is not present, then no options are listed - 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/43729292/104694476-3f2f2380-5731-11eb-9e61-f15f119d1909.png">

Filtering should be consistent across the versions.

> Is this a feature request (new component, new icon), a bug, or a general issue?
`BUG`

> Is this issue related to a specific component?
It is specific to `Combobox` component

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected behaviour - 
If the searched value is not matching with any of the options available, then it should show nothing as in case of `multi-select` version of `Combobox` component

Actual behaviour - 
In case of `single-select`, if the search value is not present, then all the options are displayed

> What browser are you working in?
`Chrome`

> What version of the Carbon Design System are you using?
`4.36.1`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
`IBM Cloud Brokerage - Cost and Asset Management`

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/?path=/story/components-combobox--basic
2. Search for any text which is not matching with any of the options. For example - `test`
3. Observe that all the available options are displayed, even though `test` is not matching with any of the options

<img width="407" alt="image" src="https://user-images.githubusercontent.com/43729292/104694319-0e4eee80-5731-11eb-8bca-3f5cb23ee0c9.png">

4. Now go to https://angular.carbondesignsystem.com/?path=/story/components-combobox--multi-select
5. Search for any text which is not matching with any of the options. For example - `test`
6. Observe that no option is displayed, because `test` is not matching with any of the options

<img width="329" alt="image" src="https://user-images.githubusercontent.com/43729292/104694476-3f2f2380-5731-11eb-9e61-f15f119d1909.png">

**Comment by andreancardona** [comment] 2021-01-28 21:52
@aagonzales @laurenmrice hey you two! Sorry for tagging you both - just wanted to get design opinion on this - on what is the expected behavior in this situation for combobox. 

Thank you!

**Comment by laurenmrice** [comment] 2021-01-29 15:30
I believe that both the combobox and filterable multi-select are functioning correctly.

[Combobox](https://www.carbondesignsystem.com/components/dropdown/usage#combo-box):
Since “test” is not an existing option within the menu, all options will remain visible in the menu when searching for “test”. If “test” was an existing option in the menu, the “test” option would be tabbed to inside of the menu and highlighted on hover. You are not filtering out the options in the menu like you do with the filterable multi-select. 

[Filterable Multi-select](https://www.carbondesignsystem.com/components/dropdown/usage#multiselect):
Since “test” is not a current option within the menu, while typing “test” the options that start to match your entry remain in the menu while other existing options that do not match your entry are temporarily removed. If there is no match after you have finished typing, all options will be temporarily filtered out of the menu.

Edit: Also I noticed that you are linking from the Angular storybook and we maintain a different storybook: https://carbon-components-react.netlify.app/?path=/story/accordion--accordion . Our filterable multi-select is not classified as a combobox.

**Comment by andreancardona** [comment] 2021-01-29 16:33
@yashgarg17 Closing this issue for now - since it is expected behavior. Feel free to comment or reopen if we are missing something. Thank you! :)

**Closed as completed by andreancardona** 2021-01-29 16:33 UTC
Labels: severity: 3, type: bug 🐛, package: components, component: combobox
