### ISSUE TITLE
[Bug]: Button icon not aligned with text

### ISSUE THREAD

**Issue by btepe** [carbon-design-system/carbon#15957] opened 2024-03-14 10:07 UTC
### Package

@carbon/react

### Package version

1.53.0

### Description

After the last change in https://github.com/carbon-design-system/carbon/pull/15585 released with 1.49.0, the icons inside buttons that also contain text are not vertically centered anymore.

### Screenshots

This is what they look like now:
<img width="276" alt="Screenshot 2024-03-14 at 10 59 56" src="https://github.com/carbon-design-system/carbon/assets/24353185/f189e258-4559-456f-b4ed-5f202f2908ac">

### Steps to reproduce

Go to https://react.carbondesignsystem.com/?path=/docs/components-button--overview#button-rendericon and look at the buttons containing icons. The icons are not centered vertically.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2024-03-14 13:54
@btepe is this an issue you only see in the `mdx` docs files? Can't reproduce it on [StackBlitz](https://stackblitz.com/edit/github-be93tu?file=src%2Findex.scss,package.json)

**Comment by btepe** [comment] 2024-03-18 09:54
@tw15egan No, I saw this issue first in a project I'm working on, because snapshot tests were failing due to the misaligned icon. I will try to reproduce this in Stackblitz as well and get back to you.

**Comment by andreancardona** [comment] 2024-04-01 14:48
@btepe Feel free to reopen if you are able to reproduce the issue. I am closing for now :)

**Closed as completed by andreancardona** 2024-04-01 14:48 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs reproduction
