### ISSUE TITLE
Some dialog types should not allow for user to close dialog by clicking background overlay

### ISSUE THREAD

**Issue by mitchellbernstein** [carbon-design-system/carbon#8731] opened 2021-05-20 20:28 UTC
## Detailed description

User should only be allowed to click the overlay background with passive dialog types to close the dialog. Instead, 

Related to the modal component.

Expected: User should ONLY be allowed to click background overlay on passive dialog types to close them. Other types should not allow this behavior. It should not be optional.

Brave, Chrome, Firefox, Safari

Carbon website demos

https://www.carbondesignsystem.com/components/modal/usage/#live-demon

**Comment by joshblack** [comment] 2021-06-14 14:52
cc @carbon-design-system/design wanted to reach out to confirm UX here for Modal 👀  The request is that certain types of Modals should prohibit clicking the background overlay to close.

**Comment by aledavila** [comment] 2021-06-21 16:28
Hi @mitchellbernstein I am going to close this issue because we have a fix for this. We have a prop called 'onRequestClose' that takes in a function where a user can pass in the intended behavior. 

Here's a related issue: https://github.com/carbon-design-system/carbon/issues/4493

Let us know if you have further questions.

**Closed as completed by aledavila** 2021-06-21 16:28 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬
