### ISSUE TITLE
[Bug]: ContainedList within Popover can cause visual defects when placed too high on page

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#13849] opened 2023-05-22 12:00 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.29.1

### Description

The ContainedList's header is using `position: sticky` to always be present when the user scrolls through the list.
Popover is rendering the content above the trigger by default and positions it according to the `align` prop with the help of `transform`.

When you mix these together, you're potentially running into weird visual defects as the ContainedList's header will reference the top of the viewport as its border and is unaffected by the `transform`. Therefore, for popovers that open below or next to the trigger, the sticky header will can end up rendering in the middle or at the bottom of the list.

### Reproduction/example

https://stackblitz.com/edit/github-2zklns?file=src%2FApp.jsx

### Steps to reproduce

1. In the reproduction link, inspect the `.cds--popover-content` element
2. Toggle the `transform` css property

With `transform` applied; ContainedList header renders in the middle of the list:
<img width="133" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/ff116301-f51f-40e0-82e7-66aea6ac6d49">

With `transform` removed; the reference point of ContainedList header is clearly visible:
<img width="179" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/dc62e05f-4a14-49e9-a8ad-f4e8dd36ad80">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-07-27 16:44
Dependent on #13950 as the entire structure of the ContainedList needs to become a table

**Comment by tay1orjones** [comment] 2024-06-26 13:56
This was fixed in https://github.com/carbon-design-system/carbon/pull/14654, I've made an [updated version of your stackblitz](https://stackblitz.com/edit/github-2zklns-kotasp?file=src%2FApp.jsx) showing the result.

Generally it works as intended, though there are some unique quirks due to the header being position sticky. From [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky):

> Note that a sticky element "sticks" to its nearest ancestor that has a "scrolling mechanism" (created when overflow is hidden, scroll, auto, or overlay), even if that ancestor isn't the nearest actually scrolling ancestor.

This means that if the PopoverContent is scrolled vertically so that part of the container is above the top of the viewport, the ContainedList header becomes 'sticky' to the viewport. 

https://github.com/carbon-design-system/carbon/assets/3360588/ab178747-9a05-4a33-82ab-652bc80feaec


This behavior is intended but can be modified in a few ways:

1. Place `overflow: scroll` on `.cds--popover-content`. This makes the popover content element the "nearest scrolling ancestor" without actually making it scroll. So the header remains fixed to the popover content and scrolls away.

https://github.com/carbon-design-system/carbon/assets/3360588/0eb05a6f-08f6-47d4-80be-f8638abaee64

2. Adding on to this, if you'd prefer you can also add a fixed height to `.cds--popover-content` which makes it actually scrollable within the popover content and the header sticks to the top of that container

https://github.com/carbon-design-system/carbon/assets/3360588/357dab3d-661b-48ba-9523-6af1a8082e75

**Closed as completed by tay1orjones** 2024-06-26 13:56 UTC
Labels: type: bug 🐛, severity: 2, status: blocked 🙅‍♀️, role: dev 🤖, component: contained-list
