### ISSUE TITLE
[Bug]: MenuButton no longer works with nested menu items (previously did work)

### ISSUE THREAD

**Issue by kurtwaldowski-b** [carbon-design-system/carbon#16989] opened 2024-07-17 20:26 UTC
### Package

@carbon/react

### Package version

v1.53.1

### React version

v18.3.1

### Description

When using nested menu items inside of a Menu Button, it no longer works as expected and causes strange behavior where the nested menus appear inside the original menu container.

### Reproduction/example

https://stackblitz.com/edit/vitejs-vite-v3uswe?file=src%2FApp.tsx

### Steps to reproduce

Click on the menu button in the stack blitz and observe:
![image](https://github.com/user-attachments/assets/643c23ce-f58b-4167-a2b1-a0fa27b23b8c)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2024-07-18 15:48
Duplicate of https://github.com/carbon-design-system/carbon/issues/15875

**Comment by tay1orjones** [comment] 2024-07-18 15:48
See See https://github.com/carbon-design-system/carbon/issues/15875#issuecomment-2233532476

**Closed as not planned by tay1orjones** 2024-07-18 15:48 UTC
Labels: type: bug 🐛, role: dev 🤖, status: needs triage :female_detective:, status: waiting for maintainer response 💬, component: menu-button

**Comment by kurtwaldowski-b** [comment] 2024-07-29 13:40
@tay1orjones  Thanks! Apologies for the dup
