### ISSUE TITLE
[Button]: Default value set for deprecated property

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#3427] opened 2019-07-17 12:24 UTC
## What package(s) are you using?

- [x] `carbon-components` `10.4.1`
- [x] `carbon-components-react` `7.4.1`

## Detailed description

The console warns about deprecated `small` property for Buttons.
This is caused by the default setting of the property inside the Button component.

https://github.com/carbon-design-system/carbon/blob/9d0e8284f96f3e63fc2432ea7213049d09b550ad/packages/react/src/components/Button/Button.js#L208

## Steps to reproduce the issue

1. Use React carbon component Button.
2. See the console.log

**Comment by emyarod** [comment] 2019-07-17 13:09
looks like this is a duplicate of https://github.com/carbon-design-system/carbon/issues/3413 and will be addressed in https://github.com/carbon-design-system/carbon/pull/3415

**Closed as completed** 2019-07-18 04:44 UTC
Labels: type: bug 🐛
