### ISSUE TITLE
Bug In UIShell/Link.js 

### ISSUE THREAD

**Issue by ericlowry** [carbon-design-system/carbon#3135] opened 2019-06-21 10:20 UTC
Starting on line 22 of the carbon-components-react UIShell/Link.js :
```
const LinkPropTypes = {
  /**
   * The base element to use to build the link. Defaults to `a`, can also accept
   * alternative tag names or custom components like `Link` from `react-router`.
   */
  element: PropTypes.elementType,
};
```

It should be 
```
const LinkPropTypes = {
  /**
   * The base element to use to build the link. Defaults to `a`, can also accept
   * alternative tag names or custom components like `Link` from `react-router`.
   */
  element: PropTypes.element,
};
```

Note: elementType is not a valid react propType...

**Comment by emyarod** [comment] 2019-06-21 14:08
is there a warning being emitted regarding this prop type?

to my knowledge, `PropTypes.elementType` is valid https://github.com/facebook/prop-types/blob/master/factoryWithTypeCheckers.js#L285-L295

**Comment by ericlowry** [comment] 2019-06-23 16:10
I see you are correct... elementType is supported, but I am getting the following warning:

```
Warning: Failed prop type: Invalid prop `element` of type `string` supplied to `Link`, expected a single ReactElement.
    in Link (created by HeaderName)
    in HeaderName (at App.js:41)
    in header (created by Header)
    in Header (at App.js:39)
    in div (at App.js:38)
    in App (at src/index.js:7)
```

Note: I am just cutting and pasting the UIShell Example Code...

The following snipped of JSX causes the error:

```
 function App() {
  return (
    <div className="App">
      <Header aria-label="IBM Platform Name">
        <HeaderName
          href="https://ibm.com"
          prefix="IBM"
        >
          TEST
        </HeaderName>
      </Header>
    </div>
  );
}

```

**Comment by abbeyhrt** [comment] 2020-01-16 21:03
Hi @ericlowry! I'm not able to recreate that warning with the code you provided and the newest version of Carbon, are you still able to reproduce it?

**Comment by abbeyhrt** [comment] 2020-01-31 16:58
Since we aren't able to reproduce the warning and there hasn't been a response, I'm going to close this issue. Feel free to `@` me if you are still having this problem and I will re-open this issue! 👍

**Closed as completed by abbeyhrt** 2020-01-31 16:58 UTC
Labels: type: bug 🐛, severity: 4, package: react, component: ui-shell
