### ISSUE TITLE
[Bug]: It is possible to type letters in the NumberInput (Firefox)

### ISSUE THREAD

**Issue by RadekKpc** [carbon-design-system/carbon#10279] opened 2021-12-13 11:26 UTC
### Package

carbon-components-react

### Browser

Firefox

### Package version

v7.50.0

### Description

Hi,
I found out a difference in the NumberInput behaviour in Chrome and Firefox. In the Chrome we can not type letters in the field, but it is possible in the Firefox browser.
Please look into it.

![obraz](https://user-images.githubusercontent.com/48159370/145803662-680919f1-b2f9-44ca-acac-745ea76c84ae.png)

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/docs/components-numberinput--default

### Steps to reproduce

1. Type some letters in the NuberInput in the Firefox browser.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2021-12-13 15:52
Hi @RadekKpc, thanks for reporting. This is something that the browsers disagree on, see [this bugzilla thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528) for more info. Also related, https://github.com/carbon-design-system/carbon/issues/5658

Adding a validation function to enable preventing numbers from being entered is something that has been discussed but not yet implemented, https://github.com/carbon-design-system/carbon/issues/7039. We'd welcome a PR if you're interested in contributing!

**Comment by tay1orjones** [comment] 2021-12-15 19:23
Duplicate of #7039

**Closed as completed by tay1orjones** 2021-12-15 19:23 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
