### ISSUE TITLE
Lists are not left aligned

### ISSUE THREAD

**Issue by snrubnomis** [carbon-design-system/carbon#5487] opened 2020-02-28 18:18 UTC
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Ordered and Unordered lists have bullets/numbers which stick out to the left so they do nont align well with other content.

> Is this issue related to a specific component?

`OrderedList` and `UnorderedList`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

According to carbon designers the lists should be left aligned so that the bullets/numbers line up with other content and do not stick out to the left.

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

carbon: 10.9.3
carbon-components-react: 7.9.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Create a page with an OrderedList and/or UnorderedList that also has some content above/below the list
2. See that the list bullets/numbers do not align properly

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment] 2020-02-28 18:25
cc @jeanservaas this is the issue I was talking about

See https://ibm-studios.slack.com/archives/C046Y0YUD/p1582649842035000

Specifically this image: 
![image](https://user-images.githubusercontent.com/11928039/75575239-18f08e80-5a60-11ea-83ce-ad37d89c92ee.png)

We need to add some `left-padding` to avoid the bullets/numbers from sticking out

**Comment by joshblack** [comment] 2020-10-09 21:05
bump @tw15egan is this still an issue? 👀

**Comment by tw15egan** [comment] 2020-10-12 18:44
It is still the current implementation, never received any response from design if this was intentional

![Screen Shot 2020-10-12 at 11 44 06 AM](https://user-images.githubusercontent.com/11928039/95780204-4d782a00-0c80-11eb-8caf-735a1896cfdc.png)

**Comment by tw15egan** [comment] 2021-01-27 23:01
Closing this since this seems to be working as intended by design

**Closed as completed by tw15egan** 2021-01-27 23:01 UTC
Labels: type: bug 🐛, component: list
