### ISSUE TITLE
OverflowMenu should close when focus leaves the menu while tabbing on keyboard

### ISSUE THREAD

**Issue by chubbywhale** [carbon-design-system/carbon#1687] opened 2019-01-24 16:48 UTC
## Title line template: [Title]: Brief description
OverflowMenu should close when focus leaves the menu while tabbing on keyboard

## Detailed description
> Is this issue related to a specific component?
OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?
While OverflowMenu when is opened and navigating through it by tabbing on the keyboard, if the focus is placed on element that is located outside of the OverflowMenu, it should close the menu. This behaviour on the VanillaJS and Angular version of carbon components. Click outside the menu will close it which is working great, but tabbing should have similar behaviour.

> What browser are you working in?
Chrome 71.0.3578.98 (Official Build) (64-bit)
FF 60.4.0esr (64-bit)

> What version of the Carbon Design System are you using?
"carbon-components": "^9.68.8",
"carbon-components-react": "^6.81.3",
"carbon-icons": "^7.0.7",
"react": "^16.6.3",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
The OverflowMenu component in the React Carbon Component is currently having this behaviour:
http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

## Additional information

- Screenshots or code
- Notes

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asudoh** [comment] 2019-01-25 05:04
Hi :wave: given this issue seems to refer to our React code, looks that it's a duplicate of IBM/carbon-components-react#1783. Please let us know if you think otherwise. Thanks!

**Closed as completed by asudoh** 2019-01-25 05:04 UTC
