### ISSUE TITLE
Pagination: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10425] opened 2022-01-13 16:26 UTC
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Variants
- Default (data table)
- Pagination nav (standalone)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [x] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [x] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [x] Develop

**Comment by tw15egan** [comment] 2022-01-24 19:18
With the move to `IconButton`, `Pagination` is currently not rendering any icons. Should we update the v10 `Pagination` to use `IconButton` to fix this issue? 

<img width="859" alt="Screen Shot 2022-01-24 at 2 17 04 PM" src="https://user-images.githubusercontent.com/11928039/150849229-85816ad6-db46-4f23-a1db-8f3e5533d4a2.png">

**Comment by tw15egan** [comment] 2022-01-26 16:10
`of 4 pages` text is using `text-secondary`. Is this correct or should this be using `text-primary`? Sketch file only mentions the Items per page text and the 1-10 text

<img width="197" alt="Screen Shot 2022-01-26 at 11 07 23 AM" src="https://user-images.githubusercontent.com/11928039/151200646-c85588fe-e0c0-4b51-ace0-7f18ec9b15b3.png">

**Comment by tw15egan** [comment] 2022-01-26 16:17
**Component sizes**

- [ ] Component size props have no effect in the new storybook. The class is being properly added, but styles are not there. Digging deeper, it seems the size styles have not been ported to the new `@carbon/styles` repo

**Comment by tw15egan** [comment] 2022-01-26 16:44
**Storybook**

- [ ] Prop table is population, but there are no knobs/controls to play with the different prop values.

**Comment by tw15egan** [comment] 2022-01-26 17:02
Getting some new a11y violations, but I think this is due to the button regression that should be fixed via #10510 

<img width="979" alt="Screen Shot 2022-01-26 at 12 01 18 PM" src="https://user-images.githubusercontent.com/11928039/151210680-dc17f681-fdea-4f8c-81b8-fc80ad0c7fa8.png">

**Comment by laurenmrice** [comment] 2022-02-18 16:01
## Visual bugs

### scss
- [ ] `label` `type-style` should be type token `body-compact-01`.
- [ ] `select-input`  `type-style` should be type token `body-compact-01`.
- [ ] `select-input:hover` should be color token `$layer-hover`.
- [ ] Check to make sure all spacing tokens use the format `$spacing-` instead of having to prefix the token with `$carbon--`.
- [ ] Yes @tw15egan this should be using color token `$text-primary`.
> `of 4 pages` text is using `text-secondary`. Is this correct or should this be using `text-primary`? Sketch file only mentions the Items per page text and the 1-10 text
> 
> <img width="197" alt="Screen Shot 2022-01-26 at 11 07 23 AM" src="https://user-images.githubusercontent.com/11928039/151200646-c85588fe-e0c0-4b51-ace0-7f18ec9b15b3.png">

**Comment by laurenmrice** [comment] 2022-02-18 16:09
### Design kit

Looks good ✅

**Comment by tw15egan** [comment] 2022-03-02 19:28
Looks good from a dev perspective 👍🏻

**Comment by tay1orjones** [comment] 2022-04-11 15:10
Live demo updates appear to be the only thing left for this one, we've got an issue for it:

- https://github.com/carbon-design-system/carbon/issues/10889

**Closed as completed by tay1orjones** 2022-04-11 15:10 UTC
Labels: component: pagination
