### ISSUE TITLE
Time Picker with a long invalid message is badly formatted

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#2166] opened 2019-03-21 11:26 UTC
## Detailed description

A long invalid message text in the time picker causes the formatting to be blown.

## Steps to reproduce the issue

1. Supply a long invalid message, can be done by tweaking the 

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components/tree/master/examples/codesandbox

## Additional information
Version 10 beta

![image](https://user-images.githubusercontent.com/15086604/54749359-32d8ee80-4bcc-11e9-8b97-f10ff8d8bd02.png)

**Comment by emyarod** [comment] 2019-03-21 13:08
can you provide more information about your dev environment/package versions? I believe this was addressed by https://github.com/IBM/carbon-components/pull/2099 but if this is not the case, I would like to be able to replicate the issue

**Comment by lee-chase** [comment] 2019-03-22 17:48
This is seen in the Vue implementation of using CSS from 9.87.2
http://vue.carbondesignsystem.com/?path=/story/default-cvtimepicker--invalid-slot

The vanilla implementation (latest source - March 22nd). Does not have a sample showing the invalid text. However, if I force it on and write a lot of text it does show this.

![image](https://user-images.githubusercontent.com/15086604/54842617-42d6f800-4cca-11e9-90c6-8c6adc1e31ff.png)

This is because the invalid message is in the same element as the input and the selects.
It needs to be outside or the input and two selects wrapped in an extra element.

**Comment by emyarod** [comment] 2019-03-22 20:04
if I'm not mistaken, this seems to be what #2099 addressed. it looks like the Vue component markup deviates from the vanilla markup, is that correct?

taken from https://the-carbon-components.netlify.com/?nav=time-picker

![image](https://user-images.githubusercontent.com/8265238/54849532-8f163e00-4cb2-11e9-9a95-2806da38fd2f.png)

**Comment by lee-chase** [comment] 2019-03-22 20:23
Is that the carbon 10 style?

V9 when I run vanilla source up does not show invalid as an example. Pulled source today.

Trying not to deviate from core HTML in Vue, do not think this does. Could be as a consequence of having 9 and 10 feature switched in one Vue component.

**Comment by emyarod** [comment] 2019-03-22 21:36
oh yes this is v10, I assumed we were discussing v10 because of the info in the original ticket description. I don't think the issue is fully resolved in v9 yet, but it should be for v10

**Comment by lee-chase** [comment] 2019-03-25 11:22
The solution moves the invalid message out of the core part of the component. It does not do the same for the label which exhibits the same issue. 

One alternative would be to put the HTML back where it was and use CSS for both the label and the invalid message. 

```css
.bx--form-requirement {
    overflow: visible;
    width: 0;
    white-space: nowrap;
}
```
However, this does have an issue for very long labels or invalid messages.

**Comment by emyarod** [comment] 2019-03-25 23:34
it looks like your component markup differs from the experimental vanilla component still

https://github.com/carbon-design-system/carbon-components-vue/blob/experimental/src/components/cv-time-picker/cv-time-picker.vue#L21-L23

https://github.com/IBM/carbon-components/blob/master/src/components/time-picker/time-picker.hbs#L94-L97

Am I reviewing the correct source file and branch?

**Comment by lee-chase** [comment] 2019-03-25 23:42
Yes, I'm in the process of fixing Vue component for v10. 
The label still needs moving out one level for the same reason as the invalid message.

Will investigate further with regards to V9.

**Comment by emyarod** [comment] 2019-03-26 00:49
ok got it, and actually we might not need to move the labels to get the same behavior (for v10). I will have a PR up for the labels after a bit of testing

**Comment by emyarod** [comment] 2019-04-02 14:59
@lee-chase is #2256 more in line with what you were looking for, since we are discussing the label length and not the invalid text length?

**Closed as completed** 2019-04-03 16:27 UTC
