### ISSUE TITLE
Lengthy code getting displayed only partially even with "Show more" on IBM Developer

### ISSUE THREAD

**Issue by narshars** [carbon-design-system/carbon#5684] opened 2020-03-24 05:20 UTC
We received a mail saying two of the code-listings in a tutorial  on IBM Developer are incomplete, when trying to view in-line using the "show more" option.

i.e. testke.c and libwrapper.c from https://developer.ibm.com/tutorials/control-ibm-aix-kernel-extensions/

The "copy" icon copies the whole code. But, the "show more" option only displays the first 94 lines in both cases.

**Comment by emyarod** [comment] 2020-03-24 14:19
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by tw15egan** [comment] 2020-03-24 18:59
The issue is caused because of the max-height set on the snippet container, used for transitions. This can be overridden to a larger value as a temporary fix.

**Comment by tw15egan** [comment] 2020-03-24 19:15
Seems like this issue was resolved in https://github.com/carbon-design-system/carbon/pull/4915 so I'd recommend upgrading to the latest version, or overriding the set `max-height` to `max-height: 100%`

**Closed as completed by tw15egan** 2020-03-24 19:15 UTC
Labels: status: needs more info, type: bug 🐛
