### ISSUE TITLE
[Bug]: sass-loader deprecation warnings

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon#17458] opened 2024-09-17 13:59 UTC
### Package

@carbon/styles

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.64.0

### React version

angular 

### Description

I'm using 
"webpack": "^5.94.0
"sass": "^1.78.0",
"sass-loader": "^16.0.1",
"typescript": "^5.5.4",
"postcss": "^8.4.47",
"postcss-loader": "^8.1.1",

### Reproduction/example

this is a build issue

### Steps to reproduce

```cmd
WARNING in ./src/client/styles.scss (./src/client/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 16, column 2 of file:///workspace/cloned-git-repository/node_modules/@carbon/styles/scss/utilities/_button-reset.scss:16:2:
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

16 |   display: inline-block;


node_modules/@carbon/styles/scss/utilities/_button-reset.scss 17:3          reset()
node_modules/@carbon/styles/scss/components/accordion/_accordion.scss 84:5  accordion()
node_modules/@carbon/styles/scss/components/accordion/_index.scss 11:1      @use
node_modules/@carbon/styles/scss/components/_index.scss 8:1                 @use
node_modules/@carbon/styles/index.scss 22:1                                 @use
src/client/styles.scss 27:1                                                 root stylesheet
 @ ./src/client/styles.scss
 @ ./src/client/app.ts 14:0-23

WARNING in ./src/client/styles.scss (./src/client/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 17, column 2 of file:///workspace/cloned-git-repository/node_modules/@carbon/styles/scss/utilities/_button-reset.scss:17:2:
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

17 |   padding: 0;


node_modules/@carbon/styles/scss/utilities/_button-reset.scss 18:3          reset()
node_modules/@carbon/styles/scss/components/accordion/_accordion.scss 84:5  accordion()
node_modules/@carbon/styles/scss/components/accordion/_index.scss 11:1      @use
node_modules/@carbon/styles/scss/components/_index.scss 8:1                 @use
node_modules/@carbon/styles/index.scss 22:1                                 @use
src/client/styles.scss 27:1                                                 root stylesheet
 @ ./src/client/styles.scss
 @ ./src/client/app.ts 14:0-23

WARNING in ./src/client/styles.scss (./src/client/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 18, column 2 of file:///workspace/cloned-git-repository/node_modules/@carbon/styles/scss/utilities/_button-reset.scss:18:2:
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

18 |   border: 0;


node_modules/@carbon/styles/scss/utilities/_button-reset.scss 19:3          reset()
node_modules/@carbon/styles/scss/components/accordion/_accordion.scss 84:5  accordion()
node_modules/@carbon/styles/scss/components/accordion/_index.scss 11:1      @use
node_modules/@carbon/styles/scss/components/_index.scss 8:1                 @use
node_modules/@carbon/styles/index.scss 22:1                                 @use
src/client/styles.scss 27:1                                                 root stylesheet
 @ ./src/client/styles.scss
 @ ./src/client/app.ts 14:0-23

WARNING in ./src/client/styles.scss (./src/client/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 53, column 4 of file:///workspace/cloned-git-repository/node_modules/@carbon/styles/scss/components/accordion/_accordion.scss:53:4:
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

53 |     inline-size: 100%;


node_modules/@carbon/styles/scss/components/accordion/_accordion.scss 54:5  accordion()
node_modules/@carbon/styles/scss/components/accordion/_index.scss 11:1      @use
node_modules/@carbon/styles/scss/components/_index.scss 8:1                 @use
node_modules/@carbon/styles/index.scss 22:1                                 @use
src/client/styles.scss 27:1                                                 root stylesheet
 @ ./src/client/styles.scss
 @ ./src/client/app.ts 14:0-23

WARNING in ./src/client/styles.scss (./src/client/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 54, column 4 of file:///workspace/cloned-git-repository/node_modules/@carbon/styles/scss/components/accordion/_accordion.scss:54:4:
Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

54 |     list-style: none;


node_modules/@carbon/styles/scss/components/accordion/_accordion.scss 55:5  accordion()
node_modules/@carbon/styles/scss/components/accordion/_index.scss 11:1      @use
node_modules/@carbon/styles/scss/components/_index.scss 8:1                 @use
node_modules/@carbon/styles/index.scss 22:1                                 @use
src/client/styles.scss 27:1                                                 root stylesheet
 @ ./src/client/styles.scss
 @ ./src/client/app.ts 14:0-23

WARNING in ./src/client/styles.scss (./src/client/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/client/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
1139 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.
 @ ./src/client/styles.scss
 @ ./src/client/app.ts 14:0-23

webpack 5.94.0 compiled with 6 warnings in 77962 ms
```

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2024-09-18 14:11
Duplicate of #16962

**Closed as not planned by tay1orjones** 2024-09-18 14:11 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:
