### ISSUE TITLE
Tooltip button accessibility 

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon#7154] opened 2020-10-28 14:23 UTC
I cannot add aria-labelledby or anything from my code to solve these accessbility issues
```
 <div className='foldingTogglePanel__header'>
              <p className='foldingTogglePanel__header-text'>{header}</p>
              {info && (
                <Tooltip tooltipBodyId='tooltip-body'>
                <p id='tooltip-body'>
                  {info}
                </p>
              </Tooltip>
              )}
            </div>
```

![image](https://user-images.githubusercontent.com/5415443/97448685-96470880-1939-11eb-8c9c-c9543ace0eb8.png)
![image](https://user-images.githubusercontent.com/5415443/97448830-bb3b7b80-1939-11eb-9fbf-a4b0b0538f46.png)
![image](https://user-images.githubusercontent.com/5415443/97448888-cb535b00-1939-11eb-945a-f522902fc17b.png)

**Comment by emyarod** [comment] 2020-10-28 14:29
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging? Or are these violations also present in the storybook examples?

**Comment by alon24** [comment] 2020-10-28 15:26
It does not happen in codesandbox, it does not happen in storybook

**Comment by emyarod** [comment] 2020-10-28 17:39
I see, is there a reliable way to reproduce the issue?

**Comment by alon24** [comment] 2020-10-29 12:49
I do not understand why this does not work, and on my page a different placed tooltip works,But I think we should have the ability to set the aria-label, aria-labelledby can you add that?

**Comment by emyarod** [comment] 2020-10-29 22:13
if I'm not mistaken, it looks like these values are based on [`tooltipId`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tooltip/Tooltip.js#L234-L241) and [`triggerId`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tooltip/Tooltip.js#L449-L460) if provided, otherwise they are auto generated. will need to double check if this is the case though

**Comment by alon24** [comment] 2020-11-10 07:18
any update?

**Comment by emyarod** [comment] 2020-11-10 15:31
it would be great if you could provide a way to replicate the issue. it doesn't appear in storybook or codesandbox because the required aria attributes are autogenerated if tooltipId and triggerId are not provided as I mentioned. havea you tried setting or unsetting those values?

**Comment by joshblack** [comment] 2020-11-12 19:28
Going to go ahead and close this out. If there is a way to provide steps to reproduce on Codesandbox we can totally re-open this issue!

**Closed as completed by joshblack** 2020-11-12 19:28 UTC
Labels: status: needs more info, status: waiting for author's response 💬, type: a11y ♿, component: tooltip
