### ISSUE TITLE
python error on yarn install

### ISSUE THREAD

**Issue by reinisg** [carbon-design-system/carbon#4767] opened 2019-11-25 07:10 UTC
Hello!
I downloaded this repo (https://github.com/carbon-design-system/carbon), opened powershell as admin and run `yarn install` and got python error when installing node-sass. Here is a screenshot of error: https://serving.photos.photobox.com/596663488a6618d21eaf201cf9c3de3b88884de326757e7c087803444bd554ed8c15f936.jpg

System:
- Windows 10
- Node 10.17.0
- Python 3.7.5
- Yarn 1.19.1

Is there solution for this issue?
Regards Reinis

**Comment by asudoh** [comment] 2019-11-26 00:02
Hi 👋 thank you for reporting - Since this repository has become monorepo, I see the build process with broken in Windows. The team seem to need help on that.

**Comment by sichangi** [comment] 2019-11-27 10:35
Hello @reinisg, I happened to land into this and solved it by installing windows build tools like so
```
 npm --add-python-to-path='true' --debug install --global windows-build-tools
```

I initially had ``python 3.8.0`` but it seems ``node-gyp`` needs python version 2, so am now on ``python 2.7.15`` after running the above command.

**Comment by reinisg** [comment] 2019-11-27 11:59
@sichangi Thanks, this worked well. Now `yarn install ` worked perfectly. But now there is next issue, when I write `yarn build`, it goes till @carbon/colors, where it cannot find module '../lib'

![alt text](https://fv2-1.failiem.lv/thumb_show.php?i=7fu6tfae&view&download_checksum=74977d662df73edc44eaec9022e8717378608c10&download_timestamp=1574855815 "Carbon setup")

**Comment by sichangi** [comment] 2019-11-27 12:42
No problem,
I actually found the same issue as well, and it seems to have been identified a while back #2434, I have managed to fix the build issue and am looking to propose a fix.

I can fork the repo and share it here with my fixes on it

**Comment by reinisg** [comment] 2019-11-27 12:58
Yes, it would great, if You could share the fix.
I'm very grateful!

**Comment by reinisg** [comment] 2019-12-02 06:17
@asudoh Does this bug will be fixed on 10.8.0 realease?

**Comment by asudoh** [comment] 2019-12-02 09:13
I haven't seen a PR for this, so I think it's not likely. Meaning, help wanted as labeled!

**Comment by reinisg** [comment] 2019-12-02 13:57
Okay, thanks for answer.
I did some research and tried to run installation and build process to 3 different windows PC, all had same issue with that `../lib`.
But when i tried to setup on Mac, all worked fine. For now, I'm generating code in Mac and then send compiled js to Windows PC, where is my working environment. 

I think,this is specific issue in Windows 10 installation packages.

**Comment by joshblack** [comment] 2019-12-03 23:04
Build path issues should be resolved over in: https://github.com/carbon-design-system/carbon/pull/4811 by @sichangi's awesome work! 😄 Specific issue is #2434 as mentioned above.

Going to close this for now, sorry about the issues on Windows machine! We so far have only confirmed support for Windows subsystem for Linux so sadly don't have much support yet for powershell users 😞 

Feel free to comment if this issue was meant for something else and closing was a mistake!

**Closed as completed by joshblack** 2019-12-03 23:04 UTC
Labels: type: bug 🐛, status: help wanted 👐

**Comment by reinisg** [comment] 2020-07-03 06:36
Hello!
Firstly, Sorry for return this topic.
Secondly, Great thanks. Command `yarn install` worked perfectly! 🥳 
So the new case, I'm not sure if this is related with this issue. So the new problem is - after installation, I wrote `yarn build`, process was quite long, but worked, till reached command `carbon-components: $ gulp clean`
Then started show up some errors, which caused error with exit command. Main issue is that there is no folder as it is written in files,  [here is screenshot](https://i.ibb.co/fSymV4R/carbon2020.png) 

Hope for some answer. 😃 
@sichangi @joshblack
