### ISSUE TITLE
[a11y]: The tabbable element's role 'none' is not a widget role

### ISSUE THREAD

**Issue by preranagiri** [carbon-design-system/carbon#13039] opened 2023-01-27 10:15 UTC
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

7.57.4

### React version

17.0.2

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Description

We use FileUploaderButton in our application and on running the IBM Equal Access Accessibility Checker we can see the following accessibility issue

- A tabbable element must have a valid widget role
4.1.2 Name, Role, Value
https://www.ibm.com/able/requirements/requirements/#4_1_2

There is AVT1 issue raised against this.

element location - 

```
<label
    for="fileUploadButton"
    class="bx--btn file_upload_btn bx--btn--tertiary bx--btn--md"
    tabindex="0">
```

<img width="664" alt="image" src="https://user-images.githubusercontent.com/13781018/215061670-a494136e-033b-4ed0-8c1f-780c8fc15a1d.png">

### Reproduction/example

N/A

### Steps to reproduce

na

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2023-01-27 13:51
Thanks for reporting! This looks like a duplicate of https://github.com/carbon-design-system/carbon/issues/12725. Please follow that issue for further updates.

**Closed as completed by tw15egan** 2023-01-27 13:51 UTC
Labels: status: waiting for author's response 💬, type: a11y ♿, status: needs triage :female_detective:
