### ISSUE TITLE
The overflowMenu doesn't pop up if using states and renderIcon

### ISSUE THREAD

**Issue by jillyj** [carbon-design-system/carbon#8936] opened 2021-06-17 10:00 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When using overflowMenu with state change,  the popup menu will be closed automatically when changing state (perhaps because of re-rendering?) so I could not see the popup menu. We also found that `onClose()`  will be called twice when the popup menu closes. The other finding is if we don’t use `renderIcon` , the behavior looks normal. 

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The overflowMenu with renderIcon can display the menu items when changing states.

> What browser are you working in?

Chrome
> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. From the sample code below in CodeSanbox, click the menu, and no menu item displayed. 

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/festive-cohen-shp8y

## Additional information

- Screenshots or code
- Notes

**Comment by andreancardona** [comment] 2021-06-21 13:43
Hey @jillyj!

Not sure if this is a bug - but one way this could be fixed can be seen here: https://codesandbox.io/s/boring-sky-6xc0g

Let me know if this make sense or doesn't solve your issue for any reason (and feel free to reopen the ticket) :)

**Comment by jillyj** [comment] 2021-06-22 02:25
Hi @andreancardona , I checked the code you provided, but the code doesn't change state.
In `onClose()`, it set the state to the original state.

 ``` onClose={() => {
        setOpen(open);

        console.log("onClose", open);
      }}
```
 What I want is to know when the menu opened, and when the menu closed. So I would set the different states in `onClose()` and `onOpen()`.  And you would see the problem I reported, when the state changes, the menu would not open.

**Comment by jillyj** [comment] 2021-06-22 02:27
@andreancardona would you please reopen the issue? I could not find where to reopen it. Thanks.

**Comment by tay1orjones** [comment] 2023-02-06 16:25
@jillyj Hi! In trying to look at this again it seems the code reproduction is out of date. Could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite)? 

I recreated a portion of @andreancardona's example [here](https://stackblitz.com/edit/github-kxwfok?file=src%2FApp.jsx) but I can't reproduce.

**Comment by jillyj** [comment] 2023-02-21 07:49
@tay1orjones Hi, I checked your example and I think it's fixed now. :) Thanks!

**Comment by tw15egan** [comment] 2023-02-22 19:08
Going to close this as it seems like it has been resolved, let me know if that's not the case and we can reopen it 😄

**Closed as completed by tw15egan** 2023-02-22 19:08 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:, status: needs reproduction
