### ISSUE TITLE
[Bug]: Typescript support broken in 1.22+ working in 1.21

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#13188] opened 2023-02-20 17:05 UTC
### Package

@carbon/react

### Package version

1.22

### React version

17.0.2

### Description

Upgrading from 1.21 to 1.22 or later causes Typescript build to start failing.

![image](https://user-images.githubusercontent.com/15086604/220164790-23f601e9-82ab-4e58-bb2b-888f10de6df4.png)

![image](https://user-images.githubusercontent.com/15086604/220165010-04e8f6fc-5919-48f1-b797-06a7928501d5.png)

### Reproduction/example

https://github.ibm.com/CDAI-UX-Engineering/carbon-code-scan

### Steps to reproduce

1. Clone project (let me know if you do not have access.).
2. Bump version of @carbon/react.
3. Run build script.

Note the 115 errors

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Application/PAL

Carbon compliance tool

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-03-21 13:01
Duplicate of https://github.com/carbon-design-system/carbon/issues/13091

**Closed as completed by tay1orjones** 2023-03-21 13:01 UTC
Labels: type: bug 🐛, severity: 1, area: typescript
