### ISSUE TITLE
accessibility violation in Overflowmenu item

### ISSUE THREAD

**Issue by lonestor** [carbon-design-system/carbon#6731] opened 2020-08-26 17:06 UTC
Overflowmenu item has accessibility violations

Carbon component react version:
  - v7.17.0
Test Browser 
 - chrome
Tool: IBM Equal Access Accessibility Checker
 - Violation Type 2.4.1 Bypass Blocks
"Content is not within a landmark element"

**Comment by tw15egan** [comment] 2020-08-27 21:39
Do you have a link to a reproducible example? I'm not seeing any violations when testing on our Storybook

![Screen Shot 2020-08-27 at 2 38 43 PM](https://user-images.githubusercontent.com/11928039/91497588-1c2fd000-e873-11ea-8806-e8aea5009ac7.png)

**Comment by lonestor** [comment] 2020-08-31 16:30
![Screenshot 2020-08-31 at 17 29 44](https://user-images.githubusercontent.com/68054577/91743409-a8156500-ebaf-11ea-9678-f547eab5943a.png)

**Comment by tw15egan** [comment] 2020-08-31 16:46
I'm still unable to see any a11y errors on this component.

@lonestor can you provide the ruleset you are using to see these errors?

Can you also hit the `Open in new tab` button in the top right so you can test the component in isolation? The main storybook window throws a lot of false-positive a11y errors. Content is not withing a landmark element is usually resolved when the component is placed inside an application that is already using appropriate aria landmark rules.

**Comment by dakahn** [comment] 2020-09-01 18:43
I'm gonna close this up since I can't reproduce using our test environment.

**Closed as completed by dakahn** 2020-09-01 18:43 UTC
Labels: type: a11y ♿, component: overflow-menu

**Comment by lonestor** [comment] 2020-09-02 21:50
@dakahn I have resolved the issue 
The Overflowmenu needs to be wrapped on div using  data-floating-menu-container attribue
There is styling issue which i was able to fix refering to 
https://github.com/carbon-design-system/carbon/issues/2907

The component as is will fail accessibility without being wrapped
