### ISSUE TITLE
Tooltip components focusTrap prop works as expected from the 2nd time click, but Not first.

### ISSUE THREAD

**Issue by purandarrao** [carbon-design-system/carbon#7067] opened 2020-10-17 04:47 UTC
- While clicking on ghost button displayed within tooltip that opens a side panel, it still keeps the tooltip displayed over the side panel that is opened during the first time.

- From 2nd time onwards when clicking on the open sidepanel button within tooltip info, the side panel opens and the tooltip is gone from the view - which is the right behavior.  Only during the first time click it doesn't work this way.

**Comment by joshblack** [comment] 2020-10-22 21:49
Hey there @purandarrao! 👋  Could you put together a [Codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) real quick to help us reproduce the problem that you're running into?

**Comment by purandarrao** [comment] 2020-10-23 22:46
Hi @joshblack, SidePanel is cloud pals component which is not available outside to put in Codesandbox, so I have replaced it with console.log statement.  If there is any questions please let me know.
Below is the gif of the actual issue. 
![tooltipIssue](https://user-images.githubusercontent.com/7863121/97059928-85704e80-1557-11eb-8c38-0ac9732d6879.gif)

**Comment by dakahn** [comment] 2020-10-26 22:27
Hard for us to assist without somewhere we can observe and recreate the problem. Too many variables. That said, if this issue is specific to Tooltip in a Cloud PAL component they can probably assist you with any unintended behavior. 👍 

Closing, but I can reopen if after chatting with the Cloud PAL team the source of the problem is Carbon-React. Thanks.

**Closed as completed by dakahn** 2020-10-26 22:27 UTC
Labels: status: needs more info, package: react, component: tooltip, status: needs triage :female_detective:, status: waiting for maintainer response 💬

**Comment by FeFranklin** [comment] 2020-11-03 12:36
Hi @purandarrao, Sorry for the delay to comment this issue. I was discussing it with other colleagues. As it was commented above, it is a bit difficult to reproduce and fully understand the bug there. What seems to happen is a little problem with the z-index (you probably know that already), I would suggest making some small changes in that so it could work accordingly. However, as I was talking to my colleagues, we thought that using a tooltip to trigger a SidePanel maybe isn't the best solution and may violate a11y rules. If you have any design question, you could reach out to the designs in the PAL slack channel.
