### ISSUE TITLE
[Bug]: Accordion not working as expected when open is true by default

### ISSUE THREAD

**Issue by Tomahaawk** [carbon-design-system/carbon#15342] opened 2023-12-07 10:52 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

1.44

### React version

18.0

### Description

I started having a problem with `Accordion` component where I have some `AccordionItems` with the `open` prop set as `true` by default, the content is overflowing. There is no height set until I close and open the item again.

On versions 1.41 and 1.42 I'm not able to open/close the `AccordionItem`, the exapnd and collapse button does nothing.

### Reproduction/example

https://stackblitz.com/edit/github-zc3uap?file=src%2FApp.jsx

### Steps to reproduce

Set the first AccordionItem `open` prop as true by default.

Content will overlap because the AccordionItem has no height set.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM RPA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2023-12-07 14:02
Thanks for reporting! It looks like this is a duplicate of https://github.com/carbon-design-system/carbon/issues/15340. I'm going to close this one in favor of that one, so please track the progress over there. Thanks!

**Closed as completed by tw15egan** 2023-12-07 14:02 UTC
Labels: type: bug 🐛
