### ISSUE TITLE
[Feature Request]: Automatically close SideNavMenu when SideNav collapses

### ISSUE THREAD

**Issue by navargas** [carbon-design-system/carbon#16061] opened 2024-03-26 05:52 UTC
### The problem

`SideNav` shows an empty space when a menu item without an icon is active, and the side nav is collapsed in rail mode.

<img width="304" alt="Screenshot 2" src="https://github.com/carbon-design-system/carbon/assets/8397737/bfeb332f-315b-426f-af68-a593d441e9f7">

### The solution

When the rail `SideNav` closes, it would be nice to have an option to automatically close all open `SideNavMenu`

## Menu opened:

<img width="312" alt="Screenshot 3" src="https://github.com/carbon-design-system/carbon/assets/8397737/2f36a455-b83e-43f3-a766-a97b47fd57f4">

## After mouse exits:
<img width="318" alt="Screenshot 4" src="https://github.com/carbon-design-system/carbon/assets/8397737/0d76c395-4a75-4456-a7b8-d014e13c23b6">

### Examples

https://react.carbondesignsystem.com/?path=/story/components-ui-shell-sidenav--side-nav-rail-w-header

### Application/PAL

Instana

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2024-03-26 15:46
Duplicate of https://github.com/carbon-design-system/carbon/issues/15900

**Closed as not planned by tay1orjones** 2024-03-26 15:46 UTC
Labels: type: enhancement 💡, status: needs triage :female_detective:
