### ISSUE TITLE
OnChange Hook is not working as expected in Datepicker type Simple in React-carbon design system

### ISSUE THREAD

**Issue by GokulPrasath** [carbon-design-system/carbon#8328] opened 2021-04-08 04:58 UTC
Hi Team,
 OnChange Hook is not working for Datepicker type Simple  in react-carbon design system.
Due to this issue i was unable to get and set the values.

Thank you

**Comment by emyarod** [comment] 2021-04-08 14:59
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by tay1orjones** [comment] 2021-04-09 15:32
I think we had discussed this one in slack - [here's the repro that was posted](https://codesandbox.io/s/compassionate-shannon-lbeb4?file=/src/index.js).

On my initial investigation I was unable to trigger onChange in the storybook and was able to write a failing test. I haven't looked into the cause. This hasn't been touched in quite some time, https://github.com/carbon-design-system/carbon/pull/3050. It also appears that DatePickerInput's onChange doesn't fire either, https://github.com/carbon-design-system/carbon/issues/4943

**Comment by emyarod** [comment] 2021-04-09 15:54
unless I am misunderstanding, moving the `onChange` to the `DatePickerInput` seems to work as expected (the alert dialog appears on change) in the Code Sandbox

https://codesandbox.io/s/exciting-moon-2ocx0

**Comment by joshblack** [comment] 2021-04-19 14:25
Going to close this out as needs more info, feel free to provide steps to reproduce and we can revisit this!

**Closed as completed by joshblack** 2021-04-19 14:25 UTC
Labels: status: needs more info, type: bug 🐛

**Comment by davidkan6666** [comment] 2021-07-05 02:15
You can see the issue by changing simple type to single type in the example you created here:
https://codesandbox.io/s/exciting-moon-2ocx0

**Comment by stephenhamm** [comment] 2021-11-02 12:27
It looks like the onChange is setting state as undefined, and only on blur (clicking outside the datepicker) is the state set. Has there been a solution provided anywhere for this?

**Comment by tay1orjones** [comment] 2021-11-03 19:58
Unless I'm misunderstanding, what we discussed above was that for `<DatePicker type="simple">` the intended way to catch changes to the input is to use the `onChange` on `DatePickerInput`.

For `<DatePicker type="single">` or `<DatePicker type="range">` the way to catch change updates is via the `onChange` on `DatePicker`.

The `DatePicker` `onChange` passes through all the arguments [we receive from flatpickr](https://flatpickr.js.org/events/)

> 1. selectedDates - an array of Date objects selected by the user. When there are no dates selected, the array is empty.
> 2. dateStr - a string representation of the latest selected Date object by the user. The string is formatted as per the dateFormat option.
> 3. instance - the flatpickr object, containing various methods and properties.

The date formatting is working as well from what I can tell. [Here's a codesandbox](https://codesandbox.io/s/cold-paper-ef03w?file=/src/index.js) with both the `onChange` configured and the `dateFormat`.
