### ISSUE TITLE
ToastNotification timeout regression after updating to carbon-component-react  v7.32.0.

### ISSUE THREAD

**Issue by galilmori** [carbon-design-system/carbon#8392] opened 2021-04-14 08:36 UTC
## What package(s) are you using?

- [x] @console/pal v1.383.5
- [x] carbon-components v10.32.1
- [x] carbon-components-react v7.32.1

## Detailed description

- using carbon-component-react v7.31.0 we had no  problem with Toast Notification timeouts.
- updated to 7.32.1 with @console/pal v1.383.5 update
- after update the notification appears for a split second to disappear and sometimes does not appear at all

> What did you expect to happen?
 - notification to stay on screen for the indicated time in the timeout prop then to disappear
> What happened instead? 
 - no matter the timeout indicated the notification either doesnt appea or disappears in a split second.

> What browser are you working in?
 - Google Chrome

> What offering/product do you work on?
 - Ibm cloud Power-iaas. This issue is causing users to have bad error feedback causing an unpleasent user experience

## Steps to reproduce the issue
 - display toaster with timeout property
  
##  Reduced test case in CodeSandbox
the regression can be seen in this sendbox by swithching between different carbon-component-react v7.31.0 and v7.32.0 
- https://codesandbox.io/s/lucid-haibt-klh21?file=/index.js

**Comment by emyarod** [comment] 2021-04-14 14:37
this appears to be a duplicate of https://github.com/carbon-design-system/carbon/issues/8348 and should be resolved by https://github.com/carbon-design-system/carbon/pull/8362

**Closed as completed by emyarod** 2021-04-14 14:37 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬

**Comment by tay1orjones** [comment] 2021-04-14 14:44
The fix #8362 was included in [v7.33.0-rc.0](https://github.com/carbon-design-system/carbon/releases/tag/v10.33.0-rc.0)

**Comment by galilmori** [comment] 2021-04-15 12:03
@tay1orjones when will this fix be released?
