### ISSUE TITLE
Virtual Server Cancel Button missing

### ISSUE THREAD

**Issue by mwesencr** [carbon-design-system/carbon#5890] opened 2020-04-20 09:47 UTC
Environment

OS: Windows
Browser: Chrome
Version: 80

Account
PayGo

Describe the bug

If you are using a Display Resolution of 1366 x 768, your are not able to cancel a virtual server, due to a layout error.

Steps to Reproduce

Ensure that your are using a Display Resolution of max. 1366 x 768.

1. You need a running Virtual Server Instance
2. Please open the Resource menu
            https://cloud.ibm.com/resources
3. In the device list please select your running server e.g. this was the URL to my server
            https://cloud.ibm.com/gen1/infrastructure/virtual-server/97955272/details#main

4. In the device menue, select in the blue "Actions" drop-down menu the entry for "Cancel device"
5. Select "I acknowledge that data loss might occur as a result of canceling."
6. You will observe that there is no button to confirm the cancellation of your server. Please take a    closer look, there is only a small stripe of the red button visible.

Expected behavior
The layout error should be fixed for Display Resolution of 1366 x 768 and the Confirmation button should be visible.

Severity
medium

![image](https://user-images.githubusercontent.com/36452478/79738101-34577780-82f4-11ea-9a78-bbfe138e7656.png)

**Comment by joshblack** [comment] 2020-04-20 19:29
Hi there @mwesencr! 👋 Would you mind recreating this issue in codesandbox with steps to reproduce so we can investigate this issue? 👀

**Comment by mwesencr** [comment] 2020-04-21 10:11
@joshblack Hey Josh thanks for responding can you send me a link to the codesandbox as I can't seem to find it and i'll raise the issue 

Do you need more details than the steps listed above ?

**Comment by emyarod** [comment] 2020-04-21 15:03
here is a link to [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox)

**Comment by mwesencr** [comment] 2020-04-21 18:12
@joshblack @emyarod, I think there has been some confusion, I am problem manager working for the Digital sales Europe team i'm not a developer If you need to see this error I can setup a webex with the person who raised this to show the error or can you work with the info provided ?

**Comment by emyarod** [comment] 2020-04-21 18:23
@mwesencr we are looking for a reproducible example to determine the cause of the issue. can you or your application developer create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by mwesencr** [comment] 2020-04-22 09:36
@emyarod I can give you a demo of the issue but as already stated I don't have a developer nor can I create a test case in your sandbox, I am reporting the issue to you so you can fix it

**Comment by asudoh** [comment] 2020-04-22 11:10
@mwesencr Seems that you are reporting this issue for somebody else. If it's correct, could you work with your developer to gather the information we need? Similar thing applies in case you are simply reporting an issue of the app you use using and the app developer just told you that the issue is Carbon's; The first investigation has to be done by the developer of the application, eliminate all application-specific factors so they can create a clear bug report. Thanks alot!

**Comment by asudoh** [comment] 2020-04-22 11:18
Followed up in the internal issue, let's discuss further there.

**Comment by joshblack** [comment] 2020-05-04 14:33
Gonna go ahead and close this based on above 👀 Feel free to re-open if this is a mistake!

**Closed as completed by joshblack** 2020-05-04 14:33 UTC
Labels: status: needs more info, status: waiting for author's response 💬, component: modal
