### ISSUE TITLE
Storybooks not working on IE11

### ISSUE THREAD

**Issue by tomleah** [carbon-design-system/carbon#8995] opened 2021-06-22 21:57 UTC
## What package(s) are you using?

Wanting to use the react storybook but Angular and Vue also don't work.

## Detailed description

In Internet Explorer 11 I am unable to load the react storybook to access the docs. 

We are having trouble supporting the DataTable in IE11 so wanted to check the storybook/docs to see if we can reproduce the problem there. 

> What version of the Carbon Design System are you using?

The storybook is for `carbon-components-react` v7.37.1

## Steps to reproduce the issue
1. Visit the [React storybook](https://react.carbondesignsystem.com/?path=/story/getting-started-welcome--welcome) on IE11

## Additional information
Screenshot of browser console
![image](https://user-images.githubusercontent.com/5465397/123004741-f39e3700-d3ac-11eb-85f4-a7ce3263dcdc.png)

**Comment by emyarod** [comment] 2021-06-23 14:45
this may be resolved by auto polyfilling class syntax in the feature-flags package as suggested. do you know the last working version which was viewable in storybook? currently, viewing older storybook deploys shows content security errors so it's not clear when the breakage occurred

**Comment by joshblack** [comment] 2021-06-23 15:47
Seems like it may be something webpack-related, potentially with one of our CSS loaders. When debugging, I removed all stories and still got an error when styles were trying to be loaded 🤔

**Comment by szdominik** [comment] 2021-06-28 08:59
I've investigated a few things - nothing surprising, but it could be useful for your debugging process.

I checked the following versions and the Carbon ecosystem is still broken with the same error (syntax error because of `class` usage) on IE11.
```
    "carbon-components": "10.34.0",
    "carbon-components-react": "7.34.0",
    "@carbon/feature-flags": "0.3.0",
```

So I also checked these versions and the error has been changed:
```
    "carbon-components": "10.32.1",
    "carbon-components-react": "7.32.1",
    "@carbon/feature-flags": "0.2.0",
```

New error is `Invalid character` and the problem is the usage of template literals at
https://github.com/carbon-design-system/carbon/blob/v10.32.1/packages/feature-flags/src/index.js#L23
(template literals are also unsupported on IE11).

So I still think that the `feature-flags` package is not properly compiled/polyfilled.

I'd also like to emphasize that the issue relates not just to the Storybook, but to the whole Carbon.

**Comment by emyarod** [comment] 2021-07-14 19:05
https://github.com/carbon-design-system/carbon/pull/9204 resolves the issue in the `feature-flags` package but it looks like a storybook arrow function is causing a separate error (possibly as a result of upgrading storybook versions). not sure how we want to continue with resolving this given that IE11 support is being dropped cc @joshblack

**Comment by emyarod** [comment] 2021-07-20 15:43
FWIW https://storybook.js.org/docs/react/workflows/faq#why-are-my-mdx-stories-not-working-in-ie11

related https://github.com/storybookjs/storybook/issues/14578

**Comment by joshblack** [comment] 2021-07-28 15:14
+1 to the feature flags package stuff, that should have been transpiled and thankfully is fixed/merged into the codebase now 👍

**Closed as not planned** 2022-08-15 16:50 UTC
Labels: status: needs more info, type: bug 🐛, type: docs 📖, browser: ie11
