### ISSUE TITLE
[Audit] File uploader

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2043] opened 2019-03-11 15:42 UTC
**Component**
![File Uploader - White theme.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/af8d707e-f935-40f4-a4af-57a26919d940)

**Specs:**
![File uploader - Specs - White theme.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/410fa9c5-7252-49fd-88a6-1238e9f1bbec)

**Sketch file:**https://ibm.ent.box.com/file/342710803221

**Comment by laurenmrice** [comment] 2019-03-11 15:57
**Changes:**

- [ ] The 'Add file' button needs to be 48px instead of 32px. 
- [ ] The background for the uploaded file isn't showing up currently. ![Screen Shot 2019-03-11 at 10.43.50 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/47e12eab-325d-4360-a014-cb9fd3134a0d)

**Comment by dakahn** [comment] 2019-03-11 18:43
Checked on both the latest FF and and Chrome in both Windows 10 and OS X and I can't reproduce the missing background for the uploaded file. 😕  @laurenmrice

**Comment by laurenmrice** [comment] 2019-03-11 19:56
@IBM/carbon-developers Anyone know how to get around this problem? We really need to have the background field-01 for uploaded files.

**Comment by dakahn** [comment] 2019-03-11 21:52
No, sorry -- I meant that I see a background color for the uploaded files. I can't reproduce the bug.
![2019-03-11 16_52_17-Window](https://user-images.githubusercontent.com/40970507/54160627-0d0a5780-441e-11e9-925a-274484397936.png)

**Comment by laurenmrice** [comment] 2019-03-11 21:57
Oh okay, weird. Because its happening in Firefox, Chrome and Safari for me

**Comment by dakahn** [comment] 2019-03-11 22:04
Addressed the height [in this PR](https://github.com/IBM/carbon-components/pull/2048)

As for the background color -- I cross checked in two different environment PC and macOS in both Firefox and Chrome. We'll wait to merge until someone else can check too. 🤷‍♂️

**Closed as completed** 2019-03-13 22:18 UTC
Labels: version: 10, role: dev 🤖
