### ISSUE TITLE
[Bug]: MultiSelect selection results in an infinite loop

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#16469] opened 2024-05-14 14:39 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

11.57.0

### React version

18

### Description

When selecting the first option twice, the multiselect is rerendered in an infinite loop.

### Reproduction/example

https://stackblitz.com/edit/github-pxnmha?file=src%2FApp.jsx

### Steps to reproduce

Select the first option. Select it again. Select it again. Eventually you'll hit 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ychavoya** [comment] 2024-05-16 18:35
Hello, I just wanted to share some background on this issue since I have been working on it, in case it helps the person that works on it.

There was a bug where selecting an item triggered a console warning, which #15818 solved (the warning no longer appeared). 

However, this caused the UI not to update when updating the items via the `selectedItems` prop. The UI updated fine when the user took action but programmatic tasks (setting the `selectedItems` prop from outside of the component) did not. This was fixed in  #16139 by triggering an update whenever the prop is updated from outside.

However, now programmatic tasks work fine, but when the user takes action it creates an infinite update loop. which is what the issue is referring to.

My guess on why the infinite update cycle happens is because we are storing the selected items in two places when the Multiselect is controlled (outside the component and in the [`useState` hook inside](https://github.com/carbon-design-system/carbon/pull/15818/files#diff-0a4e099b801b8c2899ce73027fc091d25e61b0c89b1a1d74df6d086f4a07068fR39)). Something then could make these two states different triggering an update loop via the added [`useEffect`](https://github.com/carbon-design-system/carbon/pull/16139/files#diff-0a4e099b801b8c2899ce73027fc091d25e61b0c89b1a1d74df6d086f4a07068fR43). I would try to figure out if there is a way to remove the `useState` that was added to fix the console warning (since both kinds of updates were working before that change) without triggering the console warning that was fixed in the first place.

Hope this helps

**Comment by filipmadejIBM** [comment] 2024-06-05 13:50
@tay1orjones We have exact same problem. Any update on ETA ?

**Comment by anneyxa** [comment] 2024-06-05 14:31
I also have this problem. Would appreciate any information on expected fix as well.

**Comment by tulivlk** [comment] 2024-06-10 13:42
+1 on the fix, MultiSelect is unusable, we had to downgrade to 11.56.0.

**Comment by Gururajj77** [comment] 2024-06-18 11:25
completed in #16793

**Closed as completed by Gururajj77** 2024-06-18 11:25 UTC
Labels: type: bug 🐛, severity: 2, role: dev 🤖, component: multiselect
