### ISSUE TITLE
ComboBox in Modal causes scrollbar

### ISSUE THREAD

**Issue by supermonkeybrainz** [carbon-design-system/carbon#8568] opened 2021-05-03 19:26 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

`ComboBox` components in `Modal` are causing the `Modal` to scroll due to the length of items in the list.  They should overflow the bounds of the `Modal` like the `Select` component does.  See a reproduction of the issue [here](https://codesandbox.io/s/carbon-components-react-forked-b9sr4?file=/src/index.js)

> What browser are you working in?

Chrome/Edge

> What version of the Carbon Design System are you using?

carbon-components 10.34.0
carbon-components-react 7.34.0

## Steps to reproduce the issue

Put a `ComboBox` in a `Modal` with a handful of options.  See [sandbox](https://codesandbox.io/s/carbon-components-react-forked-b9sr4?file=/src/index.js).

## Additional information

![image](https://user-images.githubusercontent.com/34159275/116922865-ea51e300-ac23-11eb-8300-0a0d0d1e8fcf.png)
![image](https://user-images.githubusercontent.com/34159275/116922884-f047c400-ac23-11eb-90f3-8b14049cc82d.png)

**Comment by tw15egan** [comment] 2021-05-03 19:42
Closing as a duplicate of https://github.com/carbon-design-system/carbon/issues/7565

**Closed as completed by tw15egan** 2021-05-03 19:42 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬
