### ISSUE TITLE
Delay when clicking the select-all checkbox on the Datatable at 500 records. 

### ISSUE THREAD

**Issue by Cahalanb** [carbon-design-system/carbon#8716] opened 2021-05-18 20:01 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [ x ] `carbon-components-react`

## Detailed description
We have setup a Datatable to display records where Items per page allows for 10, 20 ... 500. Setting this to 500 items per page, attempt to click the select-all checkbox on the column header toolbar. There is a clear delay of about two seconds until the selection is reflected in the table UI. This is for both checking & un-checking.

There is also a delay if the user clicks any of the checkboxes at row level.

> Is this issue related to a specific component?
Datatable

> What did you expect to happen? What happened instead? What would you like to
> see changed?
A more timely update of the Datatable to reflect the checkbox selection. Right now, it may appear to the user that no selection was made.

> What browser are you working in?
Chrome Version 90.0.4430.212 (Official Build) (x86_64)

> What version of the Carbon Design System are you using?
"@carbon/ibm-security": "=1.38.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Pak for Security - Cases

## Steps to reproduce the issue

1. Setup a carbon datatable
2. Populate the table with 500 rows ( about 10 columns )
3. Click the select-all checkbox on the column bar at the top of the table
4. Click any of the checkboxes of a particular row.

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/codesandbox-forked-bf2lw?file=/src/index.js

**Comment by tay1orjones** [comment] 2022-10-31 16:16
Duplicate of https://github.com/carbon-design-system/carbon/issues/4338

**Closed as not planned by tay1orjones** 2022-10-31 16:16 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, component: data-table, status: needs triage :female_detective:
