### ISSUE TITLE
Light Dropdown changes size when expanded

### ISSUE THREAD

**Issue by manolyaa** [carbon-design-system/carbon#6502] opened 2020-07-20 17:17 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When you have the “light” prop, the height of the dropdown increases 1px when it’s expanded, but when you remove the light prop, there’s no problem.

## Additional information

[Dropdown bug.zip](https://github.com/carbon-design-system/carbon/files/4949114/Dropdown.bug.zip)

**Comment by tw15egan** [comment] 2020-07-20 17:34
Seems like this was fixed with the latest Dropdown / Downshift updates. Can you try updating to latest and see if your issue is resolved? 

![dropdown-bug](https://user-images.githubusercontent.com/11928039/87967894-68b60d80-ca74-11ea-8399-96e0a2da79ec.gif)

**Comment by tw15egan** [comment] 2020-07-20 18:15
Verified on slack the issue is resolved on newer releases

**Closed as completed by tw15egan** 2020-07-20 18:15 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬
