### ISSUE TITLE
[a11y]:  Tooltip dismissal using 'Escape' key closes underlying sidepanel

### ISSUE THREAD

**Issue by awackygamer** [carbon-design-system/carbon#10892] opened 2022-03-01 21:54 UTC
### Package
carbon-components-react

### Browser
Chrome

### Operating System
MacOS

### Package version
7.52.0

### Automated testing tool and ruleset
IBM Equal Accessibility Checker

### Assistive technology
No

### Description

Our AVT tester, while testing keyboard accessibility, found that pressing the 'Escape' key to dismiss a Tooltip launched from a sidepanel, which is essentially a dialog ,was also closed.  The tooltip has a learn more button so we need it to have focustrap set to true which is the default.  But the only way to dismiss the tooltip is using Escape.  I could find no way to catch and stop the propagation of the escape action.

Similar tooltips on other pages which do not have a bound Escape work just fine.

**Comment by joshblack** [comment] 2022-03-07 16:32
Hi @awackygamer! 👋  Thanks for taking the time to make this issue 🙏 If I remember correctly, the Tooltip component attempts to handle this use-case by preventing event propagation when it detects that the enter key is pressed.

Could you provide additional steps to reproduce the issue that you're seeing using our codesandbox template? Here's a quick link to use it: [Link](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)

**Comment by awackygamer** [comment] 2022-03-08 21:38
Do you have an example where someone used cloud/pal components to provide the sandbox?

**Comment by jnm2377** [comment] 2022-03-09 18:55
Hi @awackygamer unfortunately, we only have a Carbon specific sandbox template. You can add any other dependencies or libraries you might need in that sandbox, however. Please share a link of the reproduced test case when you have one 🙂  thank you!

**Comment by awackygamer** [comment] 2022-03-11 18:48
cloud/pal is not externally avail in npm so I do not think that is possible.   I tried to create the same issue but instead of using the sidepanel component from pal I used your modal.  Can you tell me how modal prevents the Escape from the tooltip from closing the modal?  When doing this same thing on a sidepanel and hitting escape on the tooltip the sidepanel also closes.

Steps are.  Click button to open modal.  Click tooltip.  Press Escape.   

https://codesandbox.io/s/keen-https-zlscp2?file=/src/index.js

**Comment by jnm2377** [comment] 2022-03-15 19:42
@awackygamer ahh, I see what you're saying. That's the desired behavior, not the issue. Gotcha. Hmm, looking at our modal component, this is all it seems to be doing for keyboard events https://github.com/carbon-design-system/carbon/blob/b71bea0bdeeed0ce06ca2d56b0239dd55d82652c/packages/react/src/components/Modal/Modal.js#L258-L271

Here's what our tooltip does (for the trigger element and popup). We have `evt.stopPropagation` included so it's interesting that it's still happening to you. https://github.com/carbon-design-system/carbon/blob/b71bea0bdeeed0ce06ca2d56b0239dd55d82652c/packages/react/src/components/Tooltip/Tooltip.js#L570-L592

**Comment by awackygamer** [comment] 2022-03-16 14:18
Thanks this was helpful, I looked thru your code and version changes on tooltips but we have the latest changes for the event changes.  So I looked at the sidepanel in the PAL and they use onKeyUp(Escape) to dismiss the sidepanel so that event is not stopped.  I am not an expert at what is recommended for key events.  Is keydown or keyup better?  Who should make a change for this?

**Comment by tay1orjones** [comment] 2022-03-18 19:18
@awackygamer `keyDown` is typically preferred as it provides an immediate response to user input, leaning into a perception of the interface being more 'snappy', 'performant' etc.

Have you tried wrapping the tooltip in a div to capture the `keyup` event yourself? I'm not opposed to Tooltip being updated to capture `keyup`, but it feels like this might fall a bit outside of the scope of Tooltip's responsibility.

Another thought - what's the `target` of the event? Could it be used to discern in `SidePanel` if it should respond to the <kbd>escape</kbd> or not?

**Comment by joshblack** [comment] 2022-04-13 20:36
Going to close this out as this has not been active for several weeks. Feel free to comment and we can re-open the issue!

**Closed as completed by joshblack** 2022-04-13 20:36 UTC
Labels: status: needs more info, status: needs triage :female_detective:, status: waiting for maintainer response 💬

**Comment by lj7720** [comment] 2022-07-25 02:27
Hi, team. This problem still exists for the carbon component. As it is prerequest to close the AVT defect of [3463 ](https://github.ibm.com/CloudBBS/ts-planning/issues/3463)Transit Gateway, may I ask to reopen to give a solution for it? Thanks.
@joshblack
