### ISSUE TITLE
AccordionItem - using, and accessibility issue

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon#7354] opened 2020-11-30 16:07 UTC
According to https://pages.github.ibm.com/ibmcloud/pal/patterns/getting-started-tab/usage it is a known design to put a button in the accordion:

![image](https://user-images.githubusercontent.com/5415443/100633242-83f42c00-3336-11eb-9bdf-4d42bee78752.png)

However, when we try it we get a big error 
```Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.```

because the accordion header itself is rendered as a <button> and is considered an interactive element so having a button in it is like having a button nested within a button something which react doesn't like

```
 const getTitle = (name, description, buttonText, page, link) => {
    return (
      <React.Fragment>
        <div className={`${COMPONENT_NAME}__title-text`}>
          <div className={`${COMPONENT_NAME}__name`}>{name}</div>
          <div className={`${COMPONENT_NAME}__description`}>
            {description}
          </div>
          <Button
            className={`${COMPONENT_NAME}__title-button`}
            href={link}
            target='blank'
            kind='tertiary'
            onClick={() => routeTo(page)}
          >{buttonText}</Button>
        </div>
      </React.Fragment>
    );
  };

 <AccordionItem
          className={`${COMPONENT_NAME}__title`}
          title={
            getTitle(
              t('overview.steps.addSecretName'),
              <Trans i18nKey='overview.steps.addSecretDescription' components={[getLinkElement()]}/>,
              t('overview.steps.addSecretButton'),
              'addSecret',
              null
            )
          }>
          {
            getContent(
              <VideoPlayer src={getMediaUrl('GIF_1.mp4')} />,
              true,
              t('overview.steps.addSecretNotificationTitle'),
              <Trans i18nKey='overview.steps.addSecretNotificationSubtitle' components={[getSettingsLink()]}/>,
              <Trans i18nKey='overview.steps.addSecretDetails' components={[setBoldTreatment()]}/>
            )
          }
        </AccordionItem>

```

There is also an accessibility issue here,  because AccordionItem is a Button then all the text inside it is read at the same time when moving through it, also if I put a link, it is not read by Jaws (insert+F7) links, and cannot be used correctly (user does not know on which element he is on).

I think changing the AccordionItem to div would fixed all these issues (I checked and changed it locally in the html page to div and that fixed it). When it was button, Jaws did not recognize the Learn more link)

![image](https://user-images.githubusercontent.com/5415443/100633529-ddf4f180-3336-11eb-958d-091c23b07212.png)

**Comment by tw15egan** [comment] 2020-11-30 16:12
@carbon-design-system/design Are we allowing `Button`'s to be placed in the `Accordion` Title? 

@dakahn any a11y concerns with changing this from a `button` to a `div` with a role of button?

**Comment by joshblack** [comment] 2020-11-30 17:19
Unfortunately, if you nest buttons then it removes the semantics of the inner button 😞  This would apply to nesting the `<button>` element along with `role="button"` and a nested button.

For example:

```html
<div role="button" tabindex="0">
  Toggle
  <button>Submit</button>
</div>
```

Would read as: `Toggle Submit`. A screen reader like VoiceOver would be unable to navigate to the inner button (Submit) 😞 

Typically the remedy to this is to separate out the two actions instead of nesting one inside of the other.

**Comment by alon24** [comment] 2020-12-07 07:37
Any update on this? or was the solution here, NOT to use button, and you guys are not moving to div?

**Comment by emyarod** [comment] 2020-12-07 15:54
does `renderExpando` help with this use case? https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Accordion/AccordionItem.js#L26

**Comment by joshblack** [comment] 2020-12-07 18:55
@alon24 unfortunately I think the problem is that you can't nest buttons, and the trigger for the accordion (which takes up the full width) is a button so anything inside of it will need to be non-interactive.

**Comment by dakahn** [comment] 2020-12-16 00:56
Closing! Can reopen if we need to though.

**Closed as completed by dakahn** 2020-12-16 00:56 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬
