### ISSUE TITLE
[Bug]: Date picker of type range never call onChange when second input value change

### ISSUE THREAD

**Issue by wwwju** [carbon-design-system/carbon#12980] opened 2023-01-16 15:12 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.11.0

### React version

v17.0.2

### Description

This bug is for the possibility to type a date by hand and not using the calendar widget.
For a range date picker, the onChange props is never called after typing in the second input (and not choosing a date in the calendar) and close the calendar.
It works for the first input. And of course it works normally by using the calendar widget for both input.

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

https://stackblitz.com/edit/github-pzlus6-jt29yb?file=src/App.jsx

### Steps to reproduce

- Type a date in the first input, quit & focus again the first input, the date in the calendar change
- Type a date in the second input, quit & focus again the second input, the date don't change on the calendar
- try console.log the onChange prop, for the first input the function is called, for the second nothing happen.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment] 2023-02-09 17:21
@tay1orjones not closed by #13108 🥲, I think technically it would but there's a bug on top of this bug where the first date is getting deleted after doing step 1 and attempting step 2: 

https://user-images.githubusercontent.com/40550942/217889657-bf6dd286-b2a7-435c-bdab-489cf1066eb5.mov

**Comment by alisonjoseph** [comment] 2023-03-17 15:29
@tay1orjones @francinelucca I'm seeing this bug in the Flatpickr example here https://flatpickr.js.org/plugins/ is this something we can fix in Carbon, or is this an upstream bug? It seems that when you select the first date it expects you to select the second without clicking off of it. Perhaps not a bug, and just the way the component was intended to work?

**Comment by francinelucca** [comment] 2023-03-17 15:47
Yeah I believe it's an upstream bug. These issues seem related:
- https://github.com/flatpickr/flatpickr/issues/2804
- https://github.com/flatpickr/flatpickr/issues/2881

 I'd think it is a bug since the behavior seems very unexpected to me.
We could try and hack it if we wanted to, or wait for upstream to be fixed. Doesn't seem like there's much going on in the [flatpickr](https://github.com/flatpickr/flatpickr) repo tho' these days... Last published version is a year ago https://www.npmjs.com/package/flatpickr?activeTab=versions

**Closed as completed** 2023-04-06 22:59 UTC
Labels: type: bug 🐛, severity: 2, role: dev 🤖, component: date-picker
