### ISSUE TITLE
[Bug]: allowEmpty behaviour in NumberInput is not able to distinguish empty string with characters other than numbers

### ISSUE THREAD

**Issue by nikhil-isaac** [carbon-design-system/carbon#13624] opened 2023-04-18 18:28 UTC
### Package

carbon-components-react

### Browser

Chrome, Safari, Firefox

### Package version

v7.59.6

### React version

v17.0.2

### Description

When I set `allowEmpty` to true for `NumberInput`, then whenever I type any characters other than numbers(like a, b, c, etc), I get only `empty string`("") in `onChange` prop. I would like to distinguish between typing an actual empty string(valid value for our usecase) and typing any characters other than numbers(invalid value for our usecase).

### Reproduction/example

https://codesandbox.io/s/carbon-number-input-allow-empty-invalid-issue-97mho?file=/src/index.js

### Steps to reproduce

1. Type empty string, the component allows.
2. Type any characters other than numbers(like a, b, c, etc) the component allows them too.
3. Expectation: To allow empty string(""), but not allow characters other than numbers and empty string(like a, b, c, etc).

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Cloud & Cognitive Software

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment] 2023-04-18 21:42
@nikhil-issac would you be able to insert a screen recording reproducing the issue? I can't seem to do it from the reproduction steps.
TIA!

**Comment by francinelucca** [comment] 2023-07-05 15:06
thanks! @nikhil-isaac, I see the issue now. Could you drop that code you're using in the screenrecord into a sandbox? 🙏🏻, looks different than the one in the reproduction steps

**Comment by shankar343** [comment] 2023-08-28 13:03
Hi Team, any solutions we got for this issue?

**Comment by tay1orjones** [comment] 2023-08-28 16:42
@shankar343 @nikhil-isaac

> The empty string is being generated even when we type non-integer characters like 'a' or 'aa' or '$', which makes it impossible to do number validation when we set allowEmpty to true..

Browsers disagree on how to handle non-numeric input, see [this bugzilla thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528) for more info.

Additionally, `NumberInput` does not modify the `event` passed when `onChange` is called. It's coming straight from the browser.

https://github.com/carbon-design-system/carbon/blob/c678397eaeeea0845abec98522812c9026ba9e60/packages/react/src/components/NumberInput/NumberInput.tsx#L300-L302

This is why `onKeyUp` was added, https://github.com/carbon-design-system/carbon/pull/11230, so you can work around this and identify the individual keystrokes and implement your own additional validation. There should be nothing preventing this working with `allowEmpty`.

I hope this helps, and sorry for the lack of information earlier. I'm going to close this as a duplicate but happy to pursue other options if you have ideas for a different fix or solution to the problem.

**Comment by tay1orjones** [comment] 2023-08-28 16:43
Duplicate of https://github.com/carbon-design-system/carbon/issues/7039

**Closed as not planned by tay1orjones** 2023-08-28 16:43 UTC
Labels: type: bug 🐛, severity: 2, role: dev 🤖, component: number-input
