### ISSUE TITLE
Datatable action bar/ heading has white space on the right side for smaller resolutions

### ISSUE THREAD

**Issue by prince737** [carbon-design-system/carbon#4998] opened 2020-01-10 06:17 UTC
## Description
For smaller resolutions when the datatable becomes scrollable the table heading and action bar has does not match the width of the table. They have a rem of white space on the right.

## Environment
carbon-components@10.9.0
carbon-components-react@7.9.0
Through cloud pal@1.40.8

## Screenshot
The below screenshot is from react storybook itself

<img width="470" alt="Screenshot 2020-01-10 at 10 07 47 AM" src="https://user-images.githubusercontent.com/31027320/72130161-aee03500-339e-11ea-84ba-becf01e4c794.png">

**Comment by asudoh** [comment] 2020-01-10 08:33
HI 👋 thank you for reporting - Do you have a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox? In this way somebody may be able to jump in and help.

**Comment by prince737** [comment] 2020-01-10 10:01
Hi @asudoh  I was not able to re-create the issue in a sandbox. However, in the process of trying to re-create, I found out the reason of why such a gap is visible.
Consider this example: http://react.carbondesignsystem.com/iframe.html?id=datatable--with-batch-actions&viewMode=story

Here the datatable in enclosed in a div whose width is set to 100%. If you remove that the width attribute from that div the gap is gone. In my actual code, this 100% is set on a `bx--col`. Removing it is not an option for obvious reasons.



Here is the sandbox where I was trying it out (issue did not reproduce here): https://codesandbox.io/s/confident-driscoll-1l08v

I will let you decide whether to close this or not.

## Below screenshots show what I mean.

In cases where a parent has 100% width specified, the actual table is overflowing the `bx--table-container`.
<img width="472" alt="Screenshot 2020-01-10 at 3 42 30 PM" src="https://user-images.githubusercontent.com/31027320/72145157-ead7c200-33bf-11ea-882f-a6b28c9b7c8c.png">


<img width="1165" alt="Screenshot 2020-01-10 at 3 36 38 PM" src="https://user-images.githubusercontent.com/31027320/72144745-08f0f280-33bf-11ea-9099-644cd76ee542.png">


<img width="1131" alt="Screenshot 2020-01-10 at 3 34 42 PM" src="https://user-images.githubusercontent.com/31027320/72144655-d47d3680-33be-11ea-82b9-9b4fb264a4fc.png">

**Comment by asudoh** [comment] 2020-01-16 03:42
Tried http://react.carbondesignsystem.com/iframe.html?id=datatable--with-batch-actions&viewMode=story, but couldn't reproduce the issue. As you said, closing this for now, but if you get a reduced case don't hesitate to tell us and we can reopen the issue. I think you are close to creating one because you seem to have your code where the problem reproduces. What's needed is isolating the problem you have. Thanks!

**Comment by prince737** [comment] 2020-01-16 04:41
Hi @asudoh To reproduce the issue in the above link, you need to resize your browser window to a point where the table becomes scrollable and then you can see the issue. 

I will try recreating, If I am able, will get back. Thanks.

**Comment by asudoh** [comment] 2020-01-16 04:59
Tried to show horizontal scroll bar as well as vertical scroll bar, but no luck in my end. Probably I'm missing something? Anyhow great to have a reduced case. Thanks!

**Comment by prince737** [comment] 2020-01-16 05:28
Got it to reproduce now. Check it at https://codesandbox.io/s/confident-driscoll-1l08v
Remove the `width:100%` from the container div and the issue will be gone.

Also, here is a quick recording from storybook: 
[datatable-issue-480p.mov.zip](https://github.com/carbon-design-system/carbon/files/4069462/datatable-issue-480p.mov.zip)

**Comment by prince737** [comment] 2020-01-20 04:40
@asudoh Hi, since the issue was reproduced in an isolated instance can you please re-open this?

**Comment by asudoh** [comment] 2020-02-07 03:05
Thank you for the reduced case. Reopening. A workaround is setting `table-layout: fixed` to the `<table>`, but it's a breaking change.

**Comment by reeteshsingh93** [comment] 2020-09-23 07:49
@asudoh So shall we go with the workaround? or do we have plan to fix this permanently ?

**Comment by asudoh** [comment] 2020-09-23 07:54
I'll defer to the team, but given the workaround is a CSS tweak I think you can go with the workaround as you said.

**Comment by tw15egan** [comment] 2020-09-23 16:44
There have been changes to the DataTable so I would update to the latest and verify that this is still an issue.

**Closed as completed** 2022-11-14 16:26 UTC
Labels: type: bug 🐛, status: help wanted 👐, status: needs triage :female_detective:
