### ISSUE TITLE
Different dateFormat for "range" date picker displays range of value in single DatePickerInput

### ISSUE THREAD

**Issue by ketanb3** [carbon-design-system/carbon#5250] opened 2020-02-03 17:11 UTC
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
I am using a `DatePicker` with type `range` and using a different format `Y-m-d`. When I pass a value to this the children `DatePickerInput` component displays values in `start To end` format eg. `2020-02-03 to 2029-12-31`.

![image](https://user-images.githubusercontent.com/6772611/73668442-dbbcfa80-4673-11ea-9a0b-daf585cd1453.png)

> Is this issue related to a specific component?
Yes. DatePicker and DatePickerInput with customized `DateFormat` property of flatPicker.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I was expecting to see start and end values displayed in those individual `DatePickerInput` fields.

> What browser are you working in?
Firefox and Chrome

> What version of the Carbon Design System are you using?
"carbon-components": "^10.7.4",
"carbon-components-react": "^7.7.4",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Internal application

## Steps to reproduce the issue

1. Pass values to Parent `DatePicker` component with type = `range`
2. Pass the custom `dateFormat` property of flatpicker to `Y-m-d`
3. Pass the input value of array ['2020-02-03',  '2029-12-31']
4. Check the values rendered on browser.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment] 2020-02-04 00:29
Hi 👋 thank you for reporting - Seems a duplicate of #4803, but let us know if you don't think it's the case.

**Closed as completed by asudoh** 2020-02-04 00:29 UTC
Labels: type: bug 🐛
