### ISSUE TITLE
ComboBox: Icons use different colours

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon#4724] opened 2019-11-19 16:08 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

The icons inside `ComboBox` are two different colours. because two icons next to each other using different colours seems inconsistent we are assuming this is a bug, if however this in intentional please can you give me a reason so I can go back to my teams designer and PO

Clear button svg fill colour: `#525252`
Dropdown Chevron icon svg fill colour: `#161616`

> Is this issue related to a specific component?

`ComboBox`

> What version of the Carbon Design System are you using?

```
"@carbon/colors": "^10.5.0",
"@carbon/grid": "^10.6.0",
"@carbon/icons-vue": "^10.6.0",
"@carbon/vue": "^2.19.0 ",
"carbon-components": "^10.7.4",
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

no

## Steps to reproduce the issue

1. Goto combobox Story book
2. Select a value in the combo box
3. Observe the clear icon and the drop down arrow icon are different colours

> Please create a reduced test case in CodeSandbox

- http://vue.carbondesignsystem.com/?path=/story/components-cvmultiselect--default

## Additional information

<img width="334" alt="Screenshot 2019-11-19 at 16 06 16" src="https://user-images.githubusercontent.com/9937136/69163673-8a768380-0ae6-11ea-90a7-fa8515d4d6f4.png">

<img width="311" alt="Screenshot 2019-11-19 at 16 07 58" src="https://user-images.githubusercontent.com/9937136/69163816-cb6e9800-0ae6-11ea-9d64-4601e16ae1a8.png">

**Comment by asudoh** [comment] 2019-11-19 22:13
@carbon-design-system/design Which one is the correct color...? Thanks!

**Comment by laurenmrice** [comment] 2019-11-19 22:35
We currently have them as different colors because the close icon is a secondary action. # 525252 which is also `icon-02` is correct for the close icon. The chevron is our primary action so it gets the `icon-01` color token.

**Comment by asudoh** [comment] 2019-11-19 22:44
Thanks @laurenmrice for clarifying! Closing as working as designed.

**Closed as completed by asudoh** 2019-11-19 22:44 UTC
Labels: type: bug 🐛
