### ISSUE TITLE
NumberInput arrow buttons with decimal step value do not function correctly

### ISSUE THREAD

**Issue by guychris** [carbon-design-system/carbon#5249] opened 2020-02-03 16:38 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Trying to use NumberInput to set a value that can be fractional, eg. 0.5. Want to use a step value of `0.1` and noticing that the up/down arrows from the React component behave incorrectly and will sometimes be off by some small number, see attached screenshot or codesandbox. 

Appears to be a floating point number issue with the react component's up/down buttons because using the arrow keys in the NumberInput component, or the vanilla html number `<input>` does not cause this issue.

> Is this issue related to a specific component?

`<NumberInput>`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

arrow step buttons updated to handle decimal numbers

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.9.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Streams on CPD, end of February

## Steps to reproduce the issue

1. use something `<NumberInput step={0.1}>` 

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/jolly-mahavira-n4u4w

## Additional information

![image](https://user-images.githubusercontent.com/11824031/73670168-bed5f680-4676-11ea-9cb0-d189c4ce87cf.png)

**Comment by asudoh** [comment] 2020-02-04 00:46
Hi 👋 thank you for reporting! You hit a famous floating point issue with JavaScript. Will monitor how common the use case is, but meanwhile, you may try listening to `onChange()` and rectify the number yourself.

**Comment by tw15egan** [comment] 2020-02-04 01:00
For reference: https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by xxxle0** [comment] 2020-02-04 02:27
This is very famous issue. I really want to know how we handle it. 👍

**Comment by guychris** [comment] 2020-02-04 15:25
I noticed that the carbon NumberInput component adds its own up/down buttons and handles the logic, while hiding the browser number input's arrow buttons. Was the purpose of that to maintain consistency between browsers/devices? In my local environment I think I might be missing an scss import and on hover, in chrome, I am able to click on the browser native up/down arrows in the NumberInput component and those work as expected with step of 0.1.

Depending on resolution here I may either go with handling it in onChange() as you recommended @asudoh  or dropping NumberInput in favor of `<input type="number">` with carbon styling applied.

**Comment by asudoh** [comment] 2020-02-04 22:15
Good question @guychris - We hide native up/down buttons of `<input type="number">` due to limited capability of custom styling.

**Comment by piers-walter-ibm** [comment] 2020-02-27 10:58
I also encountered this issue, and implemented a workaround: [here](https://codesandbox.io/s/falling-wood-i1osq).

Could something like this be added as a prop to NumberInput perhaps 
```jsx
fixFloating={true}
```
I realise you may not want to interfere with the way javascript handles numbers and leave it as an exercise to the programmer, depending on their use case

**Comment by tay1orjones** [comment] 2020-10-19 17:09
> Will monitor how common the use case is

We've had this reported in our addons repo https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1693

![floating point math is fun](https://user-images.githubusercontent.com/3360588/96488652-ef10f580-1203-11eb-9364-43d6d245b726.gif)

**Comment by tay1orjones** [comment] 2023-08-18 15:51
Duplicate of https://github.com/carbon-design-system/carbon/issues/6684

**Closed as not planned by tay1orjones** 2023-08-18 15:51 UTC
Labels: severity: 3, type: bug 🐛, component: number-input
