### ISSUE TITLE
[Bug]: NumberInput component allows characters in Firefox if allowEmpty is true

### ISSUE THREAD

**Issue by preetibansalui** [carbon-design-system/carbon#17019] opened 2024-07-23 07:47 UTC
### Package

@carbon/react

### Browser

Firefox

### Package version

1.62.0

### Description

NumberInput is allowing characters (Other than numbers) if `allowEmpty` is true. 

### Reproduction/example

Video attached

### Steps to reproduce

https://github.com/user-attachments/assets/ac842a89-7067-46ee-9127-3e98af04251d

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2024-07-24 18:20
Thanks for opening this! We've had it reported and open a number of times. See here for a semi-recent convo and workaround: https://github.com/carbon-design-system/carbon/issues/13624#issuecomment-1696010343

**Comment by tay1orjones** [comment] 2024-07-24 18:21
Duplicate of https://github.com/carbon-design-system/carbon/issues/13624

**Comment by tay1orjones** [comment] 2024-07-24 18:21
Duplicate of https://github.com/carbon-design-system/carbon/issues/7039

**Closed as not planned by tay1orjones** 2024-07-24 18:21 UTC
Labels: type: bug 🐛, component: number-input, browser: firefox
