### ISSUE TITLE
[Bug]: Tag component renders improperly using v11 when using v10 implementation

### ISSUE THREAD

**Issue by embrown-ibm** [carbon-design-system/carbon#14633] opened 2023-09-11 17:41 UTC
### Package

@carbon/react, @carbon/icons

### Browser

Chrome

### Package version

v1.37.0

### Description

When I code a `<Tag>` component as below, the border, foreground and background colors appear to be incorrect. 
```
      <Tag
        locale={'en'}
        size="sm"
        key={'key'}
        type={'magenta'}
        isRemovable={false}
        maxCharacters={20}
        onClick={() => {}}
      >
        Random text
      </Tag>
```

re: https://github.com/carbon-design-system/carbon/issues/13145 

### Reproduction/example

https://stackblitz.com/edit/github-8bmids-cl4efk?file=src%2FApp.jsx

### Steps to reproduce

Implement the `<Tag>` component in your DOM and the problem will be apparent.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

I also use IBM Cloud PAL during the development of IBM Hyper Protect Crypto Services

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by lukas-kasticky** [comment] 2023-09-18 13:25
A `Tag` is rendered as a `div`. Using `onClick=` makes it a `button` instead. That's the weird styling you see.

I'm no expert on CDS and I don't know what you're trying to do, but as far as I can tell, Tags aren't meant to be used as buttons. There are no defined states for focus, hover etc. It wouldn't be clear to the user that they can be interacted with.

This would be the intended use case for 'filter chips', as [documented here](https://react.carbondesignsystem.com/?path=/docs/components-tag--overview):

```jsx
<Tag
  type="magenta"
  // ...
  filter={true}
  onClose={() => {}}
>
  Random text
</Tag>
```

Otherwise, forcing the container element to be a `div` might solve your problem, just make sure you document this 'hack' and test UX and a11y.

```jsx
<Tag
  as="div"
  type="magenta"
  // ...
  onClick={() => {}}
>
  Random text
</Tag>
```

**Comment by tay1orjones** [comment] 2023-09-18 13:37
Duplicate of https://github.com/carbon-design-system/carbon/issues/13145

**Closed as completed by tay1orjones** 2023-09-18 13:37 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
