### ISSUE TITLE
The `selected` prop doesn't work

### ISSUE THREAD

**Issue by NikitaKolokoltsev** [carbon-design-system/carbon#8584] opened 2021-05-05 15:01 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The first tab is always selected by default even if some other tab has `selected` prop. 

> Is this issue related to a specific component?

Tab

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected to see another tab being selected by default. Instead the first tab is always highlighted as selected one.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?
```
"carbon-components": "^10.33.0",
"carbon-components-react": "^7.33.0"
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Here is a demo provided by you which also doesn't work:
https://codesandbox.io/s/p14q0

If I add `selected` prop to the 2nd or 3rd tab, nothing happens. The first tab is still selected by default.

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment] 2021-05-05 15:33
the `selected` prop goes on the `<Tabs>` container and takes the index of the tab that should be selected https://carbon-components-react.netlify.app/?path=/story/components-tabs--playground

this behavior appears to function as expected in the Code Sandbox

**Comment by tw15egan** [comment] 2021-05-05 16:09
Closing as resolved, since the `selected` prop needs to be placed on the `Tabs` element to work as intended

**Closed as completed by tw15egan** 2021-05-05 16:09 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
