### ISSUE TITLE
StatefulTable: OverflowMenu should scroll with its container

### ISSUE THREAD

**Issue by ravinain** [carbon-design-system/carbon#9082] opened 2021-07-01 10:20 UTC
RowAction `OverflowMenu` in `StatefulTable` is not scrolling with the container. 

This issue is similar to https://github.com/carbon-design-system/carbon/issues/4755 . However, I'm using `StatefulTable`

When I set the parent `div` position to `relative`, it fixes the scroll issue but introduces another. After scroll, the position of overflow menu is not correct. This is exactly same problem mentioned in the aforementioned ticket.

Dependency: carbon-addons-iot-react: 2.145
Browser: Chrome

Expected Behavior:
`OverflowMenu` should scroll with container. Also, after scroll the overflow menu should display at correct position.

## Steps to reproduce the issue

1. .parent div is scrollable
2. scroll div
3. Now click on overflow rowAction
4. Notice the position of overflow rowAction menu

Example:

```
<div class="parent" data-floating-menu-container="data-floating-menu-container">
        <StatefulTable></StatefulTable>
</div>

.parent {
    position: relative;
}
```

You can also refer the aforementioned issue https://github.com/carbon-design-system/carbon/issues/4755.

**Comment by tw15egan** [comment] 2021-07-30 12:57
Hey there @ravinain, since this may be an issue with the `StatefulTable` component, would it make more sense to open an issue against the `carbon-addons-iot-react` repo instead? If you believe it is an issue with the core Carbon library, could you please recreate a reduced test case in [CodeSandbox](https://codesandbox.io/s/damp-glade-2koqo) so we can take a look?

**Comment by ravinain** [comment] 2021-08-02 10:10
Hi,

I have created an example here: [Overflow-Menu-Issue](https://codesandbox.io/s/overflow-menu-issue-forked-2kb2d?file=/src/index.js).

Steps to reproduce:

- Click on overflow menu on any record
- Scroll now. (The menu scroll with container, this is expected)
- Click on any other record now. You will notice the menu opened but at incorrect position.

**Comment by tw15egan** [comment] 2021-08-02 14:10
I'm unable to reproduce the issue.

![2021-08-02 10 07 56](https://user-images.githubusercontent.com/11928039/127874902-a9b5130c-e1fc-421c-ac62-dac6f9e0fcac.gif)

Going to close this as unable to reproduce, but if you can replicate the issue (without the `StatefulTable` component since that is an IOT add-on) we'd be more than happy to reopen and take another look.

**Closed as completed by tw15egan** 2021-08-02 14:10 UTC
Labels: severity: 3, type: bug 🐛, component: overflow-menu

**Comment by petersandor** [comment] 2022-11-08 11:46
@tw15egan this is still a problem, please see my slightly modified fork of the previously shared CodeSandbox: https://codesandbox.io/s/overflow-menu-issue-forked-y6f2d9

![Nov-08-2022 12-45-40](https://user-images.githubusercontent.com/3933866/200556046-b80be745-c7d0-4361-8694-c09d1d209c1a.gif)

**Comment by petersandor** [comment] 2022-11-08 15:36
@tw15egan it doesn't matter what component the `OverflowMenu` is in (it can even be a plain `div`), I can set up a different example.

**Comment by tw15egan** [comment] 2022-11-08 15:48
@petersandor, if you can reproduce the issue with just the overflow menu, please create a new issue so we can properly track a fix. This one seems to be tied to an addon library.

**Comment by petersandor** [comment] 2022-11-08 15:50
@tw15egan see screen recording from Carbon React Storybook page:

![Nov-08-2022 16-49-30](https://user-images.githubusercontent.com/3933866/200611672-282da7a2-06d5-4ef6-b362-11495d6920f0.gif)

All that is needed is the overflow scroll on the parent container, height limitation and a lot of content before and after the overflow menu.

**Comment by petersandor** [comment] 2022-11-08 16:42
@tw15egan here's a new CodeSandbox with everything https://codesandbox.io/s/romantic-cloud-lbdm42?file=/src/index.js

![Nov-08-2022 17-42-08](https://user-images.githubusercontent.com/3933866/200624276-d15e2949-a0a2-4ede-9e70-98c385733e0e.gif)

**Comment by tw15egan** [comment] 2022-11-08 16:46
If you wrap the menu in a `div` and set that as the container, it should be contained inside the scrollable container. 
https://codesandbox.io/s/dreamy-heisenberg-n41ncd?file=/src/index.js

**Comment by petersandor** [comment] 2022-11-08 16:57
> If you wrap the menu in a `div` and set that as the container, it should be contained inside the scrollable container. https://codesandbox.io/s/dreamy-heisenberg-n41ncd?file=/src/index.js

Right, so basically the overflow menu cannot have any sibling elements otherwise the positioning breaks.

**Comment by tw15egan** [comment] 2022-11-08 17:03
It [can have sibling elements](https://codesandbox.io/s/dreamy-heisenberg-n41ncd?file=/src/index.js); it just needs its position reset to a container inside the scrolling container rather than the scrolling container itself.

**Comment by petersandor** [comment] 2022-11-08 17:18
> It [can have sibling elements](https://codesandbox.io/s/dreamy-heisenberg-n41ncd?file=/src/index.js); it just needs its position set to a container inside the scrolling container rather than the scrolling container itself.

I see, this is an undocumented feature of the OverflowMenu though, I can see it is mentioned in the Tooltip which presumably uses the same underlying `FloatingMenu` component.

Thanks for help @tw15egan!

**Comment by tw15egan** [comment] 2022-11-08 17:30
Sorry for the confusion! If we can improve the documentation regarding this functionality, I'd love to update it to reduce headaches in the future, just let me know what should be copied over from the`Tooltip` documentation  🙂

**Comment by petersandor** [comment] 2022-11-08 17:36
Actually if I may ask one more question, I noticed that the class is not really necesary for the `data-floating-menu-container`, it selects by the attribute only:

https://github.com/carbon-design-system/carbon/blob/19778e9e8cf08dedf8a79bddd29337f0d5f63f88/packages/react/src/components/OverflowMenu/OverflowMenu.js#L455

Which means it selects the overflow menu button itself (I confirmed by removing the attribute's value in your CodeSandbox example).

**Comment by tw15egan** [comment] 2022-11-08 18:52
Updated the example https://codesandbox.io/s/dreamy-heisenberg-n41ncd?file=/src/index.js so that it correctly appends to the `div` and not the `OverflowMenu` 

https://github.com/carbon-design-system/carbon/issues/4755#issuecomment-673093566
