### ISSUE TITLE
[Feature Request]: Create an Typescript example using Carbon

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#16291] opened 2024-04-30 14:46 UTC
### The problem

Sometimes users on slack report bugs with Typescript and we need a reproduction example to better understand what is going on. Currently we only have a JS example in [Stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx).

### The solution

Create a Typescript example using Vite under `carbon/examples` folder in the monorepo.

### Examples

Working example: https://stackblitz.com/edit/vitejs-vite-xfkfg3?file=package.json,src%2FApp.tsx,src%2Fmain.tsx&terminal=dev

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2024-05-02 13:26
I actually opened an issue for this same thing over in the sandboxes repo 😅

**Comment by tay1orjones** [comment] 2024-05-02 13:26
Duplicate of https://github.com/carbon-design-system/sandboxes/issues/27

**Closed as not planned by tay1orjones** 2024-05-02 13:26 UTC
Labels: type: enhancement 💡, severity: 4, good first issue 👋, status: needs triage :female_detective:, area: typescript
