### ISSUE TITLE
Issue with FileUploaderDropContainer: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#4933] opened 2019-12-22 15:32 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I upgraded to 10.9.0 release, and found that FileUploaderDropContainer isn't working anymore when browsing for a file, however it's working fine when dropping a file inside the drop box!

## Additional information

> FileUploaderDropContainer.js:176 Uncaught TypeError: Cannot read property 'files' of undefined
    at validateFiles (FileUploaderDropContainer.js:176)
    at handleChange (FileUploaderDropContainer.js:207)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:386)
    at invokeGuardedCallback (react-dom.development.js:439)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:454)
    at executeDispatch (react-dom.development.js:585)
    at executeDispatchesInOrder (react-dom.development.js:610)
    at executeDispatchesAndRelease (react-dom.development.js:713)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:722)
    at forEachAccumulated (react-dom.development.js:694)
    at runEventsInBatch (react-dom.development.js:739)
    at runExtractedPluginEventsInBatch (react-dom.development.js:881)
    at handleTopLevel (react-dom.development.js:5832)
    at batchedEventUpdates$1 (react-dom.development.js:24387)
    at batchedEventUpdates (react-dom.development.js:1414)
    at dispatchEventForPluginEventSystem (react-dom.development.js:5928)
    at attemptToDispatchEvent (react-dom.development.js:6045)
    at dispatchEvent (react-dom.development.js:5948)

![image](https://user-images.githubusercontent.com/26740851/71323894-f0d53400-24e0-11ea-9e4d-2ea322162177.png)

Note
===
I thought at the beginning that it's related to the upgrade that I did to 10.9.0 (from 10.7.4) but managed to reproduce it on Sandbox!

I had this sandbox that the browse functionality working on it:
https://codesandbox.io/s/fragrant-morning-267l5

I forked the same sandbox, but with the new one the browse functionality isn't working:
https://codesandbox.io/s/heuristic-field-w2y75

**Comment by asudoh** [comment] 2019-12-23 22:23
Hi 👋 thank you for reporting - Seems a duplicate of #4899, let's discuss there further.

**Closed as completed** 2019-12-23 22:27 UTC

**Comment by zbeedatm** [comment] 2019-12-25 07:18
Thanks for letting me know.
Is there a workaround? If not I'll need to rollback to the previous version

**Comment by zbeedatm** [comment] 2019-12-25 08:09
Weird... even after reverting back to:

> "@carbon/colors": "^10.5.0",
    "@carbon/icons": "^10.6.1",
    "@carbon/icons-react": "^10.6.1",
    "@storybook/addon-knobs": "^5.2.6",
    "@types/storybook__addon-actions": "^3.4.3",
    "browserslist": "^4.7.3",
    "carbon-components": "^10.7.4",
    "carbon-components-react": "^7.7.4",

Symptom still exist, I'm not getting that error but nothing is happening when browsing for a file and selecting it!!!

**Comment by zbeedatm** [comment] 2020-01-02 08:24
Can you advice please...
