### ISSUE TITLE
[Bug]: Icon color in ghost button is filled in wrong color when high contrast mode + dark theme

### ISSUE THREAD

**Issue by s-onuma** [carbon-design-system/carbon#11557] opened 2022-06-06 15:09 UTC
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

carbon-components v10.53.0, carbon-components-react v7.53.0

### React version

v16.14.0

### Description

In high contrast mode with dark theme (e.g. carbon-theme--g90), a ghost button with `hasIconOnly` is not filled in the correct color.

**Expected:**
Ghost button icon should be filled in the text color.
![image](https://user-images.githubusercontent.com/22582535/172187631-2d4f6fe2-353b-4c00-80ac-a46f903bb17b.png)

**Actual:**
Ghost button icon is filled in black while tertiary button is correctly filled in the text color.
![image](https://user-images.githubusercontent.com/22582535/172187811-05592d41-90f4-4fbc-a14c-edcbfd6ba51e.png)

It's because ghost button is overwritten by `fill: ButtonText`.

https://github.com/carbon-design-system/carbon/issues/10199 is relevant (or duplicate).

### Reproduction/example

https://codesandbox.io/s/tearsheet-example-forked-hlzepj

### Steps to reproduce

1. Enable high contrast mode in your OS.
   I take macOS Monterey for example. Open System Preference and tick "Increase contrast" in Accessibility > Display.
![image](https://user-images.githubusercontent.com/22582535/172187184-8b85d453-130b-41f2-b82b-eea43e56a630.png)

2. Open the codesandbox example and set Gray 90 for the theme.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2022-09-14 19:38
Just an FYI MacOS "Increase Contrast" isn't fully supported by browsers, thus the high contrast modes don't always apply properly. Do you still see this issue when using Windows High Contrast mode? In V11, there is an `IconButton` component that does not seem to have these same issues, are you able to update?

**Comment by tw15egan** [comment] 2022-09-14 19:46
Updating to the latest versions of V10 seems to resolve this issue though: https://codesandbox.io/s/tearsheet-example-forked-ngc0l5?file=/src/Theme/ThemeDropdown.js

**Comment by tw15egan** [comment] 2022-09-15 14:29
Closing as I'm unable to reproduce on the latest version of V10. The icon is showing as visible in MacOS "Increase Contrast" mode as well as Windows HCM in both light and dark themes.

**Closed as completed by tw15egan** 2022-09-15 14:29 UTC
Labels: severity: 3, type: bug 🐛, package: react, component: button

**Comment by s-onuma** [comment] 2022-09-15 14:55
The latest V10 worked for me as well. Thank you.
