### ISSUE TITLE
IE Edge & Firefox ESR: Table with toolbar cannot hide one of toolbar-actions and toolbar-content 

### ISSUE THREAD

**Issue by zosmf-Mira** [carbon-design-system/carbon#4638] opened 2019-11-11 02:16 UTC
## What package(s) are you using?
"@carbon/icons-angular": "^10.4.0",
"carbon-components": "^10.6.1",
"carbon-components-angular": "^3.15.4",
"carbon-icons": "^7.0.7",

"@carbon/icons-angular": "^10.4.0",
"carbon-components": "^10.6.1",
"carbon-components-angular": "^3.15.4",
"carbon-icons": "^7.0.7",

## Detailed description
When I open carbon story in IE Edge and Firefox ESR, it could work well. However, in my project, it seems there is something wrong with the class whose name is "bx-batch-actions", the "clip-path" and "will-change-path" attributes in this class show error.
This problem only existed in IE edge and Firefox ESR.

> Describe in detail the issue you're having.
In IE Edge(Problem is existed) console:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/48002643/68555765-36c2c500-046a-11ea-8141-d8b31f4ff8b4.png">

In Firefox 17.0.1 console(Problem is not existed, result as we respect):
<img width="655" alt="image" src="https://user-images.githubusercontent.com/48002643/68555773-40e4c380-046a-11ea-80d3-74749cf896c9.png">

In Firefox ESR(Problem is existed) console:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/48002643/68555795-5659ed80-046a-11ea-8822-3b6f57951271.png">

> Is this issue related to a specific component?
<ibm-table-toolbar-actions>
              <button ibmButton="primary" (click)=delete()>
                  {{ _messageService.getBundle('BTN_DELETE') | translate}}
                  <ibm-icon-delete16 class="bx--btn__icon"></ibm-icon-delete16>
              </button>
              <button ibmButton="primary" 
                  id="setLogLevel"
                  (click)=setLogLevel()>
                  {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                  <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
              </button>
            </ibm-table-toolbar-actions> 

            <ibm-table-toolbar-content>

                <button 
                ibmButton="primary" size="sm" style="width: 90px"
                id="save" (click)=save() >
                    {{ _messageService.getBundle('BTN_SAVE') | translate}}
                    <ibm-icon-save16 class="bx--btn__icon"></ibm-icon-save16>
                </button>&nbsp;
                
                <button 
                ibmButton="primary" size="sm" style="width: 80px"
                id="resetDefault" (click)=resetDefault()> {{ _messageService.getBundle('BTN_RESTORE_DEFAULTS') | translate}}
                </button>&nbsp;

                <button 
                ibmButton="primary" size="sm" style="width: 80px"
                id="setAllLogLevel" (click)=setAllLogLevel()>
                {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                    <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                </button>&nbsp;
                
                <button ibmButton="primary" size="sm" style="width: 100px" (click)="openModal()">
                  {{ _messageService.getBundle('BTN_ADD_SERVICE') | translate}}
                    <ibm-icon-add20 class="bx--btn__icon"></ibm-icon-add20>
                </button>
                
            </ibm-table-toolbar-content>
          </ibm-table-toolbar>
       
          <ibm-table #tableContent
            style="display: block; width: 100%; min-height: 80px"
            [model]="model"
            [size]="size"
            [showSelectionColumn]="showSelectionColumn"
            [striped]="striped"
            [isDataGrid]="isDataGrid"
          >
          </ibm-table>
          <div *ngIf="showNoTableDataNotice" style="text-align:center;width:100%;">{{ _messageService.getBundle('TABLE_NO_DATA') | translate}}</div>
         
        </ibm-table-container>

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expect it show as other browsers that tool bar actions not show content in UI when user not select any items of table.

> What browser are you working in?
IE Edge, Firefox ESR.

> What version of the Carbon Design System are you using?
"@carbon/icons-angular": "^10.4.0",
"carbon-components": "^10.6.1",
"carbon-components-angular": "^3.15.4",
"carbon-icons": "^7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
zOSMF, Yes. we need ship our work item in 4Q which is depend on it. 

## Steps to reproduce the issue

1. Use <ibm-table-toolbar-actions> and <ibm-table-toolbar-content> with a customized <ibm-table> in HTML template.
2. 
Issue 1: Table with toolbar cannot hide one of toolbar-actions and toolbar-content in IE Edge and Firefox ESR.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/48002643/68556122-e51b3a00-046b-11ea-8d00-e508c801d9f1.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/48002643/68556128-ec424800-046b-11ea-8927-aba25237def1.png">
Issue 2: show the height too much. In Firefox ESR UI.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/48002643/68556172-10058e00-046c-11ea-9366-d14218105b75.png">
we respect it show as below in Firefox 17.0.0.1
<img width="547" alt="image" src="https://user-images.githubusercontent.com/48002643/68556204-30cde380-046c-11ea-9a5b-b88eb750fcf4.png">

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes
More detail information could refer to https://github.com/IBM/carbon-components-angular/issues/892.

**Comment by asudoh** [comment] 2019-11-18 03:12
Hi 👋 given you don't seem to reproduce this IE issue at http://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions (we don't, either), would you be able to create a reduced case? Interestingly, I cannot reproduce it at https://angular.carbondesignsystem.com/?path=/story/table--with-toolbar, either.

**Comment by joshblack** [comment] 2020-02-26 18:59
I believe this is addressed in latest carbon, let me know if this isn't the case!

**Closed as completed by joshblack** 2020-02-26 18:59 UTC
Labels: type: bug 🐛
