### ISSUE TITLE
[Button]: Tertiary States in Dark Themes

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon#4404] opened 2019-10-21 18:20 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The Tertiary Button in the darker themes (g90, g100) appears to be off and causing illegible text when interacting with the button.

`:focus`
![image](https://user-images.githubusercontent.com/3793636/67231432-ed4ffe80-f404-11e9-98d4-bbf6d360d355.png)

`:focus:hover`
![image](https://user-images.githubusercontent.com/3793636/67231450-f50fa300-f404-11e9-9346-d16117eb27a7.png)

`:hover:active`
![image](https://user-images.githubusercontent.com/3793636/67231500-0789dc80-f405-11e9-8352-8c6e10a0217b.png)

`:hover:active:focus`
![image](https://user-images.githubusercontent.com/3793636/67231532-183a5280-f405-11e9-89e2-a2df6998d4bb.png)

> What did you expect to happen?

I'm expecting something a little closer to these states.

![image](https://user-images.githubusercontent.com/3793636/67231226-83375980-f404-11e9-9e9d-f9378850f129.png)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

![image](https://user-images.githubusercontent.com/3793636/67231191-7581d400-f404-11e9-9562-045106ebcafe.png)

> What offering/product do you work on?

Dotcom

## Steps to reproduce the issue

1. `:focus`
2. `:focus:hover`
3. `:hover:active`
4. `:hover:active:focus`

> Please create a reduced test case in CodeSandbox
>
- https://codesandbox.io/s/dreamy-leaf-mzkt0?fontsize=14

**Comment by aledavila** [comment] 2020-01-14 19:55
Closing this as it seems it has been fixed. Cannot reproduce anymore. If you feel this is still an issue feel free to post an updated code sandbox and will reopen. Thanks!

**Closed as completed by aledavila** 2020-01-14 19:55 UTC
Labels: type: bug 🐛
