### ISSUE TITLE
[Feature Request]: Add secondaryButtonDisabled property to the Modal widget.

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#14026] opened 2023-06-16 20:49 UTC
### The problem

When the submit job is running I need to disable the Cancel (Secondary button) and the Submit (Primary button) until the submit job is completed. Currently, the user may think hitting the cancel button will cancel the submit job already in progress.

Today the Modal widget has a property to disable the primary button (primaryButtonDisabled) but not one to disable the secondary button.

<Modal
           open={openCallHomeDump}
           modalHeading={t('CallHomeDumpTitle')}
           primaryButtonText={callHomeButtonLabel === ""?t('CallHomeButton'):callHomeButtonLabel}
           secondaryButtonText={t('CancelButton')}
           onRequestClose={() => closePanel()}
           onRequestSubmit={() => submitCallHomeDump()}
           primaryButtonDisabled = {(dumpNames.length===0) || callHomeDisabled}
           secondaryButtonDisabled = {cancelDisabled}
           preventCloseOnClickOutside={true}
           className="heading-03"
        >

### The solution

I would like the Modal widget to support a secondaryButtonDisabled property to be able to enable / disable the secondary button like the primary button has primaryButtonDisabled.

### Application/PAL

Carbon nd Carbon for IBM products

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2023-10-04 15:51
Thanks for submitting this idea! There's work in progress for this right now in https://github.com/carbon-design-system/carbon/pull/14490

**Comment by tay1orjones** [comment] 2023-10-04 15:51
Duplicate of https://github.com/carbon-design-system/carbon/issues/10495

**Closed as not planned by tay1orjones** 2023-10-04 15:51 UTC
Labels: type: enhancement 💡, role: dev 🤖, component: modal, proposal: accepted
