### ISSUE TITLE
[Bug]: FilterableMultiSelect onMenuChange not called on click outside menu

### ISSUE THREAD

**Issue by gi** [carbon-design-system/carbon#16896] opened 2024-06-28 21:44 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

1.57.0

### React version

v16.14.0

### Description

When clicking outside the menu when opened, the onMenuChange callback is not fired with the next opened state.

The change came between
[de133bea](https://github.com/carbon-design-system/carbon/blob/de133bea57dd3fef5ef45361e0906521b8c63991/packages/react/src/components/MultiSelect/FilterableMultiSelect.js)
and
[5f35edd6](https://github.com/carbon-design-system/carbon/blob/5f35edd666dfd2d30737d0095d1b3be31078f5e6/packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx)
when `FilterableMultiSelect.js` was renamed to `FilterableMultiSelect.tsx`.

The `Downshift` component had an `onOuterClick` prop set to `handleOnOuterClick` which called `handleOnMenuChange`.

### Reproduction/example

https://stackblitz.com/edit/github-wivrwb?file=src%2FApp.jsx&preset=node=

### Steps to reproduce

1. use `onMenuChange` prop on `FilterableMultiSelect` component
5. open dropdown
6. click outside menu to close
7. `onMenuChange` callback is not called

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Gururajj77** [comment] 2024-07-04 06:27
Hi @gi , could you please let us know the steps to reproduce this issue, by making a stackblitz example so that we can work on this issue better and resolve it.

Please use sandboxes from this [carbon sandboxes](https://github.com/carbon-design-system/sandboxes/blob/main/README.md) repo, they are already customized with carbon library

**Comment by ferdelamad** [comment] 2024-07-16 18:01
Hey @Gururajj77 I'm facing the same issue, any idea when this will be fixed? Is currently blocking us from upgrading Carbon due to this bug.

Thanks!

**Closed as completed** 2024-09-12 20:11 UTC
Labels: severity: 3, type: bug 🐛, role: dev 🤖, component: filterable-multiselect
