### ISSUE TITLE
TooltipDefinition is not shown properly

### ISSUE THREAD

**Issue by Amir-61** [carbon-design-system/carbon#5759] opened 2020-03-31 16:06 UTC
CSS issue for TooltipDefinition component.

TooltipDefinition goes underneath of other components:

![image (1)](https://user-images.githubusercontent.com/10672146/78049285-df55c080-7348-11ea-8f0c-c5c519e46ef5.png)

```
<TooltipDefinition
   align='start'
   direction='bottom'
   tooltipText={name}
>
```

**Comment by emyarod** [comment] 2020-03-31 16:14
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by Donisius** [comment] 2020-03-31 18:17
It seems to be caused by the table container, removing it causes the tooltip to be fully displayed. I believe wrapping the table within a div or an element with a `display: block` property causes the tooltip to appear behind the wrapping parent. Changing the z-index appears to have no effect

**Comment by joshblack** [comment] 2020-03-31 18:26
Most likely a parent container has `overflow: hidden` which would be my guess! 😄

**Comment by Donisius** [comment] 2020-03-31 18:28
Removing the `overflow-x: auto` from `.bx--data-table-container` seems to "fix" it

**Comment by joshblack** [comment] 2020-03-31 20:37
Yeah, definitely is a tricky problem unfortunately 😞 In this case the overflow is for horizontal scroll if I remember correctly. I believe this is a limitation within CSS and it is unlikely that we could do much to resolve it. If you have any ideas let us know!

Going to close this out for now but am happy to re-open if there is something we can to do help address this!

**Closed as completed by joshblack** 2020-03-31 20:37 UTC
Labels: status: won't fix ❌, type: question ❓, component: tooltip
