### ISSUE TITLE
IDL/Carbon: Icon library: Icons totally missing or partially missing on download. 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#6354] opened 2020-06-26 22:14 UTC
It looks like many of the alphanumerical and acronyms are missing altogether and also parts and pieces are missing on some. It seems scattered throughout all categories.

blank when opened in Ai:
![Screen Shot 2020-06-26 at 5.12.03 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/f95b4783-db32-47aa-9cc0-3d576f34c49f)

Partial missing in Ai (pedestrian icon)

![Screen Shot 2020-06-26 at 5.12.08 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/0d37b38f-76b8-47ca-a23a-41d2790f9709)

What is odd to me is the show up in preview:

[Uploading... Screen Shot 2020-06-26 at 5.14.18 PM.png ]

**Comment by conradennis** [comment] 2020-06-29 13:33
this issue relates to #6324

**Comment by joshblack** [comment] 2020-06-30 15:43
Closing as duplicate of #6324

**Closed as completed by joshblack** 2020-06-30 15:43 UTC
