### ISSUE TITLE
Multiselect: Not able to programatically change values

### ISSUE THREAD

**Issue by galilmori** [carbon-design-system/carbon#9151] opened 2021-07-09 11:45 UTC
## What package(s) are you using?

- [x] carbon-components v10.36.0
- [x] carbon-components-react v7.36.0

## Detailed description
- MultiSelect.Filterable component doesnt have selectedItems property like its relative Dropdown component.
- It only has the "initalSelectedItems" which allows to set the initial internal state.
- This causes a big limitation and buggy behaviour where we cannot programmatically reset the internal values of the component.

> What did you expect to happen?
 - allow programmatically setting internal selected values. same behaviour exists in Dropdown component
> What happened instead? 
 - with onChange i can retreive values selected but i cannot clear or set values without interraction with component after inital rendering 

>What would you like to see changed?
 - a way to programatically set values as it should be possible with all components
> What browser are you working in?
 - Google Chrome

> What offering/product do you work on?
 - Ibm cloud Power-iaas. This issue causes major blocker where we set values outside the component which are not reflected. also i cannot clear values in the component without the interraction with component check boxes or chip close button

## Steps to reproduce the issue
 - create component with a list and provide the selected items in 'initialSelectedItems' or 'selectedItems' as it has been done in combobox and dropdown components
 - store initialSelected items in a react state
 - change that state by this.setState or with useState setter
 - the changes are not reflected
  
##  Reduced test case in CodeSandbox
- https://codesandbox.io/s/bold-blackwell-qv843?file=/index.js

**Comment by tay1orjones** [comment] 2021-07-19 19:32
Hey there! 👋  

For `initialSelectedItems`, the hope with the prop name is that it reveals that what is passed to the component only represents what is selected on the initial render - it's not meant for after-creation updates. Renders after that will "desync" from what is provided in that initial value. Rendering the component [with a new `key`](https://reactjs.org/docs/reconciliation.html#keys) should resolve this issue and force the component to recreate a new instance of the component.

**Comment by tay1orjones** [comment] 2021-07-19 19:32
Duplicate of https://github.com/carbon-design-system/carbon/issues/4812

**Closed as completed by tay1orjones** 2021-07-19 19:32 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬

**Comment by galilmori** [comment] 2021-07-23 09:19
Hi @tay1orjones

 I hope that this is closed only because its a duplicate and not because of the "rendereing with new key" workaround. 
 is this #4812 request going to be implemented? and when is the ETA? its open since 2019

**Comment by dhebert-dev** [comment] 2021-09-16 17:54
I can confirm that since the issue was raised in 2019 nothing has been done to address the problem. This is causing a lot of difficulty for me and my team.
