### ISSUE TITLE
[Bug]: TreeView's default story is broken

### ISSUE THREAD

**Issue by Gururajj77** [carbon-design-system/carbon#17388] opened 2024-09-09 09:54 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

v11

### React version

v18

### Description

The default story in TreeView section is broken

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-treeview--overview

### Steps to reproduce

Go to the default story of the above url

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by AustinGitHub** [comment] 2024-09-09 14:45
I have an issue here for this https://github.com/carbon-design-system/carbon/issues/17379

**Comment by 2nikhiltom** [comment] 2024-09-11 08:42
Closing this bug as its a duplicate of #17379

**Closed as not planned by 2nikhiltom** 2024-09-11 08:42 UTC
Labels: type: bug 🐛, severity: 4, role: dev 🤖, component: treeview
