### ISSUE TITLE
InputNumber component can't input invalid number 

### ISSUE THREAD

**Issue by wangqunOne** [carbon-design-system/carbon#5339] opened 2020-02-13 06:57 UTC
Now our project is using v10.9.3 version. But our scene can't be satisfied. We do this according to the link https://react.carbondesignsystem.com/?path=/story/numberinput--default.
```
 <NumberInput
  className="some-class"
  helperText="Optional helper text."
  id="tj-input"
  invalidText="Number is not valid"
  label="Number Input label"
  max={100}
  min={0}
  onChange={this.onChange}
  step={10}
  value={this.props.value}
/>
```
Our function this.onChange is one state change to setDate(value). When I change the input value is smaller than min. It always show the min value not to be our input value. We need any value can be input. 

At the same time, I find the "useControlledStateWithValue" in the https://github.com/carbon-design-system/carbon/blob/v10.9.1/packages/react/src/internal/FeatureFlags.js is false. We want to control our value to show.  How we can set it is true in our project. 

And I try to change the useControlledStateWithValue is true in our path /node_modules/carbon-components-react/es/internal/FeatureFlags.js. But I got one error: 

![hh](https://user-images.githubusercontent.com/15885127/74411550-7be60100-4e76-11ea-9c14-7c7ec5f63c29.gif)

 Thanks.

**Comment by asudoh** [comment] 2020-02-13 11:53
Comparing https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number and https://react.carbondesignsystem.com/?path=/story/numberinput--default, I see the behavior is close, which is, you can type number beyond min/max range (by keyboard), and if you do that, you get form validation error (the former is on submit, the latter is on change). Both won't let you go beyond min/max with up/down buttons. Let us know if your point is about a completely different thing.

Wrt how to use feature flags, https://github.com/carbon-design-system/carbon-components-react/blob/v6.105.0/docs/experimental.md#application-usage has the best example. BTW you can control the value from application even without the feature flag - The flag is for completely ignoring the state in "fully-controlled" mode.

**Comment by wangqunOne** [comment] 2020-02-25 04:14
@asudoh Thank you for answering my question.Now I want to satify two conditions and we are using v10.9.3 version：
1. Don't allow to input the negative number. And it can input other number. When it exceeds the min and max value, it will have the error remind message.
2. The arrow button only control to input the max and min value. It doesn't allow to click to exceed the max and min value.
So I set the useControlledStateWithValue = true in webpack.js. It can realize the second one. But the first one isn't ok. I want to extend the numberinput to overwrite the "handleChange" function in order to statify the first one. But I find I can't extend it because it isn't one enable extend class. I want to know what can i do to realize the overwrite or anyway to realize the first one. Thanks.

**Comment by asudoh** [comment] 2020-02-25 09:39
Carbon already supports 2. Carbon doesn't support 1. Note that native `<input type="number">` doesn't support 1. either.

**Comment by pallypan** [comment] 2020-02-26 04:52
@asudoh 
the issue is NumberInput provide interface useControlledStateWithValue and props.value to let user controle displayed value, but when we use them, it fail. 
We can make trick in our code to work around, but this is still a bug need to be fixed.

we can see in code https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/NumberInput/NumberInput.js#L187
--- constructor will skip state init if user select to use control mode
but in https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/NumberInput/NumberInput.js#L159
--- when getDerivedStateFromProps, it will get value from state even in control mode which it won't init state at all
this is the bug need to be fixed, or it should not privide such property

**Comment by asudoh** [comment] 2020-02-26 09:07
Please note that any non-default feature flags, including `useControlledStateWithValue`, is considered experimental. A PR to fix issues with such feature flag is welcome, though.

**Comment by wangqunOne** [comment] 2020-02-27 03:45
@asudoh Could you or someone help to fix this issue in one pr in  v10.9.3 version?

**Comment by asudoh** [comment] 2020-02-27 08:24
Sent a quick patch to NPE. I see other behaviors are correct as I mentioned and thus wontfix.

**Closed as completed** 2020-02-27 23:31 UTC
Labels: type: bug 🐛

**Comment by wangqunOne** [comment] 2020-02-28 03:18
@asudoh Do you recommend this ControlledStateWithValue to be used？
And will it  be a trend？

**Comment by asudoh** [comment] 2020-02-28 03:20
> Do you recommend this ControlledStateWithValue to be used？

No, given the nature of non-default feature flags.
