### ISSUE TITLE
DatePicker calendar using appendTo prop is badly positioned if scrolling has occurred

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#6007] opened 2020-05-04 15:44 UTC
I reported https://github.com/carbon-design-system/carbon/issues/4818, which has been closed as fixed.  I finally got the chance to test the fix and found that it is only partly fixed.  It works fine when you open the calendar picker if you have not scrolled.  However, if you have scrolled at all before opening the picker, the calendar position is off by the amount scrolled.

This can be reproduced using the original code sandbox and updating all the dependencies to "latest"  (currently 10.11.2/7.11/3)
https://codesandbox.io/s/codesandbox-fyj49

**Comment by asudoh** [comment] 2020-05-08 00:03
Hi 👋 thank you for reporting. Following your steps I cannot reproduce the problem: https://codesandbox.io/s/codesandbox-656r7 That said, wondering if you still see the problem?

**Comment by kglickman** [comment] 2020-05-08 11:40
Yes, I can reproduce it.  Scroll down a little bit so that the date picker is closer to the top of the view and the button is partly scrolled out.  Then open the date picker.  The calendar partially covers the date picker input field.  If you don't scroll, it works fine and the calendar is underneath the date picker input field.

With scroll:
![image](https://user-images.githubusercontent.com/30597411/81402072-b5897980-90fe-11ea-8575-7a7682fcaf0e.png)

Without scroll:
![image](https://user-images.githubusercontent.com/30597411/81402218-fbded880-90fe-11ea-8118-f8f8fffc37f4.png)

**Comment by asudoh** [comment] 2020-05-08 11:58
Thanks - The problem happens because the `appendTo` itself is the scrolling element. Would you try moving the `ref={this.setAppendTo}` to `<div className="innerContainer">` and add CSS rule like `.innerContainer{ position: relative; }`? It seems to fix the problem as far as I can see.

**Comment by kglickman** [comment] 2020-05-08 12:27
Yes, that works.  Thanks.

**Comment by tw15egan** [comment] 2020-05-12 18:18
Closing as resolved, feel free to reopen if you feel that is not the case 🙂

**Closed as completed by tw15egan** 2020-05-12 18:18 UTC
Labels: type: bug 🐛
