### ISSUE TITLE
[a11y]: Latest version of Chrome reporting issues on close button of toast notification

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon#17253] opened 2024-08-22 21:17 UTC
### Package

@carbon/react

### Browser

Chrome

### Operating System

Windows

### Package version

latest (Carbon React Storybook)

### Automated testing tool and ruleset

N/A - coming from Chrome

### Description

Chrome is reporting the following when opening a Toast notification
![image](https://github.com/user-attachments/assets/19284eaf-ad0b-4157-8f14-6255dd315073)

### Reproduction/example

I can see the issue in the story book

### Steps to reproduce

Look at the styles on the close button in the story book.  You have to actually open the notification to see the Chrome error.
![image](https://github.com/user-attachments/assets/bd5e3f25-7aa4-4a8a-8c0d-052c81c685dd)

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2024-08-23 15:09
Duplicate of https://github.com/carbon-design-system/carbon/issues/15907

**Closed as not planned by tay1orjones** 2024-08-23 15:09 UTC
Labels: type: a11y ♿, status: needs triage :female_detective:
