### ISSUE TITLE
[Bug]: Deprecation warning when using getSelectionProps

### ISSUE THREAD

**Issue by OmranAbazid** [carbon-design-system/carbon#17951] opened 2024-11-01 17:10 UTC
### Package

@carbon/react

### Package version

1.69.0

### Description

when passing the getSelectionProps to the TableSelectAll of the datatable, it shows a warning for deprecation for the old ariaLabel format.

### Reproduction/example

https://codesandbox.io/p/sandbox/carbon-datatable-forked-4cn436

### Steps to reproduce

- Open the page code sanbox
- open the console
- check the warning

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by AlanGreene** [comment] 2024-11-05 13:05
This looks like a duplicate of https://github.com/carbon-design-system/carbon/issues/17584

**Closed as completed** 2024-11-06 10:11 UTC
Labels: status: waiting for maintainer response 💬
