### ISSUE TITLE
Carbon tooltip doesn't recompute the position when the browser screen is resized

### ISSUE THREAD

**Issue by vladbalanescu** [carbon-design-system/carbon#5062] opened 2020-01-16 09:57 UTC
<!-- Feel free to remove sections that aren't relevant.
In our code we use this component from the Storybook which seems to not recompute position relative to the hidden tooltip icon that we implemented for our product once the window resizes:
http://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom

Proof here:
![image](https://user-images.githubusercontent.com/16047402/72514439-7df07c00-3846-11ea-915c-bb3f47b2e1d9.png)
![image](https://user-images.githubusercontent.com/16047402/72514467-8c3e9800-3846-11ea-9848-d07d9acaf183.png)

**Comment by xxxle0** [comment] 2020-01-16 09:58
hi @vladbalanescu i think this tooltip is not support auto positioning. You can integrate this tooltip with Popper.js package if you want.

**Comment by tw15egan** [comment] 2020-01-16 22:21
Closing as this seems like a duplicate of https://github.com/carbon-design-system/carbon/issues/5063

**Closed as completed by tw15egan** 2020-01-16 22:21 UTC
Labels: type: bug 🐛
