### ISSUE TITLE
FileUploaderItem errorSubject / errorBody props are not rendering

### ISSUE THREAD

**Issue by queeniema** [carbon-design-system/carbon#6909] opened 2020-09-25 00:20 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

I am playing around with the `FileUploaderItem` component in the Storybook here: https://react.carbondesignsystem.com/?path=/story/fileuploader--file-uploader-item. No matter what I try, I cannot get the `errorSubject` and `errorBody` to render. See the screenshot below.

> Is this issue related to a specific component?

Yes, `FileUploaderItem`.

> What did you expect to happen? What happened instead? What would you like to see changed?

When setting `invalid = true`, I expect `errorSubject` and `errorBody` to render underneath the component. I believe this used to work in the past.

> What browser are you working in?

Safari Version 14.0

> What version of the Carbon Design System are you using?

Latest (7.20.0)

## Steps to reproduce the issue

1. Tick the checkbox for the `invalid` prop
1. Notice that neither of the error messages appear.

## Additional information

![Screen Shot 2020-09-24 at 5 14 31 PM](https://user-images.githubusercontent.com/2454818/94212776-f3a6f000-fe89-11ea-9b33-67d9b7701532.png)

**Comment by emyarod** [comment] 2020-09-25 14:43
this looks like a duplicate of https://github.com/carbon-design-system/carbon/issues/6866 but should be addressed in https://github.com/carbon-design-system/carbon/pull/6867

**Closed as completed by emyarod** 2020-09-25 14:43 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
