### ISSUE TITLE
Allow using an action button in multi-line inline/toast notifications

### ISSUE THREAD

**Issue by swwebster** [carbon-design-system/carbon#7181] opened 2020-10-29 22:15 UTC
### Summary

Typically, when we use inline/toast notifications in our product, we are using multi-line notifications. (It's rare for our descriptions to be super brief, so we like the more optimal layout of the multi-line.) Along those same lines, usually our action description in the button is around 3 words long, which can take up quite a bit of horizontal space. If we could have action buttons in the multi-line notification as well as the single line, that would be great!

I believe this is a design and development change, since the multi-line component would need to support an action button.

![image](https://user-images.githubusercontent.com/73671599/97637506-cb6e5c00-1a08-11eb-8512-6924522ef07d.png)

### Justification

Currently, our FEDs will be using a custom version of the component for more optimal layout. Going forward, it would be more optimal and efficient for our devs to be able to use a "approved" component

### Desired UX and success metrics

Unfortunately, because of the complexity of our product, it's very rare that when we use an inline notification, that we have very brief descriptions. It's a constant negotiation with our Information/Content Developer to keep these descriptions short, but sometimes it simply needs to be a little longer. If the description is longer and has an action, then it doesn't look very good to use the single line notification with an action.

Here's a real world example I came across recently:
![image](https://user-images.githubusercontent.com/73671599/97637986-a5958700-1a09-11eb-8d68-4afb762568ff.png)

Context of the notification:
![image](https://user-images.githubusercontent.com/73671599/97638486-9f53da80-1a0a-11eb-96a2-f77471c12b1e.png)

Having an action element in a multi-line notification is much better in this case.

### Specific timeline issues / requests

For now, our devs are able to use the custom component I mentioned above, so it is not urgent. But it's definitely a nice to have!

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

I'm happy to help with building the component in Sketch if necessary. I'm sure my FED colleague could be consulted as well for the custom component that he created.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by vpicone** [comment] 2021-06-21 16:38
@tay1orjones is there an open issue for this, can we close it as duplicate?

**Comment by tay1orjones** [comment] 2021-06-21 16:58
@vpicone Yes, We've been tracking this as an exploration over in https://github.com/carbon-design-system/carbon/issues/8703. A finalized spec was recently posted and we'll be working from there. 

Will close this one as a duplicate - thanks for opening the issue @swwebster! #8703 should meet your use case described here with some additional accessibility benefits.

**Comment by tay1orjones** [comment] 2021-06-21 16:58
Duplicate of #8703

**Closed as completed by tay1orjones** 2021-06-21 16:58 UTC
Labels: type: enhancement 💡, component: notification, proposal: open
