### ISSUE TITLE
In overflow menu, keyboard actions on overflow menu options is not working.

### ISSUE THREAD

**Issue by aparnacyanam** [carbon-design-system/carbon#1860] opened 2019-02-18 23:31 UTC
## Environment

Chrome 70
macOS Mojave

## Detailed description

In an expanded overflow menu, the options have different operations like redirecting to a different page or opening a new modal or performing a function on click of a mouse or by pressing enter. These features are working with the mouse but not with a keyboard(like pressing enter overflow menu closes).

## Steps to reproduce the issue
Here is a codepen for reference
https://codepen.io/anon/pen/pGGbyR

**Comment by asudoh** [comment] 2019-02-19 05:43
CC @emyarod

**Comment by emyarod** [comment] 2019-02-20 16:57
this seems to be a duplicate of https://github.com/IBM/carbon-components/issues/1470 if I'm not mistaken

**Closed as completed** 2019-02-22 04:50 UTC
Labels: type: a11y ♿
