### ISSUE TITLE
Tabs component issue using carbon-design-system

### ISSUE THREAD

**Issue by sakshigoyal007** [carbon-design-system/carbon#9056] opened 2021-06-29 07:14 UTC
I am facing issue in adding Tabs component in my react application code. This is my code:
` 
<Tabs type="container">
<Tab  label="Tab1"></Tab>
 <Tab label="Tab2" ></Tab>
<Tab label="Tab3" ></Tab>
</Tabs>
`

This is the link to Tabs component usage in carbon design system for reference:
https://www.carbondesignsystem.com/components/tabs/usage

Earlier it was working fine and I didn't make any changes in it. But since yesterday, while running the application, instead of showing this format->
![correctTabFormat](https://user-images.githubusercontent.com/17652784/123751701-a272d380-d8d5-11eb-9ccd-fe05e0382ad9.PNG)

it is displaying the tabs as show below->
![wrongTabFormat](https://user-images.githubusercontent.com/17652784/123751831-c7674680-d8d5-11eb-9092-70376dc30a13.PNG)

 What needs to be done to correct it?

**Comment by xSCIven** [comment] 2021-06-29 12:05
I think this is an issue related to the sass module system they are implementing in carbon as of the recent update.

**Comment by tw15egan** [comment] 2021-06-29 13:05
Hey there @sakshigoyal007 , can you reproduce the issue in a [CodeSandbox](https://codesandbox.io/s/elated-banach-eef99)? I'm not seeing the issue locally or on the deployed React storybook. The sass module work should not have any effect on this, as it is net new functionality and isn't modifying any of the existing styles.

**Comment by sakshigoyal007** [comment] 2021-06-30 10:31
Hi @tw15egan, here is the link to the CodeSandbox code. I have added only the Tab component part for the reference.
https://codesandbox.io/s/tab-carbon-react-rt25h

**Comment by tw15egan** [comment] 2021-06-30 13:20
@sakshigoyal007 it doesn't seem like you are pulling in the Carbon styles anywhere in your Codesandbox. Here's an example using the unpkg CDN that is [correctly rendering the Tabs](https://codesandbox.io/s/flamboyant-andras-pcjdp?file=/src/index.js). Specifically, [this line](https://codesandbox.io/s/flamboyant-andras-pcjdp?file=/public/index.html:409-508). Hope that helps!

**Comment by sakshigoyal007** [comment] 2021-07-01 13:33
@tw15egan, thank you for bringing this to my notice, I have corrected it in the reference code in sandbox. 

But I already included this stylesheet inside css folder in current Project and have given its url in index.html. And it was working fine earlier, there were no issues with rendering carbon components. And if I am trying to add it separately in index.html like you mentioned, other sass functions of the react application are not working properly.

So, I’m wondering if it could be an issue with system update and release as they are introducing CDN artifacts for every component. Can you please suggest how I can make it work?

**Comment by tw15egan** [comment] 2021-07-01 13:41
If your watning to access the sass functions, you'll need to pull in the styles through `npm`/`yarn` and compile the scss files on your own. The CDN ships pre-compiled css files. If you need help getting started with that, I'd take a look at the tutorial that goes over installing / importing the styles here: https://www.carbondesignsystem.com/developing/react-tutorial/overview/

SInce the `Tabs` seem to be rendering correctly and this seems like an app-level import issue, I'm going to close this out but feel free to comment if you run into any other issues.

**Closed as completed by tw15egan** 2021-07-01 13:41 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
