### ISSUE TITLE
[a11y]: Notifications - Inline,Toast -Default - Focus not going on "close notification" button

### ISSUE THREAD

**Issue by guidari** [carbon-design-system/carbon#16392] opened 2024-05-09 12:58 UTC
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.56.0

### React version

18.02

### Automated testing tool and ruleset

Manual QA

### Assistive technology

JAWS

### Description

The screen reader tab/arrow key focus is not going on close notification button

### Recommended Fix
Ensure that the close button recieves tab/arrow key focus and is announced by the screen reader

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-notifications-inline--default

### Steps to reproduce

none

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2024-08-23 15:09
Duplicate of https://github.com/carbon-design-system/carbon/issues/15907

**Closed as not planned by tay1orjones** 2024-08-23 15:09 UTC
Labels: severity: 3, type: bug 🐛, type: a11y ♿, role: dev 🤖, component: notification, a11y: JAWS
