### ISSUE TITLE
[Bug]: Slider conflicted validation when non-numerical is entered

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon#11177] opened 2022-04-07 19:07 UTC
### Package

carbon-components, carbon-components-react

### Browser

Firefox

### Package version

10.56.0

### React version

17.0.2

### Description

When the `props.invalid` is provided to the component, it seems to be overriding the internal validation by Slider.
In Chrome, this seems to be fine, since it prevents user from entering non-numerics to the text input. However, when in Firefox, it's still allowed to enter alphabetical characters. The internal validation logic will catch this error - in the storybook, it will highlight with red border on the input box. 
But when we provide external validation, it fails to validate, because `props.onChange` is not called when the input value is not valid (alphabetics), thus it never reaches to external validation logic. Neither user nor application have a way to capture such error.

### CodeSandbox example

https://codesandbox.io/s/slider-bugs-forked-6vtp9c?file=/src/index.js:307-313

### Steps to reproduce

- use Firefox, enter string "abc" into input box
- move focus away
- the input box is not highlighted with red border.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2022-04-08 19:03
Duplicate of https://github.com/carbon-design-system/carbon/issues/9225

**Comment by tay1orjones** [comment] 2022-04-08 19:04
Duplicate of https://github.com/carbon-design-system/carbon/issues/9696

**Comment by tay1orjones** [comment] 2022-04-08 19:04
@nelsonchen90 This is closely related to https://github.com/carbon-design-system/carbon/issues/7039 in that it's a similar issue (but with NumberInput instead of Slider) ultimately caused by [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528). 

In the case of NumberInput, `onKeyUp` can be provided to work around this. For Slider, there's no way to provide an `onKeyUp` to the input. A prop could be added to facilitate `onKeyUp` on the Slider's input element though. Would this work for your use case? 

Otherwise my understanding is that this is blocked externally by the browser's implementation.

**Comment by nelsonchen90** [comment] 2022-04-08 19:12
@tay1orjones thanks for the analysis.

> A prop could be added to facilitate onKeyUp on the Slider's input element though

Are you proposing a new prop `onKeyUp` for Sliders? assuming it will be called with the current value in the input element, I think it will work for our use case.

**Closed as completed** 2022-04-21 16:42 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬

**Comment by nelsonchen90** [comment] 2022-06-14 16:24
@tay1orjones 
by any chance this would be available to v7 of carbon component react (https://v10-react.carbondesignsystem.com/)

**Comment by fukudasjp** [comment] 2023-04-03 07:40
@tay1orjones sorry for mentioning you again, but could this fix be back-ported to v10?
