### ISSUE TITLE
DatePicker : Typing the date in text box should not show the calendar to select the date.

### ISSUE THREAD

**Issue by swatipandey158** [carbon-design-system/carbon#5834] opened 2020-04-09 09:21 UTC
Steps to reproduce -
1. Go to datepicker component in storybook -
2. type date in textbox and hit enter -> calender should not open.
<img width="871" alt="Screenshot 2020-04-09 at 2 48 33 PM" src="https://user-images.githubusercontent.com/59439592/78879209-35c1ae00-7a71-11ea-95ac-5066342403b7.png">

Expected behavior: If the date is typed in the text box then the calendar should not be opened to select the data again.

**Comment by emyarod** [comment] 2020-04-09 15:48
cc @carbon-design-system/design about the expected UX for the date picker here. I assume showing the calendar is correct even if the user is typing in the date?

**Comment by aagonzales** [comment] 2020-04-09 16:26
Yes, the existing behavior is as intended. When date-picker with calendar is focused the calendar automatically opens and remains open even if the user is just typing. There is not a separate feature to exclusively open the calendar. This is the standard ux practice, you can look at Google flights or Kayak to see similar interactions. 

 If you do not want a calendar with your date picker than you should use the `simple date-picker`

**Comment by emyarod** [comment] 2020-04-09 18:08
thanks @aagonzales, closing this issue

**Closed as completed by emyarod** 2020-04-09 18:08 UTC
