### ISSUE TITLE
[Bug]: React: Controlled <FilterableMultiSelect> does not update when data is changed externally

### ISSUE THREAD

**Issue by freder** [carbon-design-system/carbon#11457] opened 2022-05-23 14:53 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

1.3.0

### React version

17, 18

### Description

I'm using `FilterableMultiSelect` with the `selectedItems` items prop, which makes it a _controlled component_ – at least that would be my expectation. however:
1. I still need `initialSelectedItems` to pre-select items (why?)
2. more importantly: changing the selected data externally (via `useState` hook) does not seem change the component state

### Reproduction/example

https://stackblitz.com/edit/github-cpq1kc?file=src%2FApp.jsx

### Steps to reproduce

- add / remove items via `FilterableMultiSelect` component itself
- then remove items via buttons below
- observe how `FilterableMultiSelect` component does not update

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2022-09-19 15:45
Duplicate of https://github.com/carbon-design-system/carbon/issues/10340

**Closed as not planned by tay1orjones** 2022-09-19 15:45 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, component: multiselect, status: needs triage :female_detective:
