### ISSUE TITLE
Link active state not working on first click.

### ISSUE THREAD

**Issue by LeviApp** [carbon-design-system/carbon#9101] opened 2021-07-02 14:50 UTC
The active style on an achor element is not being rendered properly.

## What package(s) are you using?

I am using the `carbon-components` and  `carbon-components-react` dependencies

I am trying to create a style on an anchor's active state. While the style is applied if you click on the link twice, the style is not applied the first time it is clicked.

I am using the SideNav, with SideNavItems and SideNavItem links, but it could be a broader issue.

I am using
"@carbon/charts-react": "0.41.52",
"@carbon/icons-react": "10.29.0",

We are building a dashboard for IBM. We need it fixed as soon as possible.

1. Use Carbon's standard class names
2. Apply active style in scss

I am using a Windows 10 virtual machine.

**Comment by joshblack** [comment] 2021-07-02 17:27
Hi there @LeviApp! 👋  Could you provide some steps to reproduce in a [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)?

**Comment by LeviApp** [comment] 2021-07-02 18:03
@joshblack Here it is... It must be an issue with Carbon working on a virtual machine

https://codesandbox.io/s/sidenaveissue-16y5h

**Comment by tay1orjones** [comment] 2021-07-19 16:20
Duplicate of https://github.com/carbon-design-system/carbon/issues/9137

**Closed as completed by tay1orjones** 2021-07-19 16:20 UTC
Labels: status: needs more info, type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
