### ISSUE TITLE
Add JS token export from the motion package;

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#7118] opened 2020-10-23 11:40 UTC
### Summary

The layout and theme packages export JS tokens which can be used to produce the SCSS variable/tokens documented not the Carbon Design System website. A JS export is much simpler to use when writing tools based on the Carbon Design System. e.g. A stylelint plugin and is required to be able to address https://github.com/lee-chase/stylelint-plugin-carbon-tokens/issues/18

### Justification

Tools that help the developer stay on track with Carbon have the potential to save a huge amount of time invested in a manual code verification and certification process.

### Desired UX and success metrics

Motion tokens can be imported into javascript directly from the @carbon/motion package in the same form as @carbon/theme and @carbon/layout

### "Must have" functionality

A JS export of all valid tokens

### Specific timeline issues / requests

The current stylelint plugin relies on an importing and parsing SCSS which relies upon locating files via a relative path. This is likely to be less reliable than the defined node-modules import.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

Doing this in a fashion that is consistent with other packages would require a build change. As a result, it is probably best addressed by a member of the core team.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by joshblack** [comment] 2020-10-23 20:00
Going to close this as a duplicate of #6779 which I think covers the same topic. Let me know if not!

**Closed as completed by joshblack** 2020-10-23 20:00 UTC
