### ISSUE TITLE
Advance charts: Heat map, color use

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon#5033] opened 2020-01-14 16:14 UTC
Hi, Regarding this data vis:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/12818623/72361107-ed3b6400-36be-11ea-9261-f4bec56c53b7.png">

Please reconsider color choices by reviewing this video:
https://youtu.be/R-oiKt7bUU8?t=2621

**Comment by asudoh** [comment] 2020-01-15 00:46
hi @heatherco would you want to enter this at https://github.com/carbon-design-system/carbon-charts? Thanks!

**Comment by theiliad** [comment] 2020-01-16 16:07
Hi @heatherco, thanks for bringing these points up. Some of these were noticed by design, however there was never a resolution that was approved to be implemented. I'll bring this up again with design.

In the meantime I suggest closing the issue here and copying the content over to carbon-design-system/carbon-charts#466

**Comment by asudoh** [comment] 2020-01-16 21:51
Moved to: #466

**Closed as completed by asudoh** 2020-01-16 21:51 UTC
Labels: type: enhancement 💡, proposal: open
