### ISSUE TITLE
[Feature Request]: Tooltip for long file names for the file uploader

### ISSUE THREAD

**Issue by adrianabitoiu** [carbon-design-system/carbon#13718] opened 2023-05-03 09:24 UTC
### Description
When uploading files with long names that are shortened with ellipsis, it would be helpful to have a tooltip that displays the full file name when hovering over the shortened name.

### Current Behavior
Currently, when uploading files with long names, the name is shortened with ellipsis. However, there is no way to view the full file name.

### Desired Behavior
When hovering over the shortened file name, a tooltip should appear that displays the full file name.

### Additional Information
This feature would be especially helpful for users who frequently upload files with long names or who need to check what they uploaded.

### The solution

When hovering over the shortened file name, a tooltip should appear that displays the full file name.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2023-05-03 14:37
Hi @adrianabitoiu, thanks for this suggestion! I agree this would be a welcome improvement to the existing state of things.

This was sort-of proposed back in https://github.com/carbon-design-system/carbon/issues/6775. I just posted a https://github.com/carbon-design-system/carbon/issues/6775#issuecomment-1533138312 there underscoring the need for a Tooltip when the file name is truncated. 

I'm going to close this as a duplicate, but if you have any further ideas or concerns please add them to https://github.com/carbon-design-system/carbon/issues/6775

**Comment by tay1orjones** [comment] 2023-05-03 14:37
Duplicate of https://github.com/carbon-design-system/carbon/issues/6775

**Closed as not planned by tay1orjones** 2023-05-03 14:37 UTC
Labels: type: enhancement 💡, status: waiting for author's response 💬, status: needs triage :female_detective:
