### ISSUE TITLE
[a11y]: Poor contrast on disabled fields

### ISSUE THREAD

**Issue by vsgoulart** [carbon-design-system/carbon#13286] opened 2023-03-03 10:21 UTC
### Package

@carbon/react

### Browser

Chrome

### Operating System

Other

### Package version

1.23.1

### Automated testing tool and ruleset

Chrome a11y tools

### Description

Almost all input component (selects, text inputs, radio buttons) have a very poor contrast when disabled. Specially on labels and description texts.

<img src="https://user-images.githubusercontent.com/1022916/222694911-d6e2a6ad-fcb6-492b-aa50-23f840e08900.png" width="400"/>

### Reproduction/example

https://stackblitz.com/edit/github-1eigkz-2c3lru?file=src%2FApp.jsx

### Steps to reproduce

Check the contrast on any input component

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-03-06 15:51
https://github.com/carbon-design-system/carbon/issues/13266#issuecomment-1452062360

> Disabled elements are removed from the accessibility tree and are not required to meet contrast ratio requirements, as seen [here in Understanding Contrast Requirements](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).
>
>Ref https://github.com/carbon-design-system/carbon/issues/13006
>Ref https://github.com/carbon-design-system/carbon/issues/11165

**Comment by tay1orjones** [comment] 2023-03-06 15:52
Duplicate of #13266

**Closed as not planned by tay1orjones** 2023-03-06 15:52 UTC
Labels: status: waiting for author's response 💬, type: a11y ♿, status: needs triage :female_detective:
