### ISSUE TITLE
Code blocks are cutting off at line 94

### ISSUE THREAD

**Issue by mcorbin-ibm** [carbon-design-system/carbon#5690] opened 2020-03-24 18:33 UTC
On IBM Developer, we have a tutorial with three long code samples that are cutting off at line 94 for some reason.  There are more than 100 lines of code.

Here's the URL on our staging server, as this content has not yet been published
https://ibmdev1.rtp.raleigh.ibm.com/tutorials/interacting-with-zos-using-mobile-device-with-zowe-and-flutter/

The long code listings are in step 6 (last listing) and step 8 (4th and final listings).

**Comment by tw15egan** [comment] 2020-03-24 18:56
Closing as duplicate of https://github.com/carbon-design-system/carbon/issues/5684

**Closed as completed by tw15egan** 2020-03-24 18:56 UTC
Labels: type: bug 🐛

**Comment by tw15egan** [comment] 2020-03-24 18:57
The issue is caused because of the `max-height` set on the snippet container, used for transitions. This can be overridden to a larger value as a temporary fix.
