### ISSUE TITLE
Issues while testing with Jest

### ISSUE THREAD

**Issue by rax-it** [carbon-design-system/carbon#3689] opened 2019-08-08 18:04 UTC
## What package(s) are you using?
		"carbon-components": "^10.4.1",
		"carbon-components-react": "^7.4.1",
                "jest": "^24.1.0",

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
 ● Test suite failed to run

    TypeError: Cannot read property 'type' of undefined

      1 | import React, { Component } from 'react';
      2 | import ReactDOM from 'react-dom';
    > 3 | import {
        | ^
      4 | 	Button,
      5 | 	Dropdown,
      6 | 	Modal,

      at node_modules/carbon-components-react/lib/prop-types/childrenOf.js:33:47
          at Array.map (<anonymous>)
      at childrenOf (node_modules/carbon-components-react/lib/prop-types/childrenOf.js:32:49)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ListBox/ListBox.js:83:37)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ListBox/index.js:8:39)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ComboBox/ComboBox.js:20:40)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ComboBox/index.js:13:40)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/index.js:987:41)
      at Object.<anonymous> (src/settings/panels/details/ContactSourceModal/ContactSourceModal.js:3:1)
      at Object.<anonymous> (tests/src/settings/panels/details/ContactSourceModal/ContactSourceModal.spec.js:4:1)

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by rax-it** [comment] 2019-08-08 18:06
The tests are working fine when using V9 versions of Carbon design

**Comment by asudoh** [comment] 2019-08-08 21:44
Hi 👋 thank you for reporting - Given our CI (with Jest) runs fine, would you want to share your test setup so we can see what errors you are hitting?

**Comment by rax-it** [comment] 2019-08-09 13:06
Do you mean the jest config files?
```module.exports = {
	clearMocks: true,
	coverageDirectory: 'coverage',
	coverageReporters: ['json', 'text', 'lcov'],
	moduleFileExtensions: ['js', 'json', 'jsx', 'node', 'ts', 'tsx'],
	moduleNameMapper: {
		'\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/tests/__mocks__/fileMock.js',
		'\\.(css|less|scss)$': '<rootDir>/tests/__mocks__/styleMock.js',
		'^Utils(.*)$': '<rootDir>/src/utils/utils.js',
		'^Services(.*)$': '<rootDir>/src/services',
		'@carbon/icons-react(.*)$': '<rootDir>/tests/__mocks__/fileMock.js',
	},
	setupFiles: ['<rootDir>/tests/setupTests.js'],
	transform: {
		'^.+\\.(js|jsx)?$': 'babel-jest',
	},
	verbose: true
};
```

**Comment by rax-it** [comment] 2019-08-09 13:06
Do you mean the jest config files?
`module.exports = {
	clearMocks: true,
	coverageDirectory: 'coverage',
	coverageReporters: ['json', 'text', 'lcov'],
	moduleFileExtensions: ['js', 'json', 'jsx', 'node', 'ts', 'tsx'],
	moduleNameMapper: {
		'\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/tests/__mocks__/fileMock.js',
		'\\.(css|less|scss)$': '<rootDir>/tests/__mocks__/styleMock.js',
		'^Utils(.*)$': '<rootDir>/src/utils/utils.js',
		'^Services(.*)$': '<rootDir>/src/services',
		'@carbon/icons-react(.*)$': '<rootDir>/tests/__mocks__/fileMock.js',
	},
	setupFiles: ['<rootDir>/tests/setupTests.js'],
	transform: {
		'^.+\\.(js|jsx)?$': 'babel-jest',
	},
	verbose: true
};
`

**Comment by rax-it** [comment] 2019-08-09 13:07
Do you mean the Jest config files?
```
module.exports = {
	clearMocks: true,
	coverageDirectory: 'coverage',
	coverageReporters: ['json', 'text', 'lcov'],
	moduleFileExtensions: ['js', 'json', 'jsx', 'node', 'ts', 'tsx'],
	moduleNameMapper: {
		'\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/tests/__mocks__/fileMock.js',
		'\\.(css|less|scss)$': '<rootDir>/tests/__mocks__/styleMock.js',
		'^Utils(.*)$': '<rootDir>/src/utils/utils.js',
		'^Services(.*)$': '<rootDir>/src/services',
		'@carbon/icons-react(.*)$': '<rootDir>/tests/__mocks__/fileMock.js',
	},
	setupFiles: ['<rootDir>/tests/setupTests.js'],
	transform: {
		'^.+\\.(js|jsx)?$': 'babel-jest',
	},
	verbose: true
};
```

**Comment by asudoh** [comment] 2019-08-10 10:30
Not just that - It means the reduced case where we can see the problem with. Thanks!

**Comment by rax-it** [comment] 2019-08-13 13:12
This is my Component:
```
import React, { Component } from 'react';
import { Lists } from './Lists';
import { createLogger, getCuiRenderViewData, getShellStore, isCui, updateActionbarAction } from 'prod-fed-shell-services-ui';
import WchContextMenu from '../utils/WchContextMenu';
import { getEventEmitter, translate } from '../utils/utils';
import './Emails.css';

const logger = createLogger('emails');

// The Emails component is used to open the Composer for an existing email or navigate back to the Home Component.
export class Emails extends Component {
	constructor (props) {
		super(props);
		this.timeout = null;
	}

	componentDidMount () {
		getShellStore().dispatch(
			updateActionbarAction({
				hidden: true,
			})
		);

		if (isCui()) {
			// Clear the url content ID and add the campaigns page indicator query parameters for navigation and refresh
			getCuiRenderViewData()
				.then(() => {
					// broadcast the updated current URL after a delay to allow CUI to process
					this.timeout = setTimeout(() => {
						getCuiRenderViewData().then(updatedData => {
							getEventEmitter().emit('UPDATE_CURRENT_URL', updatedData.currentURL);
						});
					}, 100);
				})
				.catch(e => {
					logger.error(`Could not parse the common shell RENDER_VIEW_DATA object: ${e.message || e}`);
				});
		}
	}

	componentWillUnmount () {
		clearTimeout(this.timeout);
	}

	render () {
		return (
			<div className="emails" id="emails_div">
				<Lists
					query="&fq=kind:(email)&fq=!kind:(sample)&fq=!tags:hidden&fl=id,name,thumbnail,description,kind,lastModified,document:[json]&sort=lastModified%20desc"
					noResultsMsg={translate('No results. Create some emails in the composer, or perform a new search.')}
					loadErrorMsg={translate('The list of emails could not be loaded.')}
					canToggleTemplates="true"
					canSearch="true"
					canCreate={true}
					canDelete="true"
				/>
				<WchContextMenu htmlComponentId="emails_div" />
			</div>
		);
	}
}
```

**Comment by rax-it** [comment] 2019-08-13 13:12
And the test:
```
 FAIL  tests/src/email-lists/Emails.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'type' of undefined

      1 | import React, { Component } from 'react';
      2 | import { Link } from 'react-router-dom';
    > 3 | import { ContentSwitcher, Search, Switch, Button, TooltipDefinition, Modal, InlineNotification as CarbonNotification } from 'carbon-components-react';
        | ^
      4 | import Notification from '../notification/Notification';
      5 | import Grid16 from '@carbon/icons-react/lib/grid/16';
      6 | import List20 from '@carbon/icons-react/lib/list/20';

      at node_modules/carbon-components-react/lib/prop-types/childrenOf.js:33:47
          at Array.map (<anonymous>)
      at childrenOf (node_modules/carbon-components-react/lib/prop-types/childrenOf.js:32:49)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ListBox/ListBox.js:83:37)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ListBox/index.js:8:39)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ComboBox/ComboBox.js:20:40)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/components/ComboBox/index.js:13:40)
      at Object.<anonymous> (node_modules/carbon-components-react/lib/index.js:987:41)
      at Object.<anonymous> (src/email-lists/Lists.js:3:1)
      at Object.<anonymous> (src/email-lists/Emails.js:446:10)
      at Object.<anonymous> (tests/src/email-lists/Emails.spec.js:4:1)
```

**Comment by asudoh** [comment] 2019-08-14 08:53
The reduced case has to be something we can run (ref: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases). Thanks!

**Comment by joshblack** [comment] 2019-11-19 23:02
Hi @rax-it! 👋 Thanks so much for taking the time to make an issue. Going to close this for now since it's been open a couple of months, feel free to comment if you have some steps to help us reproduce!

**Closed as completed by joshblack** 2019-11-19 23:02 UTC
Labels: status: needs more info
