### ISSUE TITLE
[Code snippet] Code snippet copy is not working

### ISSUE THREAD

**Issue by xxxle0** [carbon-design-system/carbon#5320] opened 2020-02-11 16:08 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The code snippet copy icon is not working in the carbonwebsite and codepen demo page (https://www.carbondesignsystem.com/components/code-snippet/code)
> Is this issue related to a specific component?
CodeSnippet
> What did you expect to happen? What happened instead? What would you like to
> see changed?
Copy to clipboard after click copy icon

## Steps to reproduce the issue

We can test it in react storybook

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/c02i0
> - React:
>   https://react.carbondesignsystem.com/?path=/story/codesnippet--inline
## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment] 2020-02-12 00:05
Hi 👋 thank you for reporting - Looks a duplicate of: #4448

**Closed as completed by asudoh** 2020-02-12 00:05 UTC
Labels: type: bug 🐛
