### ISSUE TITLE
Support left/right tooltip positioning

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2678] opened 2019-05-10 19:03 UTC
![image](https://user-images.githubusercontent.com/8265238/57550437-fbfd9a00-732b-11e9-84b6-d2aea442cbbc.png)

image from [this comment](https://github.com/carbon-design-system/carbon/issues/2460#issuecomment-491320129)

Related: https://github.com/carbon-design-system/carbon/issues/2460 https://github.com/carbon-design-system/carbon/issues/2604

**Comment by asudoh** [comment] 2019-05-10 22:16
@shixiedesign Do you this the left/right "sides" apply to definition tooltip, too? (Or is it only for icon tooltip?) Thanks!

**Comment by shixiedesign** [comment] 2019-05-13 15:35
Hi @asudoh @emyarod, I just confirmed: side tooltips are **only for icon tooltip on hover**, so not definition tooltip. 

Expected usage of side tooltip is on side rails & vertical toolbars: 

![image](https://user-images.githubusercontent.com/15144993/57634222-80d5f700-756a-11e9-9737-814d07529ebe.png)

**Comment by shixiedesign** [comment] 2019-05-16 18:09
All positioning and alignment options in this issue are done! 🎉

**Comment by shixiedesign** [comment] 2019-05-16 18:18
To summarize our tooltip's functionalities: 

### Interactive tooltip: 
- Position: top, bottom, left right. Done! 
- Alignment: only center. Done! 

### Definition tooltip: 
- Position: only top & bottom. Done! 
- Alignment: start, center, end. Done! 

### Icon tooltip:
- Position: top&button, **still need left, right**
- Alignment: center, still **need start, end** 

So we still need a PR for the bolded items on Icon tooltip then we can close this item. Does that seem right to you guys? @asudoh @emyarod 

## 📖 Guidelines to add
@connor-leech I think ☝️ above looks like good info to include in our Tooltip usage section.

**Comment by emyarod** [comment] 2019-05-16 19:30
all of the icon tooltip requirements are fulfilled

position: top and bottom https://github.com/carbon-design-system/carbon/pull/2749

position: left, right https://github.com/carbon-design-system/carbon/pull/2732

alignment: start, end https://github.com/carbon-design-system/carbon/pull/2732

**Comment by shixiedesign** [comment] 2019-05-16 19:44
Perfect! Thanks @emyarod Closing issue then.

**Closed as completed by shixiedesign** 2019-05-16 19:44 UTC
Labels: type: enhancement 💡, role: dev 🤖
