### ISSUE TITLE
SideNavItems - Getting console error after adding more children elements in this component.

### ISSUE THREAD

**Issue by JoseJesusOchoaTorres** [carbon-design-system/carbon#6754] opened 2020-09-01 03:29 UTC
##  Brief description:

I am trying to add a divider or <hr> between a couple of link elements of my Carbon SideNav to create small sections, but I am getting this console error/warning.

```
Warning: React does not recognize the `isSideNavExpanded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issidenavexpanded` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

- [Codesandbox](https://codesandbox.io/s/adoring-shaw-hpmu0?file=/src/index.js:0-1252)
<details>
  <summary>Snippet code</summary>
  
```js
import React, { useState } from "react";
import { render } from "react-dom";

import {
  Header as CarbonHeader,
  HeaderName,
  HeaderMenuButton,
  SideNav,
  SideNavItems,
  SideNavLink
} from "carbon-components-react";

const App = () => {
  const [isSideNavExpanded, onClickSideNavExpand] = useState(false);
  const triggerSideNav = () => onClickSideNavExpand(!isSideNavExpanded);

  return (
    <div>
      <CarbonHeader aria-label="IBM Platform Name">
        <HeaderMenuButton
          aria-label="Open menu"
          isCollapsible
          onClick={triggerSideNav}
          isActive={isSideNavExpanded}
        />

        <HeaderName href="/" prefix="IBM">
          Service Operations
        </HeaderName>

        <SideNav
          aria-label="Side navigation"
          isPersistent={false}
          expanded={isSideNavExpanded}
        >
          <SideNavItems>
            <li>Title</li>

            <SideNavLink to="#" aria-current="page">
              Link 1
            </SideNavLink>

            <SideNavLink to="#" aria-current="page">
              Link 2
            </SideNavLink>
          </SideNavItems>
        </SideNav>
      </CarbonHeader>
    </div>
  );
};

render(<App />, document.getElementById("root"));
```
</details>

As you can see we can't add a lot of HTML tags in the `<SideNavItems>` carbon component:

```js
<SideNav
          aria-label="Side navigation"
          isPersistent={false}
          expanded={isSideNavExpanded}
        >
          <SideNavItems>
            <li>Title</li> // <-- This li tag is generating the issue

            <SideNavLink to="#" aria-current="page">
              Link 1
            </SideNavLink>

           ...
          </SideNavItems>
</SideNav>
```

I tried to add the `<SwitcherDivider>`, `<span>`, `<div>`, `<p>` and I am still getting the same error.

![image](https://user-images.githubusercontent.com/8441759/91791011-b11a2c80-ebd7-11ea-982d-02e87521e544.png)

### Is this issue related to a specific component?

`<SideNavItems>`

### What did you expect to happen?

See properly the divider between my links without the console log error message.

### What browser are you working in?

Chrome

### What version of the Carbon Design System are you using?

More information in my [Codesandbox](https://codesandbox.io/s/adoring-shaw-hpmu0?file=/src/index.js:0-1252) link above

## Additional information

You can see in this screen capture how the rule/divider it correctly rendered but we have the error message.

![image](https://user-images.githubusercontent.com/8441759/91791666-5255b280-ebd9-11ea-9c38-6e0888b2b411.png)

**Comment by emyarod** [comment] 2020-09-01 15:14
related https://github.com/carbon-design-system/carbon/issues/3970

**Comment by JoseJesusOchoaTorres** [comment] 2020-09-01 17:15
> related #3970

Thanks, @emyarod  and sorry, I did not see this related ticket.

**Comment by joshblack** [comment] 2020-09-03 15:59
Going to close this as a duplicate of #3970 👀  Let me know if I'm mistaken and I'd be happy to re-open!

**Closed as completed by joshblack** 2020-09-03 15:59 UTC
