### ISSUE TITLE
Error in text area box results in content shifting

### ISSUE THREAD

**Issue by pdixit26** [carbon-design-system/carbon#6831] opened 2020-09-14 15:40 UTC
There is a slight shift in content when there is an error on the text area input.

![8c272302-fe45-44e0-8e49-5694648a5fe3-2](https://user-images.githubusercontent.com/19144807/93107007-e312a080-f665-11ea-90f0-53b18bfc609c.png)

![81363bcf-47ff-42e7-bdbf-c813f60293a8-2](https://user-images.githubusercontent.com/19144807/93106947-d130fd80-f665-11ea-88f3-9495694b7d22.png)

**Comment by pdixit26** [comment] 2020-09-14 15:40
made by different id

**Comment by pdixit26** [comment] 2020-09-14 15:44
opening it again.

**Comment by emyarod** [comment] 2020-09-16 15:08
I believe this is intentional and follows the component spec, cc @laurenmrice for confirmation

**Comment by laurenmrice** [comment] 2020-09-16 15:44
When an invalid state is present for text area a text error message should appear below the text area. Any content below this will be shifted down to provide enough space. From your screenshot it appears there is no text error message showing.

**Comment by alisonjoseph** [comment] 2020-10-26 14:45
Closing as this appears to be working as intended.

**Closed as completed by alisonjoseph** 2020-10-26 14:45 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, component: text-area
