### ISSUE TITLE
[Bug]: Tooltip responding to click events

### ISSUE THREAD

**Issue by haspal** [carbon-design-system/carbon#11827] opened 2022-07-19 05:42 UTC
### Package

carbon-components-react

### Browser

Chrome

### Package version

^10.50.0

### React version

17.0.2

### Description

When we click on a tooltip of icon button, the tooltip responds to click event. For eg- If there is a close icon button with tooltip and i click on the icon, the modal closes. if i click on the tooltip of the button, it behaves similarly and closes the modal. 
expected behaviour -
Onclick should be disabled on tooltip.

### Reproduction/example

https://codesandbox.io/s/strange-zeh-u5zis2?file=/src/index.js

### Steps to reproduce

1. Click on the icon, alert popup is displayed
2. Click on tooltip, alert popup is displayed
expected - On clicking of tooltip, alert popup should not be displayed.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2022-07-19 15:06
Hey @haspal, thanks for reporting. I see the issue you are encountering. It seems like the issue is fixed in v11, so if possible I would recommend upgrading to the newest version. Let me know if you are able to do this

**Closed as not planned** 2022-12-07 15:10 UTC
Labels: version: 10, type: bug 🐛, status: waiting for author's response 💬, component: button
