### ISSUE TITLE
v10 Pagination - issue with select dropdown (design change)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#1649] opened 2019-01-16 23:25 UTC
From the current way the pagination component is designed, the open select dropdowns are triggering the full name displayed when the dropdown is closed.

Comments by emyarod:
![Screen Shot 2019-01-16 at 5.18.13 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/07fb69b2-9431-4dda-979e-323c89bb1d0b)

We only want to have the dropdown showing individual numbers inside of it, so we are proposing to reorder the chevrons and numbers to fix this problem.

![Pagination design change.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/fff89948-2060-4c2d-af9d-39ee7918db84)

@IBM/carbon-developers

**Comment by emyarod** [comment] 2019-01-16 23:46
I'm slightly confused but is this a duplicate of https://github.com/IBM/carbon-components/issues/1638?

**Closed as completed** 2019-01-28 03:52 UTC
Labels: role: dev 🤖

**Comment by asudoh** [comment] 2019-02-08 02:39
Refs IBM/carbon-components#1749
