### ISSUE TITLE
Bidi support: Structured text at static components is not supported in Carbon components

### ISSUE THREAD

**Issue by amirbrans** [carbon-design-system/carbon#7291] opened 2020-11-15 13:02 UTC
Structured text is a predefined, machine-readable syntax or internal structure in static data. Some elements of the structured text contains Bidi text ( Arabic, Hebrew, Urdu) while others English text.  Also, structured text can be bidirectional on some cases. 
Common cases for structure text can be found in: file path, breadcrumb, file name, email address, text concatenation etc..
However, Carbon components does not apply structure text processing expected to happen for structure text patterns and as a result can obfuscate its structure, making the text’s display misleading or even incomprehensible.

An example illustrating structure text case with file path:

![image](https://user-images.githubusercontent.com/20791186/99184035-f8c94280-2748-11eb-8e5b-b145bc388c31.png)

Examples in Carbon components:

 1)   File path in label:

![image](https://user-images.githubusercontent.com/20791186/99184531-2663bb00-274c-11eb-9815-82ea52f62a6d.png)

2) URL in checkbox

![image](https://user-images.githubusercontent.com/20791186/99185599-93c71a00-2753-11eb-8545-3d6139398fa7.png)

  @mattrosno , @joshblack ,  @adir01  FYI

**Comment by joshblack** [comment] 2021-04-01 20:33
Hi there @amirbrans! 👋  Could you share a quick [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) with steps to reproduce so we can make sure this issue is addressed?

**Comment by wajnberg** [comment] 2021-04-05 11:56
Hello @joshblack ,

I created this quick sandbox https://codesandbox.io/s/blazing-snow-jnuyh
to illustrate the problem

Please tell me if you need anything else
Thank you

@sadir@il.ibm.com. FYI

**Comment by joshblack** [comment] 2021-04-08 17:55
Thanks @wajnberg! 🙏 

In terms of the expected outcome, what would need to be provided to the text in order to match the expected behavior? I tried re-creating this with a `<span>` to see what could applied to the text but couldn't seem to get the expected sequence 🤔 

In other words:

```html
<span>http://אבג1/דהו2/זחט3</span>
```

With `dir="rtl"` or `direction: rtl` in CSS didn't seem to work. Curious what your thoughts are here!

**Comment by laurenmrice** [comment] 2021-06-21 16:18
Hi @amirbrans and @wajnberg 👋, just checking in to see if you still have any thoughts on the above?^

**Comment by tay1orjones** [comment] 2021-06-21 16:19
Potentially related to #7264 ?

**Comment by adir01** [comment] 2021-06-21 16:56
@wajnberg please comment
@tay1orjones yes, it is related to  #7264

**Comment by wajnberg** [comment] 2021-06-22 11:51
Hello @laurenmrice @mattrosno and @joshblack 

We cannot resolve this problem just by adding css directives like `dir=rtl`.
Instead we should enclose each segment with `<bdi>` HTML element.
We have some code which achieves this.
Do you want me to share it with you ?

**Comment by joshblack** [comment] 2021-06-23 22:29
Totally agreed on above, I think these issues will fall under the discussion we've been having over in #7264

**Comment by tay1orjones** [comment] 2024-09-19 14:04
Duplicate of https://github.com/carbon-design-system/carbon/issues/7264

**Closed as completed by tay1orjones** 2024-09-19 14:04 UTC
Labels: type: enhancement 💡, proposal: open, type: bidi ↔️
