### ISSUE TITLE
[CodeSnippet] Does not change colors when theme is applied

### ISSUE THREAD

**Issue by electrostaticfleece** [carbon-design-system/carbon#4982] opened 2020-01-08 22:19 UTC
## What package(s) are you using?

- [X] `carbon-components`

## Detailed description
 

Not sure if this is a duplicate issue. Please feel free to close if so. Currently, the `CodeSnippet` component within the `carbon-components` background color does not change if you change the theme. Fro what I can tell this exists when using both CSS custom properties and without the custom properties flag applied.

Additionally, there looks to be an issue with the pseudo-element as well.

> Is this issue related to a specific component?

CodeSnippet

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When applying a theme I would expect the CodeSnippet component to reflect the applied theme.

> What browser are you working in?

Chrome (but this probably applies to all browsers)

> What version of the Carbon Design System are you using?

10.9.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud. We have a deadline of February 1st for Carbon 10 migration.

## Steps to reproduce the issue

You can see the issue here. It appears this only applies to single and multi-line components:
https://www.carbondesignsystem.com/components/code-snippet/code/

Picture as well: 

<img width="633" alt="Screen Shot 2020-01-08 at 4 18 08 PM" src="https://user-images.githubusercontent.com/16194732/72021009-a4089180-3232-11ea-9ef7-2506d7386a83.png">

**Comment by tw15egan** [comment] 2020-01-08 23:15
Hmm, interesting. When running the component locally and using custom-properties, the component switches accordingly when I use the theme switcher. @asudoh, any ideas on what might be different on the website vs locally?

**Comment by asudoh** [comment] 2020-01-08 23:20
@tw15egan Same finding here, can be seen at: https://the-carbon-components.netlify.com/?nav=code-snippet

It means that the problem is not likely to affect user applications. Though I don't have a good idea wrt website given theme switcher in website was introduced recently, here's some info that would help product team and website team to further debug it; The background color is dictated by [`$snippet-background-color`](https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/components/src/components/code-snippet/_mixins.scss#L15) which maps to [`$ui-01`](https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/components/src/globals/scss/_theme-tokens.scss#L190).

**Comment by electrostaticfleece** [comment] 2020-01-17 18:05
@tw15egan @asudoh I believe my issue occurred due to the import order of the theme. I was importing some of the other globals before the theme and it appears as though if the SASS variable is assigned to another variable (global or component-specific) then it wasn't getting reassigned when the theme was imported. This can likely be closed. it might be good to more explicitly state that the theme should be imported before all other components and global styles within the documentation. 

Currently there's a line within the code snippet, but it's pretty easy to miss / forget : https://www.carbondesignsystem.com/guidelines/themes/#default-theme

**Comment by tw15egan** [comment] 2020-01-17 20:35
Good note, import order would definitely cause this and I'm glad you've figured it out. I'm wondering if we could add the actual import instead of a comment that is easy to miss. I'll create an issue over on the website repo so they can take it under consideration, but I'm going to close this as resolved.

**Closed as completed by tw15egan** 2020-01-17 20:35 UTC
