### ISSUE TITLE
[StructuredList] Unable to navigate with keyboard

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon#2820] opened 2019-05-23 15:28 UTC
## Detailed description

In v9:
Tabbing through the list does not work at all.

In v10:
When trying to navigate the `<StructuredList>` component, I am unable to press the enter or space key to select the row item.

**Comment by dakahn** [comment] 2019-05-28 19:49
Hi 👋 Thanks for submitting and issue. I can confirm the lack of selection on keydown in v10 for enter using our example site, but could you provide the information requested in the template?

**Comment by emyarod** [comment] 2019-06-21 14:34
just to confirm is this just for v9 and v10 react only? vanilla v10 structured list should already have keyboard navigation https://github.com/carbon-design-system/carbon/pull/1427

**Comment by dhyliu** [comment] 2019-07-10 01:53
@emyarod According to @zgrossbart The issue was found in the product which is using carbon-components version 9.91.4 (this is a v9 version) and carbon-components-react version 6.115.5.

**Comment by emyarod** [comment] 2019-07-16 15:12
I see, yeah it looks like this has been a missing feature from the React component for a while and includes the current version as well. we will likely need to refactor this component to support keyboard navigation

**Comment by dhyliu** [comment] 2019-07-17 02:50
@emyarod when do you think there can be fix available for my accessibility tester to verify? Any target date for resolution? Please advise.

**Comment by emyarod** [comment] 2019-07-17 16:47
no ETA for a bugfix at the moment but the next Carbon release would be in August

**Comment by xubinnb** [comment] 2019-08-06 07:21
Hi @emyarod, any updates for this issue? We need a fix for v9, thanks.

**Comment by dakahn** [comment] 2019-08-09 20:36
Escalating this after confirmation that we have a AVT2 and AVT3 violation. Cannot make a selection in or out of screen reader.

**Comment by joshblack** [comment] 2021-06-01 21:38
Closed by https://github.com/carbon-design-system/carbon/pull/8172

**Closed as completed by joshblack** 2021-06-01 21:38 UTC
Labels: type: bug 🐛, severity: 1, type: a11y ♿
