### ISSUE TITLE
Tutorial links 404'ing

### ISSUE THREAD

**Issue by ecumike** [carbon-design-system/carbon#8089] opened 2021-03-15 15:57 UTC
All three tutorial links on this page are 404'ing:

https://www.carbondesignsystem.com/developing/get-started/

![image](https://user-images.githubusercontent.com/7328459/111182705-8bf27780-8585-11eb-9cb2-6fb81e0721ea.png)

**Comment by emyarod** [comment] 2021-03-15 16:06
duplicate of https://github.com/carbon-design-system/carbon-website/issues/2178

**Closed as completed by emyarod** 2021-03-15 16:06 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬

**Comment by ecumike** [comment] 2021-03-15 16:07
Woops, sorry.
