### ISSUE TITLE
IconDescription on Button is not displayed on MS Edge

### ISSUE THREAD

**Issue by wschue** [carbon-design-system/carbon#2522] opened 2019-03-05 09:17 UTC
IconDescription on Button is not displayed on MS Edge

IconDescription on Button is been displayed as tooltip on chrome and firefox but not on MS Edge
       
<Button
          small
          kind="ghost"
          **iconDescription={formatMessage(messages.downloadCsv)}**
          href={`/ibm/iis/dq/da/rest/v1/workspaces/${workspaceId}/dataSets/${datasetId}/dataClasses/selected?format=csv`}
          icon="icon--download"
          id="download.dataclasses.selected"
          key="button_download.dataclasses.selected">
</Button>

firefox:
![image](https://user-images.githubusercontent.com/39309641/53793610-84c41800-3f2e-11e9-95a5-f7bc0308678b.png)

MS Edge:
![image](https://user-images.githubusercontent.com/39309641/53794192-cbfed880-3f2f-11e9-863f-60b9587802c2.png)

**Comment by joshblack** [comment] 2019-12-06 17:31
Hi there! :wave: Looks like there hasn't been any activity in a while so I'm going to close this out. If you have a second to provide some steps to reproduce, we'd be happy to re-open and help out!

**Closed as completed by joshblack** 2019-12-06 17:31 UTC
Labels: severity: 3, type: bug 🐛, status: waiting for author's response 💬, package: react
