### ISSUE TITLE
!global no longer supported (sass)

### ISSUE THREAD

**Issue by theskillwithin** [carbon-design-system/carbon#8412] opened 2021-04-14 22:24 UTC
It looks like with dart sass !global is no longer supported

https://github.com/sass/dart-sass/blob/3d39f22cbff8097c212dd90a507c22dd808c3f19/CHANGELOG.md#1220

```
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Since this assignment is at the root of the stylesheet,
the !global flag is unnecessary and can safely be removed.
```

**Comment by emyarod** [comment] 2021-04-15 14:59
closing as duplicate of https://github.com/carbon-design-system/carbon/issues/8069

**Closed as completed by emyarod** 2021-04-15 14:59 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
