### ISSUE TITLE
[Bug]: Events are incorrect on FileUploaderDropContainer

### ISSUE THREAD

**Issue by ajbeach2** [carbon-design-system/carbon#13663] opened 2023-04-25 19:58 UTC
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v11.27.0

### Description

The on drop even passes the div as the event target. which causes an issue with the onAddFiles since the files cannot be gotten from this div. 

https://github.com/carbon-design-system/carbon/blob/47966b102beb1310c23bb0fc914a22f639dc08d6/packages/react/src/components/FileUploader/FileUploaderDropContainer.js#L119

The on drop event target is a div, so OnAddFiles call back fails.

<img width="1068" alt="Screenshot 2023-04-25 at 3 45 28 PM" src="https://user-images.githubusercontent.com/1581726/234386465-8182656b-ea0c-4ce5-a491-d0e1e9012c40.png">

This causes an error in the OnAddFiles, since a div will not have files.

If you click on the FileUploader, the Input is the event target, and the OnAddFiles callback can access the files
<img width="929" alt="Screenshot 2023-04-25 at 3 54 08 PM" src="https://user-images.githubusercontent.com/1581726/234388200-4e2120ef-5b97-4883-8aed-6258cbb6d4aa.png">

### Reproduction/example

N/A

### Steps to reproduce

Drag and drop files and it does not work

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-07-06 19:01
Closing due to lack of reproduction

**Closed as completed by tay1orjones** 2023-07-06 19:01 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:, status: needs reproduction
