### ISSUE TITLE
ComboBox should have selectedItem option

### ISSUE THREAD

**Issue by eglepuo** [carbon-design-system/carbon#4300] opened 2019-10-11 10:25 UTC
### Summary

Combobox component should have prop selectedItem as Dropdown has.

### Justification

It's not possible to use selected value not from ComboBox dropdown. 

### "Must have" functionality

Combobox has selectedItem prop.

**Comment by emyarod** [comment] 2019-10-11 13:35
closing as a duplicate of https://github.com/carbon-design-system/carbon/issues/4045

**Closed as completed by emyarod** 2019-10-11 13:35 UTC
Labels: type: enhancement 💡
