### ISSUE TITLE
[Bug]: The overflow menu item is truncated automatically when the text length is more

### ISSUE THREAD

**Issue by ratheesh-kumar-nv** [carbon-design-system/carbon#11877] opened 2022-07-28 17:58 UTC
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

10.50

### React version

17.0.2

### Description

The overflow menu item text is truncated automatically when the text is some what larger text. See image below
![image](https://user-images.githubusercontent.com/91602127/181603809-3874150f-e4c7-4fac-8477-684edbf0b490.png)

Please let me know is there a fix/workaround for this as we wont be able to upgrade the carbon component version now. Thanks

### Reproduction/example

https://codesandbox.io/s/flamboyant-mccarthy-wi9f66?file=/src/index.js

### Steps to reproduce

1. Add overmenu component
2. Add an item with a bigger text

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment] 2022-07-28 20:38
Hey @ratheesh-kumar-nv! The text truncating is intended for when the text is longer than what is displayed, what are you hoping for it to do instead?

**Comment by ratheesh-kumar-nv** [comment] 2022-07-29 02:27
@abbeyhrt As a user I would expect to control the width of the popup and keep the text not truncated. Is there a way that can be done? Could you please explain me the truncation logic? after some number of characters?
And I guess as per Carbon standards, these are expected behaviours in carbon applications

**Comment by tay1orjones** [comment] 2022-08-08 15:29
@ratheesh-kumar-nv Yes, the overflow menu items have a default width of `10rem` specified. This can be overridden with css on the `.cds--overflow-menu-options` class.

The truncation is done via css and is automatically bound by the width of the element. Closing this as intended, but let us know if there's anything else we can help with

**Closed as completed by tay1orjones** 2022-08-08 15:29 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
