### ISSUE TITLE
Data Table Overflow Issue

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5497] opened 2020-03-02 00:54 UTC
If you go to the storybook and take a look at the dynamic content example for the data table, you'll see that after adding multiple columns, the table completely disregards overflow:

https://react.carbondesignsystem.com/?path=/story/datatable--with-dynamic-content

![image](https://user-images.githubusercontent.com/11995299/75637708-145dde80-5bf6-11ea-83f1-cb008449b36d.png)

In my ideal world, there is no wrap and no truncation. Each cell takes up as much space as is needed to fit the contents in a single line, even if that means overflow. When the table overflows like this it shouldn't extend beyond the frame of it's container and there should be a scrollbar. Is there anything I can do to fix this.

**Comment by tw15egan** [comment] 2020-03-13 15:40
Closing as duplicate of https://github.com/carbon-design-system/carbon/issues/4998

**Closed as completed by tw15egan** 2020-03-13 15:40 UTC
Labels: type: bug 🐛
