### ISSUE TITLE
[Modal]: Use of selectorPrimaryFocus makes secondary button require a double click

### ISSUE THREAD

**Issue by JohnWColby** [carbon-design-system/carbon#9470] opened 2021-08-11 18:39 UTC
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

We have recently been updating to the latest Carbon package versions, and it broke some of our integration tests. Upon investigation, we found that some of our Modals now require double clicking the secondary button before its event is triggered. Upon further testing, it seems to be a focus related issue related to using `selectorPrimaryFocus`. When this property is removed, the secondary click works as expected (triggers event on the first click).

Our updates are as follows:
carbon-components: 10.23.2 => 10.40.2
carbon-components-react: 7.23.2 => 7.40.2

## Steps to reproduce the issue

I'm not sure how to reproduce this-- I've only seen it in our application.

## Additional information
Screen recording: 
[Modal bug.mov.zip](https://github.com/carbon-design-system/carbon/files/6970661/Modal.bug.mov.zip)

**Comment by ColbyJohnIBM** [comment] 2021-08-11 19:30
This did not end up being the cause of our issue (although I haven't determined the true cause yet). Closing this.

**Closed as completed by ColbyJohnIBM** 2021-08-11 19:30 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬
