### ISSUE TITLE
[Bug]: DatePicker range selection has confusing behavior

### ISSUE THREAD

**Issue by LauKwaiFanHK** [carbon-design-system/carbon#11304] opened 2022-04-28 07:11 UTC
### Package

carbon-components-react

### Package version

v11, v10

### Description

Hello, The Carbon range datepicker does not function correctly when I select another range after a date range has been selected. When I select another start date, the reselected start date would becomes the end date, and the previous end date becomes the start date. This error occurs also on Carbon storybook.

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

This error occurs already in Carbon Components React Storybook. Just go to the above link and pick a date range on the range datepicker. Then try to choose / reselect a new date range by clicking the start date. Starting from here you will see the problem.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by aagonzales** [comment] 2022-04-28 15:25
What AirBnB does: if you are focused on the end date and then select a date (for the end date) that is before the start date, then the end date clears and the earliest date selected becomes the start date.

![Apr-28-2022 10-22-41](https://user-images.githubusercontent.com/11670886/165787894-4c5bab2b-b007-4259-9ae8-e6d4cd8ac47f.gif)

**Comment by tay1orjones** [comment] 2022-04-28 16:25
Conversely, here's how that same selection of dates happens in ours:


https://user-images.githubusercontent.com/3360588/165798790-972070d1-626b-40a3-9176-ea42dd0a7c43.mov



The big difference I'm seeing is that theirs keeps the calendar open for the entire interaction and discreetly indicates/changes focus on the start and end dates inputs during the interaction.

Ours closes the calendar after selection of the second (end) date. Selecting a new start date does not remove the end date like the AirBnb example.

**Comment by tay1orjones** [comment] 2022-04-28 16:28
Here's a crisp example of the invalid behavior @LauKwaiFanHK describes:


https://user-images.githubusercontent.com/3360588/165800031-7c92465b-bdc0-402e-b5e8-829f7fe09f47.mov

One additional piece to note - at the end I select the end date input and the entire thing resets to the same start and end date. I doubt that's the intended behavior?

**Comment by tay1orjones** [comment] 2022-04-28 16:42
@aagonzales Is this also a duplicate of https://github.com/carbon-design-system/carbon/issues/4476?

**Comment by aagonzales** [comment] 2022-04-29 19:32
I'm not sure is a duplicate but it is related. I think 4476 is about the focus changing back to the start date when you close the calendar instead of it staying on the end date.

**Comment by abbeyhrt** [comment] 2022-06-16 20:48
To resolve this, we've added a new prop `closeOnSelect` that allows users to keep the calendar dropdowns open while users are choosing dates. We highlighted this as the main difference between Airbnb's DatePicker and ours and have decided to follow their strategy.

**Comment by abbeyhrt** [comment] 2022-06-24 20:46
Closing this for now due to a lack of response, feel free to message us to get it re-opened if necessary!

**Closed as completed by abbeyhrt** 2022-06-24 20:46 UTC
Labels: type: bug 🐛, severity: 2
