### ISSUE TITLE
[Question]: Carbon React Components that are not client components? Next.js server-side rendering by default

### ISSUE THREAD

**Issue by RapTho** [carbon-design-system/carbon#15967] opened 2024-03-14 19:30 UTC
### Question for Carbon

I'd love to use the Carbon React components for my Next.js 14 project but I'd have to make every component a client component with "use client".

This would make Next.js's great feature of using server-side rendering by default impossible. Is there a way of using the Carbon React components without making everything a client component?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2024-03-15 18:27
Duplicate of #14458

**Closed as not planned by tay1orjones** 2024-03-15 18:27 UTC
Labels: type: question ❓
