### ISSUE TITLE
get warning when using reference ref on Button React component

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon#6191] opened 2020-06-03 16:58 UTC
## What package(s) are you using?
Carbon-components-react

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
I have a typescript containing <Button> component. when I use the ref on Button, I get following error:

![image](https://user-images.githubusercontent.com/14806866/83665542-2ce0ea80-a591-11ea-9716-4f6d638d975f.png)

here is code snippet:
![image](https://user-images.githubusercontent.com/14806866/83665625-4a15b900-a591-11ea-8ee3-5f1169035d6a.png)

The code in fact is working, only see the error in build log

**Comment by tw15egan** [comment] 2020-06-03 18:17
We don't maintain any type definitions in the repo, perhaps the issue should be raised here? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon-components-react

**Comment by joshblack** [comment] 2020-06-03 19:44
To @tw15egan's comment, responded similarly over in Slack: https://ibm.biz/BdqarE

> Unfortunately, the types for the components are community-driven so this is something that might need to be fixed upstream on DefinitelyTyped.

Going to go ahead and close this one out since the issue is for the TypeScript types which are community maintained 👍

**Closed as completed by joshblack** 2020-06-03 19:44 UTC
Labels: type: bug 🐛
