### ISSUE TITLE
[Bug]: Vertical progress indicator: Text is misaligned when space is limited

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#9611] opened 2021-09-07 08:15 UTC
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

10.43.0/7.43.0

### Description

When using a vertical progress indicator, the step labels start to misalign when horizontal space is limited.

![image](https://user-images.githubusercontent.com/28265588/132309313-f72be9c3-3ada-4522-90e4-6c26f72e9e72.png)

I'd expect the text to wrap and still align with the rest of the step labels.

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-progressindicator--default

### Steps to reproduce

1. Visit the carbon react storybook
2. Enable the "vertical" option in the knobs
3. Reduce the width of the story until the text misaligns

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment] 2021-09-07 15:55
@janhassel I think this is a duplicate of https://github.com/carbon-design-system/carbon/issues/9261 so will track over in there 👍

**Closed as completed by joshblack** 2021-09-07 15:55 UTC
Labels: type: bug 🐛, package: components, component: progress-indicator
