### ISSUE TITLE
[Bug]: NumberInput : Unable to clear number input textboxes they are defaulted to 0

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/carbon#16016] opened 2024-03-20 14:40 UTC
### Package

@carbon/react

### Browser

Chrome, Safari

### Package version

 "@carbon/react": "1.53.0",

### React version

 "react": "17.0.2",

### Description

- Render the NumperInput component from carbon/react.
- By default, 0 is been assigned to the field.
- Try to clear and add a new value . This would not clear the value 0 instead append the newly added value to 0.
- Though allowEmpty prop is been set to true. The NumberInput field is never cleared.

### Reproduction/example

https://codesandbox.io/p/sandbox/numberinput-9587cm?file=%2Fsrc%2FApp.js%3A7%2C41

### Steps to reproduce

Render the NumperInput component from carbon/react.
- By default, 0 is been assigned to the field.
- Try to clear and add a new value . This would not clear the value 0 instead append the newly added value to 0.
- Though allowEmpty prop is been set to true. The NumberInput field is never cleared.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by ecrvich** [comment] 2024-03-20 17:13
See also #15985 which basically covers the same problem.

**Comment by tw15egan** [comment] 2024-03-21 14:48
CLosing as a dupe of #15985

**Closed as completed by tw15egan** 2024-03-21 14:48 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬
