### ISSUE TITLE
[Bug]: DatePicker: Cannot select date range using keyboard

### ISSUE THREAD

**Issue by makafsal** [carbon-design-system/carbon#17310] opened 2024-09-02 11:33 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.65.0

### React version

v18.2.0

### Description

When trying to select a date range using the keyboard it loses focus after selecting an initial date by pressing the 'Enter' key.

https://github.com/user-attachments/assets/300c66e4-bacd-4f4d-931f-1b2839e825d3

### Reproduction/example

https://stackblitz.com/edit/github-bmgxxb-ds4ysm?file=src%2FApp.jsx

### Steps to reproduce

1. Press the `Tab` key and focus on the `DatePicker` (calendar will appear)
2. Press the `Down Arrow`, focus date
3. Press the `Enter` key to select the focused date (We can observe that the focus is lost from Calendar)

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by Kritvi-bhatia17** [comment] 2024-09-04 07:07
Hi @makafsal, I can see the focus state on the start date after selecting it. I've added a screenshot and screen recording for reference. Could you please confirm if you're encountering the issue you've mentioned in the 'Date picker range with calendar' or in another variant?
 

https://github.com/user-attachments/assets/888b9619-997f-45be-a5b2-c7824d8049f0

<img width="304" alt="Screenshot 2024-09-04 at 12 36 38 PM" src="https://github.com/user-attachments/assets/1f15d0b5-32d2-4499-a1ed-72ea32d48d13">

**Comment by makafsal** [comment] 2024-09-09 11:58
Hi @Kritvi-bhatia17, Thank you for your response. I figured out that the issue pops up when I give the `value` property for the `DatePicker` and `DatePickerInput` components. Could you please confirm that I need to give the `value` property?

**Comment by Kritvi-bhatia17** [comment] 2024-09-10 05:39
Hi @makafsal! @carbon-design-system/developers will help us with that.

**Comment by Kritvi-bhatia17** [comment] 2024-09-10 14:34
Hi @Geethkadali! Thanks for opening the issue. @carbon-design-system/developers will look into it.

**Comment by Kritvi-bhatia17** [comment] 2024-09-16 07:38
Hi @makafsal, just an update on this issue—it has been resolved in PR #17435.

**Comment by makafsal** [comment] 2024-10-28 08:15
@Kritvi-bhatia17 - I think you don't need any more info from my end so that you can remove the `waiting for author's response` label.

**Comment by 2nikhiltom** [comment] 2024-11-06 09:50
Hey @makafsal 

> Press the Tab key and focus on the DatePicker (calendar will appear)
> Press the Down Arrow, focus date
> Press the Enter key to select the focused date (We can observe that the focus is lost from Calendar)

after selecting the start date (start date remains focused ) and when you select the end date the calendar collapse and focus moved back to the triggering element i.e (start input date) and the range is selected
I confirmed same behavior on the shared stackblitz and the reactstorybook 

Could you expand more on the the issue/required behavior ?

**Comment by 2nikhiltom** [comment] 2024-11-11 10:25
Closing this since it is the expected behaviour of focus - happy to reopen with more details

**Closed as completed by 2nikhiltom** 2024-11-11 10:25 UTC
Labels: status: waiting for author's response 💬, type: discussion 💬, component: date-picker
