### ISSUE TITLE
[Bug]: @carbon/react does not work with nx-workspace library

### ISSUE THREAD

**Issue by fahadahmed** [carbon-design-system/carbon#13524] opened 2023-04-13 19:41 UTC
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v1.26.0

### React version

v18.2.0

## Issue

When trying to use `@carbon/react` npm package within an nx-workspace library, importing any component like a Button results in an error: `Invalid hook call. Hooks can only be called inside of the body of a function component.`

<img width="1680" alt="Screenshot 2023-04-14 at 5 22 28 am" src="https://user-images.githubusercontent.com/1190340/231863026-9f549d5b-61fc-463f-a2ed-2fdeda5fade8.png">

### Reproduction/example

Unable to create an nx workspace either on CodeSandbox or Stackblitz

### Steps

- create a new nx workspace
- create a new nx library using `@nrwl/react`
- create a new UI component like a Button
- install storybook to generate stories for the Button component
- add `@carbon/react` to the nx library
- import any component like `Button` from the carbon react package
- import the library component to the nx workspace app

The build fails with the following error:

<img width="1680" alt="Screenshot 2023-04-14 at 5 22 28 am" src="https://user-images.githubusercontent.com/1190340/231863026-9f549d5b-61fc-463f-a2ed-2fdeda5fade8.png">

`@carbon/react` needs to be able to support the latest React version and be compatible with build tools like [nx](https://nx.dev/) to effectively build enterprise system using the Carbon Design System.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

Space Technologies Platform

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-04-17 15:05
Duplicate of https://github.com/carbon-design-system/carbon/issues/13531

**Closed as not planned by tay1orjones** 2023-04-17 15:05 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
