### ISSUE TITLE
[Bug]: Treeview - TreeNode with Tooltip

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon#14023] opened 2023-06-16 19:47 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

1.31.3

### React version

18.2.0

### Description

From Slack: https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1686939455012339
This is a bug/question. When trying to render a Treenode with a renderIcon that has a Tooltip, the tooltip does not show up on hover. 
Would expect the tooltip to show up, unless this is intended and we don't support tooltips inside treenodes?

### Reproduction/example

https://codesandbox.io/s/wizardly-silence-tqfcn4?file=/index.js

### Steps to reproduce

1. Click on reproduction example
2. Hover over "Business Operations" checkmark icon
3. Notice no tooltip shows up

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tongyy** [comment] 2023-06-20 04:29
this is a tooltip issue. 
this piece of code needs to be reviewed. why if it not interactiveContent and close the tooltip.

 ```
 useEffect(() => {
    if (containerRef !== null && containerRef.current) {
      const interactiveContent = getInteractiveContent(
        containerRef.current as HTMLElement
      );
      if (!interactiveContent) {
        setOpen(false);
      }
    }
  });
```
getInteractiveContent check if it has the following types of node. this means the tooltip only supports these types. I don't see docs mention this limitation.
```
switch (element.nodeName) {
    case 'A':
      return !!element.href && element.rel !== 'ignore';
    case 'INPUT':
      return element.type !== 'hidden';
    case 'BUTTON':
    case 'SELECT':
    case 'TEXTAREA':
      return true;
    default:
      return false;
  }
```

and here's the workround use button to wrapp the icon.

https://codesandbox.io/s/tender-goldwasser-mwrhll

```
      <TreeNode
        key="4"
        id="4"
        renderIcon={() => (
          <Tooltip label="tooltip">
            <button style={{ border: "none", marginTop: "4px" }}>
              <CheckmarkOutline />
            </button>
          </Tooltip>
        )}
        value="Business operations"
        label="Business operations"
      />
```

**Comment by preetibansalui** [comment] 2024-03-25 13:00
Not able to reproduce the issue, given codesandbox link is also working fine to me. Please check the attached screenshot. It might be fixed with the PR [15535](https://github.com/carbon-design-system/carbon/pull/15535)
<img width="1438" alt="image" src="https://github.com/carbon-design-system/carbon/assets/146315451/c06a76b8-1528-4848-a658-30099f3ce918">

**Closed as completed by preetibansalui** 2024-03-25 13:00 UTC
Labels: type: bug 🐛, severity: 2, role: dev 🤖, component: tooltip
