### ISSUE TITLE
[Bug]: When scrolling while the focus is on Number input, value changes and page scrolls

### ISSUE THREAD

**Issue by Natuu** [carbon-design-system/carbon#11947] opened 2022-08-12 09:20 UTC
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

10.57.2 (and v11 too as it's still same behavior in doc)

### React version

17.0.2

### Description

 When scrolling while the focus is on Number input, value changes and page scrolls.
 You can see this in the docs too (https://carbondesignsystem.com/components/number-input/usage/).
 
It seems logic that the value changes for accessibility reasons or design reasons. However, the page should not scroll at the same time as it harder to see that the value changes. When using a mouse pad, user can even miss that the input has focus, and change the value without knowing.

### Reproduction/example

https://carbondesignsystem.com/components/number-input/usage/

### Steps to reproduce

 - Click on the input
 - Scroll down / up

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2022-08-29 15:25
Duplicate of https://github.com/carbon-design-system/carbon/issues/11982

**Comment by tay1orjones** [comment] 2022-08-29 15:26
I'm going to close this as a solution to the issue has been proposed and agreed upon in #11982

**Closed as not planned by tay1orjones** 2022-08-29 15:26 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, component: number-input, status: needs triage :female_detective:
