### ISSUE TITLE
If I set a className for max width on TextInput the invalid wrapper extends past it

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#5208] opened 2020-01-29 18:42 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
I used the className prop of the TextInput to set a maxWidth on the input field for certain TextInput types.  It works! Unfortunately if the TextInput is invalid, the wrapper class highlights extend way beyond the max width of the Text Input.  Can we also send the className prop along on the wrapper, or give a separate wrapper class prop that we can override?

> Is this issue related to a specific component?
TextInput

## Additional information
![image](https://user-images.githubusercontent.com/6663002/73386538-9e7ff380-4294-11ea-9348-3ce31551a41a.png)

**Comment by emyarod** [comment] 2020-01-29 19:10
would you mind creating a reduced test case in Code Sandbox for easier testing and debugging?

**Comment by scottdickerson** [comment] 2020-01-31 13:25
sure no problem:
https://codesandbox.io/s/textinput-example-47zv7 @emyarod

**Comment by tw15egan** [comment] 2020-01-31 19:47
Confirmed. Seems like this is solved by passing the class down the wrapper instead of the input itself. Seems like this would be considered a breaking change since some users could be sending down a class they want to send to the `input`, so we may need to add a new prop to allow adding classes to the wrapper.

**Comment by emyarod** [comment] 2020-02-11 15:51
since the wrapper element is still modifiable with an alternate selector I think that would be the workaround in this case. not sure if there's a definite fix for this

**Comment by tw15egan** [comment] 2020-02-11 16:01
I can take this and add a new prop that allows wrapper class to be set

**Closed as completed** 2022-11-14 16:30 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬
