### ISSUE TITLE
[React Modal] carry over a11y updates from Vanilla

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3816] opened 2019-08-23 19:01 UTC
changes were made to modal for keyboard users that need carried over to react: 

https://github.com/carbon-design-system/carbon/pull/3650

**Comment by abbeyhrt** [comment] 2019-09-09 15:43
Closing this issue as it is a duplicate of #3261

**Closed as completed by abbeyhrt** 2019-09-09 15:43 UTC
Labels: type: a11y ♿, package: react
