### ISSUE TITLE
carbon-components.min.css and carbon-components.min.js not found 

### ISSUE THREAD

**Issue by rogeliotrejo13** [carbon-design-system/carbon#11137] opened 2022-04-04 15:02 UTC
### Package

carbon-components

### Package version

11.0.0

### Automated testing tool and ruleset

not needed  

### Description

https://unpkg.com/carbon-components/scripts/carbon-components.min.js
https://unpkg.com/carbon-components/css/carbon-components.min.css 

### CodeSandbox example

not needed

### Steps to reproduce

open unpkg.com links, files not found 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by rogeliotrejo13** [comment] 2022-04-04 15:05
official links from .min.js and min.css on docs 
https://www.carbondesignsystem.com/developing/frameworks/vanilla/

**Comment by tay1orjones** [comment] 2022-04-04 15:07
@rogeliotrejo13 Thanks for reporting this, if you're looking for the v10 versions of this file, you'll need to use a versioned url like `https://unpkg.com/carbon-components@10.56.0/css/carbon-components.min.css`

**Comment by rogeliotrejo13** [comment] 2022-04-04 15:27
Hi @tay1orjones  what about .js file? 
Thanks a lot

**Comment by tay1orjones** [comment] 2022-04-04 15:51
Duplicate of https://github.com/carbon-design-system/carbon/issues/11137

**Closed as completed by tay1orjones** 2022-04-04 15:51 UTC
Labels: status: waiting for author's response 💬, status: needs triage :female_detective:

**Comment by rogeliotrejo13** [comment] 2022-04-04 16:06
@tay1orjones  marked as duplicated an linked to this one  11137 (same one), 
what is the other one? to follow up

**Comment by tay1orjones** [comment] 2022-04-04 16:32
Ah, sorry! Wrong issue number. 

Duplicate of https://github.com/carbon-design-system/carbon/issues/11129
