### ISSUE TITLE
Allow setting default locale for DatePicker

### ISSUE THREAD

**Issue by fred104** [carbon-design-system/carbon#9248] opened 2021-07-22 08:02 UTC
### Summary

Is it possible to set default locale for `DatePicker`? Then we don't need to pass `locale` to each `DatePicker` component.

### Justification

No.

### Desired UX and success metrics

Probably we can add a function to set default locale?
```js
import { DatePicker } from "carbon-components-react";

DatePicker.setDefaultLocale("zh_tw");
```

### "Must have" functionality

Set default locale for `DatePicker`

### Specific timeline issues / requests

We have a GVT defect in our backlog. It's up to this ticket to decide whether we should directly fix this defect by adding `locale` prop to each `DatePicker`.

### Available extra resources

What resources do you have to assist this effort?

I guess we probably can discuss the better way to do this. If needed, I can create a PR for it.

**Comment by tay1orjones** [comment] 2021-08-02 16:13
@fred104 Could you elaborate on why this is a requirement for your project? The general intent of having a `locale` prop on `DatePicker` is so that you can pass a locale to each `DatePicker` individually.

**Comment by jnm2377** [comment] 2021-08-02 16:13
It looks like we already have a default locale for our DatePicker component. https://github.com/carbon-design-system/carbon/blob/f33d65cf473a27a6ce1b450fae379f560bb4a2fd/packages/react/src/components/DatePicker/DatePicker.js#L293 Is this what you were referring to?

**Comment by fred104** [comment] 2021-08-09 03:28
@tay1orjones In our current project, we have a place to handle globalization and localization related stuffs. If we can have global setting for `DatePicker`, that would be very useful. Developers don't need to take care of that and we can reduce defect numbers.

**Comment by tay1orjones** [comment] 2021-09-09 19:20
Hi @fred104 sorry for the delay in responding. If I understand correctly, you'd like to set a new default locale for all DatePickers in your application.

If this is the case, I'd recommend creating a lightweight wrapper around DatePicker that would set the locale to your preferred locale. You can then reuse this wrapper throughout your application in place of DatePicker. Something like this might work:

```js
import { DatePicker as CarbonDatePicker } from "carbon-components-react";

export function DatePicker(props) {
  return (
    // `fr` is used here, but can be whatever locale you'd like the new "default" to be
    <CarbonDatePicker locale={props?.locale || "fr"} {...props}>
      {props?.children}
    </CarbonDatePicker>
  );
};
```

[Here's a quick codesandbox example](https://codesandbox.io/s/frosty-curie-mvr88?file=/src/index.js) I cooked up.

**Comment by jnm2377** [comment] 2021-09-09 19:49
Closing this issue, since this is not a bug and no enhancement is needed. For anyone else wanting to do a similar thing, we've provided the recommended solution above for setting the same prop value to more than one component without having to explicitly add the prop to each component instance (see https://github.com/carbon-design-system/carbon/issues/9248#issuecomment-916371174)

**Closed as completed by jnm2377** 2021-09-09 19:49 UTC
Labels: type: enhancement 💡, status: waiting for author's response 💬, status: needs triage :female_detective:
