### ISSUE TITLE
Migrate off CRA: Determine which examples we should remove, and remove them

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#14599] opened 2023-09-07 16:29 UTC

**Comment by alisonjoseph** [comment] 2023-09-18 18:36
## Examples

- `/examples/class-prefix`

  - using vite ✅
  - runs on stackblitz ✅

- `/examples/codesandbox`

  - using vite/nextjs ❌

- `/examples/codesandbox-styles`

  - using vite ✅
  - runs on stackblitz ✅

- `/examples/codesandbox-with-sass-compilation`

  - using vite ✅
  - runs on stackblitz ❌

- `/examples/custom-theme`

  - using vite ✅
  - runs on stackblitz ✅

- `/examples/id-prefix`

  - using vite ✅
  - runs on stackblitz ✅

- `/examples/incremental-migration`

  - using vite/nextjs ❌
  - [ ] **Remove** 🗑️

- `/examples/incremental-migration-vite`

  - using vite ✅
  - runs on stackblitz ❌

- `/examples/light-dark-mode`

  - using nextjs ✅
  - runs on stackblitz ❌

- `/examples/nextjs`

  - using nextjs ✅
  - runs on stackblitz ✅

- `/examples/v10-token-compat-in-v11`

  - using vite ✅
  - runs on stackblitz ✅

- `/examples/vite`

  - using vite ✅
  - runs on stackblitz ✅

- `/packages/icons-vue/examples/vue-cli`

  - not on CRA ✅
  - runs on stackblitz ❌

- `/packages/react/examples/codesandbox`

  - duplicate of `examples/codesandbox`
  - [ ] **Remove** 🗑️

- `/packages/react/examples/create-react-app`

  - [ ] **Remove** 🗑️

- `/packages/react/examples/custom-css-prefix`

  - duplicate of `examples/custom-css-prefix`
  - [ ] **Remove** 🗑️

- `/packages/react/examples/custom-data-table-state-manager`

  - not on CRA ✅
  - runs on stackblitz ❌

- `/packages/react/examples/drag-and-drop-file-uploader`

  - not on CRA ✅
  - runs on stackblitz ❌

- `/packages/react/examples/next`

  - duplicate of `examples/nextjs`
  - [ ] **Remove** 🗑️

- `/packages/react/examples/react-router`

  - broken example ❌

- `/packages/colors/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/colors/examples/sass-modules`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/grid/examples/css-grid`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/grid/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/icons/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/layout/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/pictograms/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/themes/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/themes/examples/preview-v10`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/themes/examples/sass-modules`

  - using nextjs ✅
  - runs on stackblitz ❌

- `packages/type/examples/preview`

  - using nextjs ✅
  - runs on stackblitz ❌

**Closed as completed** 2023-09-19 15:34 UTC
Labels: role: dev 🤖, package: react
