### ISSUE TITLE
Disabled input on flatpickr calendar does not respect selected theme

### ISSUE THREAD

**Issue by Donisius** [carbon-design-system/carbon#6249] opened 2020-06-10 21:30 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Using the range date picker with the g100 theme causes the year input to blend in with the background of the calendar if it is disabled (through setting min and max date).

> Is this issue related to a specific component?

Datepicker

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The year input should be visible if it is disabled.

> What version of the Carbon Design System are you using?

"carbon-components": "10.11.2",

## Steps to reproduce the issue

1. https://carbon-components-react.netlify.app/?path=/story/datepicker--range-with-calendar and pick g100 theme
2. add `disabled` attribute on the input of the year within the flatpickr calendar

input to add disabled on:
<img width="253" alt="Screen Shot 2020-06-10 at 5 28 26 PM" src="https://user-images.githubusercontent.com/45505172/84320560-ddc22900-ab3f-11ea-9684-c4c3fb7f2c8b.png">

Alternatively you can set a min and max date through flatpickr options which also disables the year.

## Additional information

What it looks like with a disabled year input:
<img width="311" alt="Screen Shot 2020-06-10 at 5 27 22 PM" src="https://user-images.githubusercontent.com/45505172/84320642-ffbbab80-ab3f-11ea-8492-5ca44e6a292f.png">

**Comment by emyarod** [comment] 2020-06-11 13:47
This is a duplicate of #6231 and will be addressed in #6248

**Closed as completed by emyarod** 2020-06-11 13:47 UTC
Labels: type: bug 🐛
