### ISSUE TITLE
[Feature Request]: Allow option for expandable tile to only be toggleded from carrot

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/carbon#10218] opened 2021-12-02 23:49 UTC
### Summary

APIC is using the expandable tile component to show API information-

<img width="1496" alt="Screen Shot 2021-12-02 at 5 46 31 PM" src="https://user-images.githubusercontent.com/6370760/144520761-82141b39-06f8-49b6-ae5c-0f085e513573.png">

design likes being able to open and close the tile, but would like the option to have it so the entire tile isn't clickable and only toggle the open and close from the carrot on the bottom right of the tile. here's a mock of what they're thinking-

![062b5300-c87a-11eb-89a0-a0ff38a572be](https://user-images.githubusercontent.com/6370760/144520890-b58968a4-c38d-4ac8-81a5-44209b71421d.png)

### Available extra resources

I can open up a PR to address this

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2021-12-03 16:36
Hi @davidmenendez, great suggestion! This actually came up recently https://github.com/carbon-design-system/carbon/issues/9442#issuecomment-957736325. I think you're knocking on the same thing in this request. If you agree we can close this as a duplicate of #9442

**Comment by davidmenendez** [comment] 2021-12-03 20:42
@tay1orjones yes i think we can close this and i'll head over to that issue 👍 

thanks for the follow up

**Comment by davidmenendez** [comment] 2021-12-03 21:24
link to original issue https://github.ibm.com/velox/ui/issues/25591

**Comment by tay1orjones** [comment] 2021-12-03 21:48
Duplicate of #9442

**Closed as completed by tay1orjones** 2021-12-03 21:48 UTC
Labels: type: enhancement 💡, status: waiting for author's response 💬, status: needs triage :female_detective:
