### ISSUE TITLE
[Bug]: Build w/ Vite.js causes _all_ of @carbon/icons-react to be bundled

### ISSUE THREAD

**Issue by jhpedemonte** [carbon-design-system/carbon#13865] opened 2023-05-23 18:51 UTC
### Package

carbon-components, carbon-components-react, @carbon/icons, @carbon/icons-react

### Package version

10.46.0

### React version

17

### Description

I'm migrating an app from `create-react-app` to `vite`. When analyzing the built chunks, I noticed that *all* of `@carbon/icons-react` (>4.5MB) was being bundled. I expect that only the icons I'm using will actually make it into the built bundle.

Here's what `source-map-explorer` shows:
![Screenshot 2023-05-22 at 9 24 06 AM](https://github.com/carbon-design-system/carbon/assets/711365/95bd9bb9-d79a-4146-9c62-ea859f8496e3)

### Reproduction/example

(see below)

### Steps to reproduce

I have a branch within IBM. I can make access available to other IBMer to check it out. Within that branch:
1. Build: `NODE_OPTIONS=--max-old-space-size=14336 yarn build`
2. Analyze the built chunks: `yarn analyze`

### Suggested Severity

None

### Application/PAL

Watson Discovery

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-05-23 18:59
@jhpedemonte Thanks for opening this! What version of Vite are you using?

It'd be great to get a simple reproduction going in a stackblitz and/or something locally that uses Vite like our [bug repro template](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx), and confirm with `rollup-plugin-visualizer` or [vite-bundle-visualizer] (https://www.npmjs.com/package/vite-bundle-visualizer)(which uses `rollup-plugin-visualizer`)

**Comment by jhpedemonte** [comment] 2023-05-30 22:50
I tried to recreate this with a minimal test:
1. Start with bare Typescript-based create-react-app
2. Add an icon from `@carbon/icons-react` to the app
3. Remove `react-scripts` (CRA) and replace with Vite

However, builds only pull in the necessary parts, not the entire `@carbon/icons-react`. I downgraded to the versions of React (v17) and carbon (v10) that I'm using in my main app, but same results.

So something else I'm not accounting for is causing all of `@carbon/icons-react` to be built into my app. Any ideas on what I should look for?

**Comment by tay1orjones** [comment] 2023-06-08 19:23
@jdharvey-ibm @tw15egan and I spent some time this afternoon and we're not able to reproduce it either. 

Some thoughts or things to try:
- Double check dependency versions, including transients. Maybe something is out of date in your toolchain? Maybe rollup or a plugin or something isn't resolving to the proper version for Vite? That could be part of why it works in a new app, all the dependency versions are probably at latest.
- Could it be something like `import * from '@carbon/icons-react'` or a similar errant import statement bringing everything in? In our tests we did notice a difference in behavior between Vite and CRA when you have a sweeping import like this. Tree shaking with webpack/CRA was more aggressive and the overall bundle was smaller.
- It's unlikely but technically possible to only be using ~31 icons but if each is in a different bucket, all buckets would be included. This seems unlikely though since you observed different/correct tree shaking behavior with react-scripts.
- Something else you could try would be forcing Vite to tree shake with esbuild via the [`optimizeDeps.esbuildOptions`](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-esbuildoptions) option. You could try including [`tree-shaking: true`](https://esbuild.github.io/api/#tree-shaking) in there to force tree shaking. I think this might only be in dev though, since `vite build` uses `@rollup/plugin-commonjs`

**Closed as completed** 2023-06-09 14:49 UTC
Labels: type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬, status: needs reproduction
