### ISSUE TITLE
Dropdown and select chevron in dark themes (g80, g90, g100) is black on Safari iOS and iPhone

### ISSUE THREAD

**Issue by weaseldotro** [carbon-design-system/carbon#9145] opened 2021-07-08 16:00 UTC
On an iPhone in Safari, the chevron for the `dropdown` and `select` components is black when using a dark theme, it doesn't change color to a lighter variant. I'm running the latest iOS version (14.6).
On an iPad in Safari it works fine, the chevron changes color when switching between dark and light carbon themes.

To reproduce:
Open this URL on an iPhone: https://www.carbondesignsystem.com/components/dropdown/usage/#live-demo
Select Gray 90 or Gray 100 theme.
I tried changing the iPhone appearance from dark mode to light mode, but the problem still persists.
![6C9840C0-2474-4AF5-939E-E71011B59E48](https://user-images.githubusercontent.com/1822852/124954504-d27d4d80-e01e-11eb-9527-c8e87e6596bd.png)

**Comment by emyarod** [comment] 2021-07-13 14:21
I currently only have access to an iPad which doesn't seem to have the issue as you mentioned but it seems strange that only the iPhone would be rendering the component differently. can anyone else confirm the issue is occurring only on the iPhone?

**Comment by tw15egan** [comment] 2021-07-13 14:35
I'm unable to reproduce on iPhone 12 running `14.6`. Since you're not seeing it running Safari on iPad, it must be some sort of caching issue on the iPhone. Going to close this for now, but if you continue to see this (or we can get another reproduction), we'll reopen and take a look. Thanks for reporting! 

![IMG_4120](https://user-images.githubusercontent.com/11928039/125470565-ff317dea-5b03-46bd-9ff7-486644537459.jpg)
![IMG_4119](https://user-images.githubusercontent.com/11928039/125470570-80a3f9f1-6f63-4b89-84b7-3fd23e755465.jpg)

**Closed as completed by tw15egan** 2021-07-13 14:36 UTC
Labels: severity: 3, type: bug 🐛

**Comment by weaseldotro** [comment] 2021-07-13 18:20
I have determined the cause.
The option Settings / Accessibility / Display & text size / Increase contrast was turned on. After turning off the option, the chevron is not dark anymore.

It’s up to you to determine if this is an issue or not.
