### ISSUE TITLE
[Bug]: Datepicker in range mode on keyboard interaction selected date is getting changed

### ISSUE THREAD

**Issue by Geethkadali** [carbon-design-system/carbon#16144] opened 2024-04-08 07:28 UTC
### Package

@carbon/react

### Browser

Chrome, Firefox, Edge

### Package version

1.52.0

### React version

17.0.2

### Description

The default date should automatically be the date the user is selecting, but when we select dates with keyboard the selected date range is changing with the year 2001 on tab press.
This is especially challenging when trying to select the dates using only a keyboard.

### Reproduction/example

The behaviour is present on the online storybook https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

1. select the dates using keyboard
2. now do tab press, selected start date is changing to other date with year 2001
3. continue with tab press then again selected end date also changes with a date with 2001

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment] 2024-04-09 13:14
Hey @Geethakadali123 I'm not able to reproduce the error. The date is being selected as expect on my end, using only keyboard.
Could you record your screen, so we can see step by step?

**Comment by Geethakadali123** [comment] 2024-04-10 11:00
Hi @guidari  , I have attached the screen recording for your reference, you can view it here

https://github.com/carbon-design-system/carbon/assets/45656474/cd968c9f-0560-4a90-af24-6ece4afdce5c

**Comment by guidari** [comment] 2024-04-10 13:00
Hey @Geethakadali123 
Thanks for the video! 
I'll close this issue, because we have a similar issue https://github.com/carbon-design-system/carbon/issues/16125, I'll reference this issue there so whoever takes the issue can watch the video.

**Closed as completed by guidari** 2024-04-10 13:00 UTC
Labels: type: bug 🐛, component: date-picker, status: needs triage :female_detective:, status: waiting for maintainer response 💬
