### ISSUE TITLE
Need ability to drag resize columns in tables

### ISSUE THREAD

**Issue by elvis1994** [carbon-design-system/carbon#5480] opened 2020-02-28 10:23 UTC
**Summary**
Need the ability to drag resize a column in a table.
**Justification**
Some data is naturally long. To make the column large enough to display the longest possible content can make the table unwieldy, depending the available screen real estate. Allowing a user to dynamically resize a column allows them to easily override whatever size choice was made initially. 
**Desired UX and success metrics**

1. As the user moves the mouse over the divider between two column headers, the cursor changes (typically to some form of let-and-right arrow) to indicate that a click-and-drag from this point will result in column resizing.
2. If the user clicks and drags, a vertical line appears. This vertical line covers the height of the visible part of the table, and moves left and right to follow the mouse movement.
3. When the user ends the drag (by releasing the mouse button), the column separator moves from its original location to the new location, and all the cells in the column resize accordingly
4. The table component communicates the change (which column changed, and the values for the old and new widths) to the "calling environment". E.g., this could be by issuing an event.

Indication of drag resize possibility
![52746279-2b13a200-2faf-11e9-8c50-ea87cef71da0](https://user-images.githubusercontent.com/15010767/75540443-59c6b400-5a1c-11ea-9222-a5f0690116ab.png)

During dragging, showing the vertical line that follows the mouse:
![2](https://user-images.githubusercontent.com/15010767/75540456-5e8b6800-5a1c-11ea-9139-46f509b49508.png)

End of drag, column has been resized:
![3](https://user-images.githubusercontent.com/15010767/75540485-68ad6680-5a1c-11ea-8f5f-373623067b7c.png)

**Comment by tw15egan** [comment] 2020-02-28 12:06
Related: https://github.com/carbon-design-system/carbon/pull/5084

**Comment by joshblack** [comment] 2020-03-04 23:25
Closing as duplicate of #4751. Let me know if this is a mistake!

**Closed as completed by joshblack** 2020-03-04 23:25 UTC
