### ISSUE TITLE
[Bug]: DatePicker setting and clearing date in range issues

### ISSUE THREAD

**Issue by marcinmotNB** [carbon-design-system/carbon#17071] opened 2024-07-31 11:21 UTC
### Package

@carbon/react

### Package version

v1.62.1

### React version

v17.0.2

### Description

There is a problem with DatePicker component.
- after selecting date range if user clicks outside date component calendar is opened and can't be closed (issue can be reproduced on carbon's storybook too),
- when user clears date range start date input is not cleared,

https://github.com/user-attachments/assets/7ba96c66-3e29-4159-815d-0f82a14f8820

### Reproduction/example

https://stackblitz.com/edit/vitejs-vite-bngjrz

### Steps to reproduce

- create DatePicker with range and calendar
- select range
- click somewhere outside component

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by 2nikhiltom** [comment] 2024-07-31 11:26
Duplicate of https://github.com/carbon-design-system/carbon/issues/16740

**Comment by marcinmotNB** [comment] 2024-07-31 11:30
Is there also duplicate of second problem (resetting values)?

**Comment by 2nikhiltom** [comment] 2024-07-31 12:29
I rolled back to older version and did some debugging it seems like the reported issue is happening because of the [focus which is added ]( https://github.com/carbon-design-system/carbon/blob/50e88bc01cb35eb2667d03ea9a5bf415af94d680/packages/react/src/components/DatePicker/DatePicker.tsx#L448C3-L449C71)
```
  const onCalendarClose = (selectedDates, dateStr) => {
    endInputField?.current?.focus();
    calendarRef?.current?.calendarContainer?.classList.remove('open');
```

**Closed as completed** 2024-08-06 13:18 UTC
Labels: type: bug 🐛, severity: 2, component: date-picker
