### ISSUE TITLE
[React] DatePicker/DatePickerInput does not re-render on the change of minDate/maxDate prop

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4242] opened 2019-10-07 18:42 UTC
## What package(s) are you using?

- [x] `carbon-components-react`

## Detailed description

DatePicker/DatePickerInput is not re-rendering after minDate/maxDate param values are updated.

## Steps to reproduce the issue

1. On the codesandbox page below, select a "From" from the first date picker. Lets call it Today.
2. Now try selecting a "To" date from the second date picker. This control should have kept me from selecting a date before Today.

## Reason

I am aware of the range type of the datepicker, however in my context users need to select time range in addition to the date range hence I am using individual datepickers for From and To dates.

## Link for CodeSandBox

Please take a look at the codesandbox link to view the bug in action [CodeSandBox Link](https://codesandbox.io/s/codesandbox-6s86g)

- Notes
The props do work if a value is already set for the minDate and maxDate on the component load. However, it doesn't update when the values update.

**Comment by tahaimt** [comment] 2019-10-10 20:10
@asudoh can you take a look at this please

**Comment by asudoh** [comment] 2019-10-10 21:27
Workaround: Grabbing `<DatePicker>` instance via `ref` and running `datePickerInstance.cal.set({ minDate: newMinDate, maxDate: newMaxDate })`. Feel free to send a PR also, e.g. with adding `componentDidUpdate()` to detect change in `minDate`/`maxDate` and running `this.cal.set({ minDate: newMinDate, maxDate: newMaxDate })`.

**Comment by tahaimt** [comment] 2019-10-10 21:30
Another issue of a similar nature is happening with MultiSelect component. Take a look here https://codesandbox.io/s/codesandbox-nbxxn.
1. On page load, the count of initialSelectedItems is wrong (2 selected but the control shows 1).
2. None of the items are shown as selected in the expanded selection dropdown.
3. After 3 second of page load, the state used in initialSelectedItem is changed, however the change does not reflect in the control.

**Comment by asudoh** [comment] 2019-10-10 21:31
@tahaimt Could you please enter another issue for above? Thanks!

**Comment by tahaimt** [comment] 2019-10-10 21:32
Sure.

**Comment by tahaimt** [comment] 2019-10-10 22:11
> Workaround: Grabbing `<DatePicker>` instance via `ref` and running `datePickerInstance.cal.set({ minDate: newMinDate, maxDate: newMaxDate })`. Feel free to send a PR also, e.g. with adding `componentDidUpdate()` to detect change in `minDate`/`maxDate` and running `this.cal.set({ minDate: newMinDate, maxDate: newMaxDate })`.

@asudoh I am trying to do this on the mentioned codesandbox but the ref variable only has one property called current which is null. Take a [look](https://codesandbox.io/s/codesandbox-4k1ph). Select a date in the first control and open console.

**Comment by asudoh** [comment] 2019-10-10 22:12
It'll be set to non-`null` after it's mounted (e.g. in `useEffect()` callback).

**Comment by tahaimt** [comment] 2019-10-10 22:19
Thanks it worked.

**Comment by asudoh** [comment] 2020-01-24 04:00
Duplicate of: #2500

**Closed as completed by asudoh** 2020-01-24 04:00 UTC
Labels: severity: 3, type: bug 🐛, status: help wanted 👐, role: dev 🤖, component: date-picker
