### ISSUE TITLE
TableToolbarMultiSelect: not showing the complete placeholder text (on hover)

### ISSUE THREAD

**Issue by kaushalnavneet** [carbon-design-system/carbon#7298] opened 2020-11-16 22:44 UTC
## What package(s) are you using?
```
node_modules/@console/pal/carbon-components-react/DataTable/TableFilters/TableToolbarMultiSelect.js
```
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

### During preTVT testing, this issue got discovered with the TableToolbarMultiSelect component. On hover, the complete placeholder text should be visible, it doesn’t seem like this component has that behavior in place.

> Is this issue related to a specific component?

`TableToolbarMultiSelect`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

On hover, the complete placeholder text should be visible, which is not working in this case.

> What browser are you working in?

`Chrome`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

It is used in `pipeline-ui` and the concerned preTVT issue is supposed to be closed on priority.

## Steps to reproduce the issue

Issue reference: Problem 1 of this issue https://github.ibm.com/org-ids/g11n-issues/issues/482

**Comment by emyarod** [comment] 2020-11-17 15:33
if I understand the reported issue correctly, the visibility of placeholder text depends on the width of the input field

**Comment by tw15egan** [comment] 2021-02-04 20:12
Closing since this is working as intended. Feel free to reopen if you feel there is anything else you need us to do on our end. Thanks!

**Closed as completed by tw15egan** 2021-02-04 20:12 UTC
Labels: status: needs more info, type: bug 🐛, status: waiting for author's response 💬
