### ISSUE TITLE
Header and Content Overlap Issues

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon#5523] opened 2020-03-04 01:30 UTC
So at a certain break point the header navigation becomes unavailable and the side navigation fixes itself on the left side of the page. From what I can tell the width of the `SideNav` is fixed and thus the `Content` component should also have a fixed left margin as well that accommodates the size of the `SideNav`

Using a CSS grid class of `bx--offset-lg-3 bx--col-lg-13` is quite honestly a hack job because a margin of 3 units varies on different displays and thus creating visual inconsistency. In the very same way the `Content` component accommodates the height of `Header` it should accommodate `SideNav` especially if you're going to keep it fixed like that.

**Comment by tw15egan** [comment] 2020-03-13 16:21
Dupe of #5611

**Closed as completed by tw15egan** 2020-03-13 16:21 UTC
Labels: type: bug 🐛
