### ISSUE TITLE
[Feature Request]: Update `@carbon/styles` to a more recent `@ibm/plex`

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon#12608] opened 2022-11-14 10:13 UTC
### The problem

We're on Carbon 10 and our entire application is standardised on `@ibm/plex@6.0.2` - the latest version of this package is `@ibm/plex@6.1.1` which we could probably also use.

We recently added a dependency which makes use of `@carbon/styles` to our application and we discovered that this added a dependency on `@ibm/plex@6.0.0-next.6`:

https://github.com/carbon-design-system/carbon/blob/4b9b09a55304717307f288d8b588d23294318793/packages/styles/package.json#L42

This dependency is 50.6MB on disk. This is admittedly is a huge improvement over our current `@ibm/plex` which is 194MB on disk... but because we have two Plex installs in play at once, means this isn't an improvement for us, it's a regression of 50.6MB. This increases our install times and disk usage.

### The solution

I suggest that `@carbon/styles` should use the same Plex version as the rest of the Carbon ecosystem, a recent, supported version. If you want to experiment with new beta versions of Plex, I think that should be done using a beta version of `@carbon/styles` itself.

### Application/PAL

IBM App Connect Enterprise (don't know what a PAL is)

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Available extra resources

I can open a PR to change this version number but I don't know if that suffices.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment] 2022-11-14 16:29
@s100 We would welcome a PR to bump up the version, I don't think it should be an issue

**Comment by s100** [comment] 2022-11-14 16:59
@tw15egan Opened #12614, thank you.

**Comment by s100** [comment] 2022-11-14 17:26
OK so at first glance I thought this was just a one-liner because there were no lockfiles but on closer inspection it looks like there's one `yarn.lock` file for the entire repo at the top level, which means I guess I need to get a development environment set up, which is something like a 2GB to check out, and also the [Windows instructions](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/setup/windows.md#development-on-windows-10) are pretty lengthy, so this could take a while...

**Comment by tw15egan** [comment] 2022-11-14 18:03
@s100 I wasn't able to push to your branch, but I've put up a new PR [here](https://github.com/carbon-design-system/carbon/pull/12616) if you want to take a look

**Comment by tay1orjones** [comment] 2022-11-14 22:11
Yeah, I think this is a duplicate of #11661.

**Comment by tay1orjones** [comment] 2022-11-14 22:20
Duplicate of #11661

**Closed as not planned by tay1orjones** 2022-11-14 22:20 UTC
Labels: type: enhancement 💡, status: blocked 🙅‍♀️, role: dev 🤖, version: 11, proposal: open, package: @carbon/react, adopter: product

**Comment by s100** [comment] 2022-11-15 09:36
I don't see that `@ibm/plex` needs to be integrated into this repo in order to do this, surely this is just a simple version change?
