### ISSUE TITLE
Inconsistency in tooltip

### ISSUE THREAD

**Issue by Ankita-Jaiswal** [carbon-design-system/carbon#12060] opened 2022-07-20 04:27 UTC
Tooltip for button and Overflow Menu looks so different. There should be consistency. 
Currently button uses `<div class="bx--assistive-text"></div>` and others uses `title`. Thay's why it looks different.

https://ibm-systems-power.slack.com/archives/C2K6RFJ1G/p1658142286278329

![image](https://user-images.githubusercontent.com/16722905/179896789-a410ad2e-0ec0-4b0c-ad24-911b1691f649.png)
![image](https://user-images.githubusercontent.com/16722905/179896824-81a50f68-59f2-47c9-abec-587ff3be7444.png)

**Comment by tay1orjones** [comment] 2022-09-06 15:44
@Ankita-Jaiswal Thanks for pointing this out! We agree, the tooltips should be consistent. They are currently inconsistent because OverflowMenu uses a `title` attribute which renders the browser-based tooltip, whereas the Button is using the Carbon tooltip.

We have an issue open for this to consider replacing all usages of `title` with Carbon tooltips, https://github.com/carbon-design-system/carbon/issues/9208

**Comment by tay1orjones** [comment] 2022-09-06 15:44
Duplicate of https://github.com/carbon-design-system/carbon/issues/9208

**Closed as not planned by tay1orjones** 2022-09-06 15:44 UTC
Labels: status: waiting for author's response 💬, status: needs triage :female_detective:
