### ISSUE TITLE
Dropdown: Dropdown scrolling not working when first opened

### ISSUE THREAD

**Issue by KimWooHyun** [carbon-design-system/carbon#7371] opened 2020-12-01 06:41 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Hi. 
I'm getting this bug when dropdown first opened.
When I first open the dropdown, the scroll doesn't move if the selected value is at the bottom.
But, from the second time it works fine.

![dropdownbug](https://user-images.githubusercontent.com/4816936/100706007-8fedf580-33eb-11eb-8e3b-51474e370729.gif)

## Steps to reproduce the issue

I uesed latest version in codesandbox.
codesandbox: https://codesandbox.io/s/infallible-bush-9exgt

## Additional information

```javascript
import React from "react";
import { render } from "react-dom";
import "carbon-components/css/carbon-components.min.css";
import { Dropdown } from "carbon-components-react";

const items = [
  "option-1",
  "option-2",
  "option-3",
  "option-4",
  "option-5",
  "option-6",
  "option-7"
];

const App = () => (
  <Dropdown
    ariaLabel="Dropdown"
    id="carbon-dropdown-example"
    items={items}
    label="Dropdown menu options"
    titleText="Dropdown title"
    selectedItem="option-7"
  />
);

render(<App />, document.getElementById("root"));
```

**Comment by dakahn** [comment] 2021-04-13 14:59
@KimWooHyun Hey, thanks for reporting. Getting to this now. Interesting that I can confirm this behavior on your code sandbox, but can't recreate on my locals/in our testing sandbox [here](https://react.carbondesignsystem.com/?path=/story/components-dropdown--default). Was this behavior you saw outside of Codesandbox?

**Comment by dakahn** [comment] 2021-04-16 15:27
Since I can't recreate I'll close this up. If you're still seeing the error in production I can reopen though! 🏄🏽

**Closed as completed by dakahn** 2021-04-16 15:27 UTC
Labels: type: bug 🐛
