### ISSUE TITLE
Hover helps for closely located icon-only buttons could overlap

### ISSUE THREAD

**Issue by ykami** [carbon-design-system/carbon#5593] opened 2020-03-11 00:09 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

It looks an icon-only button pops up a hover help either when it gets focused or hovered. If you put focus on one icon and hover on the next icon, then hover helps overlap and they are really annoying.

Our product faced this issue and we tried to patch to the default behavior by ourselves, but it turned out it's not a good idea.

> Is this issue related to a specific component?

Icon-only Button component.

## Steps to reproduce the issue

1. Place two icon-only buttons closely
2. Put focus on one icon
3. Hover on the other icon
-> Two hover helps overlap

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/676255/76368639-4993ca80-6374-11ea-9b04-fa7139229886.png)

- Notes

**Comment by asudoh** [comment] 2020-03-11 04:56
Hi 👋 thank you for reporting! Seems a duplicate of #4560, let's discuss further there.

**Closed as completed by asudoh** 2020-03-11 04:56 UTC
Labels: type: bug 🐛
