### ISSUE TITLE
[OverflowMenu] OverfowMenu menu draws outside page boundary

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon#7689] opened 2021-01-28 22:35 UTC
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When the OverflowMenu menu opens near the edge of the page (bottom or right) it is drawn partially off page.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Menu should be positioned in the page so fully visible on open if possible, as is standard practice for native menus.

> What browser are you working in?

Chrome, Firefox

> What version of the Carbon Design System are you using?

 10.27 + React 7.27 (possibly happens in all versions.

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/overflow-ovlerflowing-emjoe

## Additional information

**Comment by tw15egan** [comment] 2021-01-28 22:49
Hey, @gillibrand thanks for raising this issue. It seems this is a duplicate of https://github.com/carbon-design-system/carbon/issues/6551 so I'm going to close this out and bump that issue again. 

For now, as a workaround, you can add `direction="top"` [like so](https://codesandbox.io/s/overflow-ovlerflowing-forked-rius5?file=/src/index.js:356-371) until we find a way to automate the direction it opens. Sorry for the inconvenience!

**Closed as completed by tw15egan** 2021-01-28 22:49 UTC
Labels: type: bug 🐛
