### ISSUE TITLE
Toggle text should be #171717 to pass high contrast accessbility testing and match the design spec.

### ISSUE THREAD

**Issue by xpander53** [carbon-design-system/carbon#4000] opened 2019-09-16 18:48 UTC
## Environment: All

> Operating system
ALL
> Browser
ALL
> Assistive technology used to verify
High Contrast chrome extension.

## Detailed description
Currently the toggle text is #565656 but the Sketch Design Kit states it should be #171717.  #565656 will cause the text to fail high contrast test.

> What version of the Carbon Design System are you using?
"@carbon/icons": "10.4.0",
"@carbon/icons-react": "10.4.1",
"carbon-components": "10.4.1",
"carbon-components-react": "7.4.1",

**Comment by dakahn** [comment] 2019-09-30 20:32
Not seeing this bug in React. Looks like we have a 11.5 contrast ratio.

**Comment by joshblack** [comment] 2019-11-22 19:12
Closing this as its been a while since the last update, feel free to comment with steps to reproduce and we'd be happy to take a look!

**Closed as completed by joshblack** 2019-11-22 19:12 UTC
Labels: status: needs more info
