### ISSUE TITLE
Add Notifications Panel to UI Shell

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1144] opened 2018-09-25 15:30 UTC
![image](https://user-images.githubusercontent.com/3901764/46025224-10976580-c0ae-11e8-890d-097fed9e4410.png)

Latest Sketch file: https://ibm.box.com/s/5t33bkuvfk0c3dj61nyyb9vqv0rk25gp

**Comment by paschalidi** [comment] 2019-04-12 14:46
@joshblack can i take care of this please?

**Comment by joshblack** [comment] 2019-04-12 14:50
Hi @paschalidi! 👋 We're currently revisiting our UI Shell work after our v10 release, so this may be getting an update, but once we finalize it we would love if you want to take it on!

**Comment by paschalidi** [comment] 2019-04-12 15:26
shore

**Comment by paschalidi** [comment] 2019-04-12 15:27
shore I would love to 👍 will be waiting for one

**Comment by chrisconnors-ibm** [comment] 2019-05-01 19:00
dupe of https://github.com/carbon-design-system/carbon-components/issues/2336

**Closed as completed by chrisconnors-ibm** 2019-05-01 19:00 UTC
Labels: role: dev 🤖
