### ISSUE TITLE
Cannot find: "/css/carbon-components.min.css" in carbon-components@11.0.0

### ISSUE THREAD

**Issue by katjageb** [carbon-design-system/carbon#11136] opened 2022-04-04 14:59 UTC
### Description

Our IBM application makes use of the carbon-component.min.css for 11.0.0 and it seems to not be able to find this anymore since last week Friday.

This link: https://unpkg.com/carbon-components/css/carbon-components.min.css
Completes to: https://unpkg.com/carbon-components@11.0.0/css/carbon-components.min.css

![Screenshot 2022-04-04 at 16 00 02](https://user-images.githubusercontent.com/32041604/161572622-c3b269c4-2704-4cd1-8c4d-1f460ee723af.png)

The UI for the web browser related sign is affected and looks out of place since:

Screenshots:
![Screenshot 2022-04-03 at 18 37 18 (2)](https://user-images.githubusercontent.com/32041604/161571989-a5a4c12b-bb86-4a93-952a-88c2f0688871.png)
![Screenshot 2022-04-03 at 18 37 10 (2)](https://user-images.githubusercontent.com/32041604/161572010-532b7f98-80b0-45cf-a116-f19242ccca96.png)
![Screenshot 2022-04-03 at 18 37 06 (2)](https://user-images.githubusercontent.com/32041604/161572023-128cc850-38a2-4f6c-bbb4-a43c9e2280dc.png)

From the browser console:
![image](https://user-images.githubusercontent.com/32041604/161572384-b72b641a-c96e-4f30-b2d1-9332cd6deb30.png)

Where as before it looked like this:
<img width="403" alt="APA - Sign-in panel" src="https://user-images.githubusercontent.com/32041604/161572144-ec28f2ed-365d-45cf-8d05-206a99a7e2dd.png">

Can you please let me know if this link will get fixed, or if this is something on our end I need to change.

If you need more information, please let me know,

Thanks in advance,
Katja

**Comment by tay1orjones** [comment] 2022-04-04 15:08
@katjageb Thanks for reporting this, if you're looking for the v10 versions of this file, you'll need to use a versioned url like https://unpkg.com/carbon-components@10.56.0/css/carbon-components.min.css

**Comment by katjageb** [comment] 2022-04-04 15:13
Hey Taylor @tay1orjones can I ask a question for understanding, am I right in thinking, that this URL: https://unpkg.com/carbon-components/css/carbon-components.min.css will automatically complete to whatever is the latest version?

So since 31.03.2022 and the move to Carbon 11, it couldn't find the file, as it doesn't exist yet?

Thanks for your help, Katja

**Comment by tay1orjones** [comment] 2022-04-04 15:51
Duplicate of https://github.com/carbon-design-system/carbon/issues/11129

**Closed as completed by tay1orjones** 2022-04-04 15:51 UTC
Labels: status: waiting for author's response 💬, status: needs triage :female_detective:
