### ISSUE TITLE
DataTable SelectAll failed after filtering

### ISSUE THREAD

**Issue by chenxpcn** [carbon-design-system/carbon#2569] opened 2018-11-09 03:52 UTC
Say there are 3 rows in a DataTable.  Filter the table to show 2 rows only, click SelectAll box, on table header, the description shows "3 items selected".  and then if take action on selected rows, all 3 items are applied.  It should be 2 items actually.
![image](https://user-images.githubusercontent.com/44887319/48242368-e9b89880-e3a8-11e8-832c-44050e5887b3.png)

**Comment by joshblack** [comment] 2020-08-20 15:07
Going through older issues, I believe this issue has been addressed (at least I couldn't reproduce in latest) so am going to close this one out! 👍

**Closed as completed by joshblack** 2020-08-20 15:07 UTC
Labels: type: bug 🐛, role: dev 🤖, package: react
