### ISSUE TITLE
Previous/next icon size option for pagination

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#6316] opened 2020-06-19 03:36 UTC
At Carbon version 10.12.0, default icon size of pagination was enough. However, icon size became smaller as upgrading to 10.14.0. Therefore, I need option to control size of prev/next button for pagination svg. I checked [storybook](https://react.carbondesignsystem.com/?path=/story/pagination--pagination) and couldn't find it.

![스크린샷 2020-06-19 오후 12 37 23](https://user-images.githubusercontent.com/35518072/85094467-d11d8f00-b229-11ea-9adf-6c05b77f4ff1.png)

**Comment by emyarod** [comment] 2020-06-23 16:44
unless this is a visual issue or spec mismatch (cc @carbon-design-system/design) this should be resolvable at the app level via CSS

**Comment by aagonzales** [comment] 2020-06-24 15:44
I don't believe the icon should have changed size between those releases. If it has happened then that is a regression and we should fix it.

**Comment by emyarod** [comment] 2020-06-24 15:57
based on https://github.com/carbon-design-system/carbon/pull/6058 it appears to be intentional @aagonzales but if this is supposed to be 20x20 again I can make that change

**Comment by aagonzales** [comment] 2020-06-24 19:46
Ok it sounds like the icon size did physically change at one point but with the #6058 issue it has been changed to be optically correct to its original size. So they started out small, became big for a release or two, but now they are back to their intended size. We do **not** want to introduce a larger size variant here at this time. We don't normal introduce a variant with just the one icon size changing, a size variant would scale all aspect of the component up.

![image](https://user-images.githubusercontent.com/11670886/85619749-5937d600-b628-11ea-8430-a7adec947f0d.png)

-----------------------

As a side note, the change in size has made the padding be incorrect to form perfect squares for those arrow to sit in.
![image](https://user-images.githubusercontent.com/11670886/85620335-407bf000-b629-11ea-90f2-2a8ccdf9f9b2.png)

**Comment by baeharam** [comment] 2020-06-25 00:53
Ok, I'll style these buttons at the app level until for the next release. Can I close?

**Comment by chrisconnors-ibm** [comment] 2020-06-25 14:56
@baeharam no need - the PR above will close it when it's merged. Thank you!

**Closed as completed** 2020-06-25 19:30 UTC
Labels: type: enhancement 💡
