### ISSUE TITLE
Different overflow menu button getting focused while clicking

### ISSUE THREAD

**Issue by akashkrishnak** [carbon-design-system/carbon#15366] opened 2023-12-11 06:49 UTC
### Package

@carbon/react
carbon-components-react

### Browser

Safari

### Package version

7.12.0

### React version

18.2.0

### Description

While clicking on a particular overflow menu button in the data table, a different overflow menu button gets focused.
<img width="1728" alt="Screenshot 2023-12-11 at 10 32 47 AM" src="https://github.com/carbon-design-system/carbon/assets/70852245/412690d3-9731-444f-b621-0fa0c8544d6f">

### Reproduction/example

https://stackblitz.com/edit/github-hdg3nw?file=src%2FApp.jsx

### Steps to reproduce

1. Click on any overflow menu button.
2. Click on another overflow menu button without closing the previously opened menu.
3. Previously selected overflow menu button gets focused rather than the currently selected button.

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment] 2023-12-11 14:07
@akashkrishnak could you share more, potentially a screen recording, of how you observed this bug? I can't reproduce on the storybook. 

https://github.com/carbon-design-system/carbon/assets/3360588/316fae93-cc20-45c7-81cd-1f8845620ed1



I also can't reproduce it on the stackblitz you shared.


https://github.com/carbon-design-system/carbon/assets/3360588/f760cdaf-28d9-4d3f-ad40-0e903cec0442

**Comment by akashkrishnak** [comment] 2023-12-11 14:24
As I said in the step 2 , you should not close the previously opened menu.
https://github.com/carbon-design-system/carbon/assets/70852245/03716df9-12c6-4e6c-b14f-48a6089eedb4


https://github.com/carbon-design-system/carbon/assets/70852245/f28055d9-b634-482b-b555-cf89ae375ec6

**Comment by tay1orjones** [comment] 2023-12-11 15:00
Ah, my mistake, yes I see it now. My guess is that this stems from the focus placement logic of the FloatingMenu used internally.

**Comment by 2nikhiltom** [comment] 2024-03-13 11:06
Will be closed by 
https://github.com/carbon-design-system/carbon/pull/15833

**Closed as completed** 2024-03-27 13:30 UTC
Labels: type: bug 🐛, severity: 2, role: dev 🤖, version: 11, component: overflow-menu
