### ISSUE TITLE
[Bug]: Radio Button not working

### ISSUE THREAD

**Issue by csgeeek** [carbon-design-system/carbon#12315] opened 2022-10-17 09:48 UTC
### Package

@carbon/react

### Browser

Chrome, Firefox, Edge

### Package version

v1.15.0

### Description

This is a `documentation` related issue.

The radio button in [docs](https://react.carbondesignsystem.com/?path=/docs/components-tile--radio) is not functioning properly. When clicking on `option 3` of `radio button`, `Multi select` fields are getting highlighted.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-tile--radio

### Steps to reproduce

1. Goto [Link](https://react.carbondesignsystem.com/?path=/docs/components-tile--radio)
2. Click on `Option 3` in `Radio`

Multiselect fields are getting highlighted.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jsehull** [comment] 2023-03-29 14:13
@TannerS marked this as fixed in #12312 (comment [here](https://github.com/carbon-design-system/carbon/pull/12312#issuecomment-1292758903))

I can confirm. I am not able to reproduce the bug and it seems to work as intended now.

**Closed as completed** 2023-03-31 13:39 UTC
Labels: type: bug 🐛, severity: 4
