### ISSUE TITLE
Type declarations should work for package imports

### ISSUE THREAD

**Issue by brandones** [carbon-design-system/carbon#9540] opened 2021-08-25 16:16 UTC
`@types/carbon-components-react` doesn't provide types for ES package imports, e.g. `carbon-components-react/es/components/UIShell`. Typescript complains: 

> Could not find a declaration file for module 'carbon-components-react/es/components/UIShell'. '/path/project/node_modules/carbon-components-react/es/components/UIShell/index.js' implicitly has an 'any' type.
  If the 'carbon-components-react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon-components-react'ts(7016)

**Comment by Daveiano** [comment] 2021-12-13 17:23
What is the state when using the new @carbon/react?

The page at https://github.com/carbon-design-system/carbon-components-react says we should use this package instead but there is no typescript support yet because @types/carbon-components-react is for the deprecated repo?

**Comment by joshblack** [comment] 2022-02-18 16:24
For TypeScript discussions, I made a discussion over at: https://github.com/carbon-design-system/carbon/discussions/10752

This should be where teams can find the most up-to-date information on where our team is at with respect to TypeScript. At the moment, the types are community-provided and supported and we do not have influence over them. This is more of a logistics problem than anything else on our end, if teams would like to help I would love to chat more in the discussion.

Definitely am sorry that the situation for TypeScript is as rough and confusing as it currently is. It's definitely not our intention and we are trying to see what we could provide to improve this experience.

**Comment by tay1orjones** [comment] 2024-09-11 14:37
Duplicate of https://github.com/carbon-design-system/carbon/issues/16436

**Closed as not planned by tay1orjones** 2024-09-11 14:37 UTC
Labels: type: enhancement 💡, proposal: accepted, area: typescript
