### ISSUE TITLE
click CopyButton, the outline of the copy button is out of frame

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1122] opened 2018-09-19 12:20 UTC
@xiaolixu commented on [Tue Sep 18 2018](https://github.com/IBM/carbon-components-react/issues/1335)

## Detailed description

> Describe in detail the issue you're having.

click CopyButton, the outline of the copy button is out of frame

> Is this issue related to a specific component?

CopyButton

> What browser are you working in?

Firefox 60.2.0esr (64-bit) on Windows OS , the issue can not be seen with Firefox on Mac OS

> What version of the Carbon Design System are you using?

carbon-components-react: 6.21.4
carbon-components: ^9.5.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Virtual Private Cloud

## Steps to reproduce the issue

http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-The%20text%20shown%20upon%20clicking%20%28feedback%29=Copied%21&knob-How%20long%20the%20text%20is%20shown%20upon%20clicking%20%28feedbackTimeout%29=3000&knob-Feedback%20icon%20description%20%28iconDescription%29=Copy%20to%20clipboard&selectedKind=CopyButton&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

## Additional information

* Screenshots or code
![screenshot 2](https://user-images.githubusercontent.com/24239504/45726673-da13a380-bbf2-11e8-8795-2399f79f4013.png)

* Notes
 the issue can not be seen with Firefox on Mac OS

---

@alisonjoseph commented on [Wed Sep 19 2018](https://github.com/IBM/carbon-components-react/issues/1335#issuecomment-422781053)

I was able to see this issue on FF on mac, but only after clicking copy while having keyboard focus on the icon.  Going to move this to the carbon-components repo since it appears to be a styling issue.

**Comment by tw15egan** [comment] 2018-10-09 19:14
Since the `bx--btn--copy__feedback`, the tooltip, is located inside the `button`, the focus wrapper expands when the hidden text becomes visible. This is a cross-browser differentiation, and not much we can do about this without rewriting the HTML (breaking change). 

 We could switch the focus to the `svg`, but since there is no padding it looks a bit odd

<img width="87" alt="screen shot 2018-10-09 at 2 11 58 pm" src="https://user-images.githubusercontent.com/11928039/46692666-8121a480-cbcd-11e8-97c1-d88c4b6516b5.png">

Going to close this, as this is not a bug but just how Firefox handles focus and containing elements. Feel free to submit a fix if you find one

**Closed as completed by tw15egan** 2018-10-09 19:14 UTC
Labels: type: bug 🐛, severity: 4
