### ISSUE TITLE
[React] TextInput.Password not showing *'s for input characters

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4631] opened 2019-11-08 22:39 UTC
## What package(s) are you using?

- [x] `carbon-components`; 10.7.3
- [x] `carbon-components-react`; 7.7.3

## Detailed description

As apparent from the title, password input is not showing fields as *. Also, the documentation on the component suggests using PasswordInput but Story asks to use TextInput.Password. Here is the [codesandbox](https://codesandbox.io/s/codesandbox-sufu3?fontsize=14)

**Comment by emyarod** [comment] 2019-11-08 22:43
did you try removing `type="text"`?

**Comment by tahaimt** [comment] 2019-11-08 22:49
Yeah but the control is called PasswordInput so should it ignore the prop...., just wondering.

**Comment by emyarod** [comment] 2019-11-11 15:56
it looks like `type` is being spread into the input, and perhaps we can consider setting a fixed `type` in the next major release. but for now the workaround would be to leave the input `type` as it is (or not set it to a value that you do not want)

**Comment by emyarod** [comment] 2020-01-09 19:45
closing as the issue is caused by explicitly setting the input type to something that is not desired

**Closed as completed by emyarod** 2020-01-09 19:45 UTC
Labels: type: bug 🐛
