### ISSUE TITLE
Improve package bundle performance

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#8407] opened 2021-04-14 20:05 UTC
Our packages ship more JS and CSS than they need to. As part of our next release, it'd be great to refactor away some of the dead code that is not needed for a package. We could also use this as a chance to move away from dependencies that may be larger than we want to ship, or are unintentionally included even when not used.

In terms of CSS, it'd be great to get a handle our the size of each stylesheet. Reducing selector complexity and limiting our use of nested mixins to generate CSS will go a long way to reducing the overall footprint of Carbon's styles.

Packages impacted:
- carbon-components
- carbon-components-react

**Comment by floriankapaun** [comment] 2021-05-14 15:00
Not quite sure if this is the right place to add this, but I've experienced the same issue you are describing here when I used `@carbon/vue`. Even if I'm only using a few components I'd have to include the whole bundle (carbon-vue.umd.min.js) which comes in at a total of over 300 KB.

**Comment by joshblack** [comment] 2022-01-04 16:47
Duplicate of: https://github.com/carbon-design-system/carbon/issues/4882 I believe, @tay1orjones 

Going to close this in favor of that issue, feel free to re-open if that's not the case!

**Closed as completed by joshblack** 2022-01-04 16:47 UTC
Labels: planning: umbrella
