### ISSUE TITLE
How to change MultiSelect value programatically?

### ISSUE THREAD

**Issue by Jodebu** [carbon-design-system/carbon#6515] opened 2020-07-22 09:44 UTC
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
We are using Carbon inputs in a filter form where we need to include a "reset filters" button, which sets the state of the form to the initial state. Every input gets initialiazed as expected except for MultiSelect.Filterable, which retains the selection (even though the state changes properly and the list is correctly unfiltered).
Since the MultiSelect does not have a traditional "value" prop, is there a way to programatically change or restart the selected items?

## Relevant information
- `react`: 16.13.1
- `carbon-components`: 10.14.0
- `carbon-components-react`: 7.14.0

Please do not hesitate to ask for any extra information you mey need.
Thank you very much in advance!

**Comment by emyarod** [comment] 2020-07-27 19:13
I don't believe this use case is well supported beyond setting the initial selected items and rerendering the component with modifiede initial selected items using a key

**Comment by nagiah** [comment] 2020-10-09 17:29
I'm using Carbon MultiSelect in a filter form with a "reset filters" button. initialSelectedItems is not getting cleared when set to empty array [].
Could you please provide a working example on how to clear MultiSelect selected items programmatically?

**Comment by tw15egan** [comment] 2020-10-09 17:44
@nagiah can you put your code up in a CodeSandbox so we can take a look and see whats going wrong?

**Comment by nagiah** [comment] 2020-10-10 06:18
Here's an example on sandbox:
https://codesandbox.io/s/modest-merkle-fzltr

**Comment by tw15egan** [comment] 2020-10-12 18:54
Seems this is a dupe of https://github.com/carbon-design-system/carbon/issues/4812, so I'm going to close this issue so we can keep the conversation in one place.

**Closed as completed by tw15egan** 2020-10-12 18:54 UTC
Labels: type: question ❓, component: multiselect
