### ISSUE TITLE
React does not recognize the `isSideNavExpanded` prop on a DOM element

### ISSUE THREAD

**Issue by AlanGreene** [carbon-design-system/carbon#3970] opened 2019-09-12 16:58 UTC
## What package(s) are you using?

- [x] `carbon-components` - 10.6.1 (latest)
- [x] `carbon-components-react` - 7.6.1 (latest)

## Detailed description

> Describe in detail the issue you're having.

It looks like https://github.com/carbon-design-system/carbon/pull/3626 introduced a warning about unrecognized props being applied to DOM elements.

```
Warning: React does not recognize the `isSideNavExpanded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issidenavexpanded` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink (created by Link)
    in Link (created by ForwardRef(SideNavMenuItem))
```

here, the props (including `isSideNavExpanded`) are being spread onto `element`: https://github.com/carbon-design-system/carbon/blob/99f12f98e226b2ab1872b7379167d827e4fe7bd5/packages/react/src/components/UIShell/Link.js#L19

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The Carbon components should not be passing through all props like this, instead they should filter out those that are not supported / relevant for the target component / element, or explicitly pass only the expected props to their children.

Having these warnings causes a lot of noise in logs, both in the browser and in tests, making it harder to spot / debug genuine problems.

## Steps to reproduce the issue

This can be reproduced by running the storybook in dev mode
1. from packages/react: `npm run storybook`
2. navigate to http://localhost:9000/?path=/story/ui-shell--fixed-sidenav
3. see the warning in the browser console

![image](https://user-images.githubusercontent.com/2829095/64804395-aa3d7880-d586-11e9-95b6-e553a19e66f8.png)

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment] 2019-11-19 22:52
Should be closed by https://github.com/carbon-design-system/carbon/pull/4349! Let me know if that isn't the case and I'd be happy to re-open 😄

**Comment by AlanGreene** [comment] 2020-01-27 22:02
Apologies for the delay, I completely lost track of this one. I've just updated to 10.9.2/7.9.2 and confirmed it's resolved 👍 Thanks

**Comment by KimWooHyun** [comment] 2020-03-16 08:53
@joshblack Hi  josh,

I still having the same problem with ts 😢 

## What package(s) are you using?

- [x] `carbon-components` - 10.10.1
- [x] `carbon-components-react` - 7.10.1
- [x] `types/carbon-components-react` - 7.6.15

## Detailed description

###  console
```
Warning: React does not recognize the `isSideNavExpanded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issidenavexpanded` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Link)
    in Link (created by ForwardRef(SideNavMenuItem))
    in li (created by ForwardRef(SideNavMenuItem))
    in ForwardRef(SideNavMenuItem) (at Sidebar/index.tsx:26)
    in ul (created by SideNavItems)
    in SideNavItems (at Sidebar/index.tsx:24)
    in nav (created by ForwardRef(SideNav))
    in ForwardRef(SideNav) (at Sidebar/index.tsx:23)
    in Sidebar (at Header/index.tsx:26)
    in header (created by Header)
    in Header (at Header/index.tsx:15)
    in Header (at Layout/index.tsx:25)
    in div (at Layout/index.tsx:24)
    in render (created by HeaderContainer)
    in HeaderContainer (at Layout/index.tsx:16)
    in Layout (at Payment/index.tsx:62)
    in Payment (created by Context.Consumer)
    in Route (at App.tsx:34)
    in Route (at App.tsx:56)
    in Switch (at App.tsx:52)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:51)
    in ApolloProvider (at App.tsx:50)
    in App (at src/index.tsx:7)
```

### using component

```
// isSideNavExpanded is props

<SideNav aria-label="Side navigation" isRail expanded={isSideNavExpanded}>
  <SideNavItems>
    <SideNavMenuItem href="" aria-current='page'>test</SideNavMenuItem>
  </SideNavItems>
</SideNav>
```

**Comment by muratumutlu** [comment] 2020-05-08 13:18
Hi @joshblack  ,

The error is going on. I'm using the following packages:

"carbon-components": "^10.11.2",
"carbon-components-react": "^7.10.2",
"carbon-custom-elements": "^1.0.0-beta.12",
"carbon-icons": "^7.0.7",

**Comment by AlanGreene** [comment] 2020-05-08 13:37
@muratumutlu I'm not a Carbon developer. I'm just a user like you who reported an issue I found, and it was resolved for my use case in the versions I mentioned in my last comment.

You should probably open a new issue with details of what you're seeing, including a codesandbox  reproducing it if possible. That will make it easier for the Carbon team to debug.

**Comment by muratumutlu** [comment] 2020-05-09 05:11
Sorry @AlanGreene , I've seen your message about "it's resolved" and then I post this message. Now I'm changing my message. Thank you for the information.

**Comment by trusinaj** [comment] 2020-06-02 12:33
Im having same issue as @KimWooHyun or @AlanGreene in version:
    "carbon-components": "10.12.0",
    "carbon-components-react": "7.12.0",

![image](https://user-images.githubusercontent.com/26432590/83520377-e54d5680-a4dd-11ea-8962-f3aceaaa21ab.png)

**Comment by hsu022210** [comment] 2020-06-05 18:55
Hi @joshblack , I'm also having the issue with
"carbon-components": "10.12.0",
"carbon-components-react": "7.12.0"

<img width="447" alt="Screen Shot 2020-06-05 at 11 53 48 AM" src="https://user-images.githubusercontent.com/9044877/83912827-5af63400-a723-11ea-8307-1e676d15ad34.png">

**Comment by tw15egan** [comment] 2020-06-08 15:22
Does anyone have a link to a reproducible example? 

The example using `isSideNavExpanded` in storybook does not seem to be throwing that warning...

https://react.carbondesignsystem.com/iframe.html?id=ui-shell--sidenav-rail-w-header

**Comment by AlanGreene** [comment] 2020-06-08 15:57
I'm not seeing the issue, but React only emits those warnings in dev mode so you'd need to run the storybook locally in dev mode to see it if it's happening there.

**Comment by zigzactly** [comment] 2020-06-11 03:01
Hi there, i am also having this issue. I will see if i have the time to get a basic reproducible example, but im not doing anything differently from the storybook.

(Im a little behind on the versions)
"carbon-components": "^10.11.2",
"carbon-components-react": "^7.11.3",

![image](https://user-images.githubusercontent.com/6165450/84340129-8caf4500-abd2-11ea-88b4-6d87e89ebdfa.png)

**Comment by kubijo** [comment] 2020-07-16 11:43
It's still there on 
```json
{
  "carbon-components": "^10.15.0",
  "carbon-components-react": "^7.15.0"
}
```

**Comment by dioslibre** [comment] 2021-01-16 22:54
```
import PropTypes from "prop-types";

const SideNavChild = ({ children }) => {
  return children;
};

SideNavChild.propTypes = {
  isSideNavExpanded: PropTypes.bool,
};

const Sidebar = () => {
  return (
    <SideNav
      isFixedNav
      expanded={true}
      isChildOfHeader={false}
      aria-label="Legend"
      className="w-screen md:w-80 max-w-screen"
    >
      <SideNavChild>
             ...
      </SideNavChild>
    </SideNav>
  );
};
```

**Comment by tw15egan** [comment] 2021-02-05 18:32
I've just tested locally in dev mode and on the deployed production version and I'm unable to reproduce this issue. My main recommendation is to ensure you are running the latest version of the components and see if it still exists. Closing this since I am unable to reproduce, but I will reopen if someone can provide a CodeSandbox reproducing this issue. Thanks!

**Comment by kubijo** [comment] 2021-02-07 12:47
![image](https://user-images.githubusercontent.com/11244314/107146161-a1510200-6946-11eb-9ce0-3090b8f29380.png)

The way I see it:
 - `SideNavItems` [injects `isSideNavExpanded` into its children](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/SideNavItems.js#L23) (I've got `undefined` in there)
 - `SideNavMenuItem` [spreads that into Link](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/SideNavMenuItem.js#L27)
 - `Link` [spreads it](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/Link.js#L19) [into anchor](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/Link.js#L39) [without catching `isSideNavExpanded`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/Link.js#L18)

**Comment by kubijo** [comment] 2021-02-07 12:55
- I've looked into your official storybook site, but that doesn't shout probably because it's a production build.
- I've tried creating CodeSandbox, but it spouted strange errors about unknown/undefined elements on code that didn't seem to have any apparent problems & I don't really have time for debugging example sandbox without any prior experience with that tool.

I believe however that the message above does, however, explain the problem quite thoroughly & the fix could be as easy as catching the `isSideNavExapnded` in the `UIShell/Link`s props destructuring … or not passing it there in the first place since the component doesn't really need it.

**Comment by tw15egan** [comment] 2021-02-08 20:42
@kubijo Thanks for taking the time to investigate this. I'll make a PR to catch the `isSideNavExpanded` in the `Link` to avoid this warning.

**Comment by kubijo** [comment] 2021-03-19 09:40
OK guys, the problem persists in `7.31.0` … I could probably redo my last report, but I believe that I've covered it in a pretty detailed manner, so could you please sift through the rest of the few components in the same way?

**Comment by kubijo** [comment] 2021-03-19 09:41
For what it's worth, this is the tail of stack-trace that I get 
![image](https://user-images.githubusercontent.com/11244314/111761032-b3a45100-889f-11eb-8c19-c685eabe38f6.png)

----------------------------------

Edit: found the culprit… [it's about this line](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/UIShell/SideNavItems.js#L23) & the fact that our designers require some custom elements in the menus (titles).

You are injecting the prop to whatever gets into children.
While I do understand the simplicity-based reason for this choice, it's quite evidentially pretty clunky because you are making too 
strong assumptions about usages.

Couldn't you use a React context and flip the solution to ask for value in components that might need it instead of forcing it upon everything?

------------------------------------

For others … For now, I've been able to fix it this way 
![image](https://user-images.githubusercontent.com/11244314/111764096-2531ce80-88a3-11eb-931c-78c8b686be39.png)

… or just wrap it in `React.Fragment` ;-)

**Comment by emyarod** [comment] 2021-03-19 16:50
@kubijo would you mind sharing a reduced test case in a ZIP if [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox) is still not playing nice?

**Comment by kubijo** [comment] 2021-03-19 17:58
If I understood it correctly this should be the link https://codesandbox.io/s/magical-clarke-ldj9i?file=/src/index.js

**Closed as completed** 2021-03-24 18:41 UTC
Labels: type: bug 🐛, role: dev 🤖, component: ui-shell
