### ISSUE TITLE
IE11: Single line code snippet is overflowing bounds

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2060] opened 2019-03-12 18:11 UTC
> Describe in detail the issue you're having.

Single line code snippet appears wider in IE11 than other browsers.

> Is this issue related to a specific component?

Code snippet

> What did you expect to happen? What happened instead? What would you like to see changed?

Here's IE11. Notice how copy button extends to the right.

![image](https://user-images.githubusercontent.com/1691245/54224778-3bdd0800-44c8-11e9-8680-685c3be06e4d.png)

Here's Chrome, what's expected.

![image](https://user-images.githubusercontent.com/1691245/54224805-48f9f700-44c8-11e9-8aad-8f6a749ab181.png)

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v10

**EDIT** 
This seems to be a Windows issue and not a browser issue

**Comment by asudoh** [comment] 2019-04-17 04:55
@mattrosno Have you tried Windows Chrome? Wanted to see if this is an issue with Windows scroll bar or with IE. Thanks!

**Comment by mattrosno** [comment] 2019-04-17 15:50
@asudoh I did not debug by testing other Windows browsers.

**Comment by aledavila** [comment] 2019-04-17 20:06
@asudoh I checked on both Edge and Chrome on windows and the same issue persists. So it seems to be a Windows issue not an IE11 issue. Do you know of a fix for this ?

**Comment by asudoh** [comment] 2019-04-17 22:36
@aledavila I don't have a specific fix I have come up with yet, but I have an impression that we need to change how we lay out the code portion and the button portion (e.g. using flex box). BTW I see it's reproducible even in Mac, by setting "Always" to "Show scroll bars" in System Preferences. Would you be able to pair with @jnm2377 on this? Thanks!

**Comment by aledavila** [comment] 2019-04-18 16:02
@mattrosno is this issue pertaining to the scroll bar that it is showing up or that the code snippet container is overflowing past its container ?

**Comment by mattrosno** [comment] 2019-04-18 16:08
@aledavila OSes will always treat scrollbars differently so I don't expect Windows scrollbars look as good as scrollable containers in macOS. IMO this bug is mostly about the right overflow.

**Comment by aledavila** [comment] 2019-04-18 16:17
@mattrosno So I can make the scroll bar be the same width as the code snippet. As for the right overflow of code snippet in our website that is not how it looks. Thats specific to our dev environment and our dev container demo styles. 

This is in production: 
<img width="2032" alt="Screen Shot 2019-04-18 at 11 16 49 AM" src="https://user-images.githubusercontent.com/12533409/56375577-91918800-61cb-11e9-941c-62c84a30ed74.png">

**Comment by mattrosno** [comment] 2019-05-24 15:04
Not stale.

**Comment by joshblack** [comment] 2019-12-06 16:50
Going to close this as it seems related to our dev environment. Feel free to re-open if this isn't the case!

**Closed as completed by joshblack** 2019-12-06 16:50 UTC
Labels: type: bug 🐛, role: dev 🤖, browser: ie11
