### ISSUE TITLE
[a11y]: JAWS reads Tooltip as  button

### ISSUE THREAD

**Issue by xuelanz** [carbon-design-system/carbon#10667] opened 2022-02-09 08:14 UTC
### Package

        "carbon-components": "10.52.0",
        "carbon-components-react": "7.52.0",

### Browser

Chrome

### Operating System

Windows

### Package version

10.52.0

### React version

17.0.2

### Automated testing tool and ruleset

JAWS 2021

### Description

What is expected: Jaws could recognize Carbon Tooltip as tooltips, read tooltip label and tooltip messsage.

What happens: All the tooltips info within application are not able to be read by JAWS. When a respective tooltip is opened, JAWS reads it as button collapsed to open press space bar/Enter key, expanded. Pressing Space Key/Enter key closes the tooltip. Here the user will get confused as there is no button it’s just tooltip.

After update to  "carbon-components": "10.52.0" "carbon-components-react": "7.52.0", JAWS is able to read tooltip message, automatically open and close when focus on and off. But it still reads tooltip as button, tells press enter to activate.

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-tooltip--default-bottom

### Steps to reproduce

> Find a windows environment to install JAWS 2021.
> Using JAWS to read theTooltip on page https://react.carbondesignsystem.com/?path=/story/components-tooltip--render-custom-icon, JAWS reads it as button.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment] 2022-02-16 21:21
@dakahn can you confirm if this is an issue after all?

**Comment by dakahn** [comment] 2022-02-21 16:44
Potentially relevant 
https://github.com/w3c/aria-practices/issues/128#issuecomment-1015063668

**Comment by dakahn** [comment] 2022-02-21 22:47
attempted to verify with **JAWS 2022.2112.24** and couldn't reproduce. When the tooltip button receives focus it's read as "tooltip label button expand/collapse" which seems right to me. Describes the element, what it is, and what will happen if it's activated. Im closing this as a false report, but after you upgrade JAWS if you still are encountering this error let me know and we can reopen 👍🏾

**Closed as completed by dakahn** 2022-02-21 22:47 UTC
Labels: type: a11y ♿, package: react, component: tooltip
