### ISSUE TITLE
Date range picker, end date controls forces you to re-enter start date

### ISSUE THREAD

**Issue by matrix674** [carbon-design-system/carbon#4476] opened 2019-10-28 15:50 UTC
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

When you want to edit a selected date in the date range picker. Click on the end date control forces you to first re-enter the start date.

I believe that click on the end date control should only edit the end date.

The feature was tested under Chrome and Edge with the same behaviour.

Tested under Carbon Design System v10

## Steps to reproduce the issue

1. Select a start date and end date in the date range picker.
2. Click on the end date field.
3. Select a date.

![image](https://user-images.githubusercontent.com/20320104/67694054-22b29a00-f979-11e9-95db-39f52e4ec223.png)

**Comment by asudoh** [comment] 2019-11-08 08:15
Hi 👋 thank you for reporting - What happens if you select a date later than older start date in step 3.? Also, what behavior do you see at https://flatpickr.js.org/plugins/#rangeplugin-beta?

**Comment by matrix674** [comment] 2019-11-13 21:15
> What happens if you select a date later than older start date in step 3

It selects that date as start date. and prompts me to select another end date afterward.

> Also, what behavior do you see at https://flatpickr.js.org/plugins/#rangeplugin-beta?

It seems to be working as intended in this example. Once a start date and end date are selected, clicking on one of the field will make you select that field only.

**Comment by asudoh** [comment] 2019-11-18 03:04
I now recall our designer wanted to us to make the behavior similar to https://flatpickr.js.org/examples/#range-calendar for re-edits. Given the nature of range re-edit, I imagine the behavior is regardless of which field the date picker is launched from.

@aagonzales (CC @shixiedesign) Just wanted to double-check if https://flatpickr.js.org/examples/#range-calendar shows the right behavior for re-edits. Please let us know if https://flatpickr.js.org/plugins/#rangeplugin-beta is more desirable. Thanks!

**Comment by matrix674** [comment] 2019-11-18 15:00
In my application the 2nd example is more desirable. It makes it easier to modify only 1 of the 2 dates.

I can see applications where the first example would make sense, but it makes it hard to manually edit dates using your keyboard. Also, I could see the first case as less intuitive that it is a range that is being selected (when nothing is selected). 

In any case, if using 2 different fields I feel like each field should be editable separately.

Thanks!

**Comment by aagonzales** [comment] 2019-11-18 16:03
From my quick check of it, its just re-focusing on the start date after making an end date selection. Its not forcing you to re-enter a start date, the start date remains the same, its just a re-focus. So it not technical broken, the input isn't resetting to blank. I'm not familiar with form focus input order and what's standard with multiple inputs in one component. @matrix674 Do you have any recommended resources to look at for focus order? 

![Nov-18-2019 09-56-13](https://user-images.githubusercontent.com/11670886/69068329-2e2e3980-09ea-11ea-96f1-2baa2e020855.gif)

It looks like our component if following at https://flatpickr.js.org/plugins/#rangeplugin-beta is doing. I'll have to investigate further to see what is the correct focus order.

**Comment by matrix674** [comment] 2019-11-18 16:33
That's odd. This is not the behavior that I am experiencing. 
[Here is a link](https://codepen.io/team/carbon/full/yreYrQ/) from the example on your website documentation. And here is what happens:

![2019-11-18_11-31-09](https://user-images.githubusercontent.com/20320104/69070946-15785080-09f7-11ea-86e5-c6116d20cf62.gif)

Otherwise, I don't see a problem with your focus order.

**Comment by matrix674** [comment] 2019-11-18 16:38
I have the same behaviour in Chrome and Firefox

**Comment by aagonzales** [comment] 2019-11-18 16:58
@asudoh do you think there's something wrong with the codepen example. The react component is not doing that. http://react.carbondesignsystem.com/?path=/story/datepicker--range-with-calendar

**Comment by asudoh** [comment] 2019-11-19 02:21
@aagonzales The vanilla (where I guess the code pen is based on) variant has closer behavior to https://flatpickr.js.org/examples/#range-calendar and the the React variant has closer behavior to https://flatpickr.js.org/plugins/#rangeplugin-beta - So the latter sounds more desirable, is it correct?

**Comment by jinhei** [comment] 2020-06-16 19:13
@aagonzales @asudoh I have the same / a similar issue and stumbled upon this issue. The reproduction steps depend on whether you click the *calendar icon* or the *input field*. Using the *calendar icons* to change the start/end dates causes incorrect behavior, while using the *input fields* results in the correct behavior. 

#### Setup
* Preselect a date range (e.g. Jun 15-17).
* Then...

#### Using Icons
* Click the start date calendar icon, select Jun 1
* Click the end date calendar icon, select Jun 30

Expected result: Range Jun 1 - Jun 30 is selected 
Actual result: ❌ Range Jun 17 - Jun 30 is selected  

![2020-06-16 15 01 47](https://user-images.githubusercontent.com/7538453/84817846-9b876480-afe3-11ea-8b3b-e9bbb8f524cd.gif)

#### Using input field
* Click the start date input field, select Jun 1
* Click the end date input, select Jun 30

Expected result: Range Jun 1 - Jun 30 is selected
Actual result: ✅  Range Jun 1 - Jun 30 is selected (correct)

![2020-06-16 15 12 11](https://user-images.githubusercontent.com/7538453/84818071-e5704a80-afe3-11ea-9ec1-6f484edd71c8.gif)

**Comment by matias-quezada** [comment] 2020-12-18 09:19
I can confirm this happens in the documentation page. I was going to create an issue when I saw this one. 

## How to reproduce
- Open https://react.carbondesignsystem.com/?path=/story/datepicker--range
- Click on the "Start date" input
- Select Dec 1st 2020 as start date
- Select Dec 31st 2020 as end date
- Click on "End date" input to change it
- Select Dec 16th 2020

## Expected behaviour
- Start date stays as Dec 1st 2020
- End date is changed to Dec 16th 2020

## Actual result
- Start date is changed to Dec 16th 2020
- End date stays Dec 31st 2020

## Notes
- There are around 3/4 chances that the bug will happen, sometimes it works as expected
- After following the steps to reproduce the bug I can do it again by trying to change end date to Dec 17th, then Dec 18th... eventually the bug doesn't happen and end date is finally changed.

### Reproduced in
- Brave V1.18.70
- Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Safari Version 14.0 (15610.1.28.1.9, 15610)
- Firefox 80.0.1 (64-bit)
- Firefox 84.0 (64-bit)

### Environment
- macOS Catalina 10.15.7

![Screen Recording 2020-12-18 at 10 21 58](https://user-images.githubusercontent.com/44360321/102597600-2ffd8b80-411b-11eb-8fef-c5e46d063108.gif)

**Comment by abbeyhrt** [comment] 2022-06-16 19:15
Looking into this issue now, it looks like it might have been fixed in a flatpickr update as I'm no longer able to reproduce. When you select a range of dates, then select the "end date" input and choose a date between the two previously selected date, it updates the end date accordingly.

**Comment by abbeyhrt** [comment] 2022-06-21 16:53
Hey @JoelOtter!  Would you be able to provide a [code snippet](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/v10/packages/react/examples/codesandbox) recreating the problem you are running into? I added a default value and it updated the end date as expected when I tested it out in our storybook.

**Comment by JoelOtter** [comment] 2022-06-22 09:55
Hey @abbeyhrt, thanks for the super quick response! Here's a minimal example showing the problem we're having, I hope it works as I've not used codesandbox before: https://codesandbox.io/s/carbon-date-picker-qvwtik?file=/src/index.js

**Comment by abbeyhrt** [comment] 2022-06-23 21:48
@JoelOtter Thank you for the sandbox, that was super helpful!

Looking through your sandbox, the problematic bit seemed to be the `selectedDateRange` state being initialized to an empty array and then being set to the `initialDateRange` in the effect, if you set `selectedDateRange` like this: `const [selectedDateRange, setSelectedDateRange] = useState([new Date(2022, 1, 10), new Date(2022, 5, 20)]);` and then remove ` let initialDateRange = [new Date(2022, 1, 10), new Date(2022, 5, 20)];` from the effect, the calendar then updates the dates as intended. Is there a reason that the initial state `selectedDateRange` needs to be set in an effect?


Since `value` is being set in an effect, it happens too fast to see but DatePicker is first being rendered with that undefined `selectedDateRange` and then the effect runs and `selectedDateRange` is updated to that `initialDateRange`.  In DatePicker, `value` isn't just the default prop, the component starts out with that value but it can be used at any time to force the date picker to be whatever range is in the value. Doing so changes the component to a "controlled" component which then overrides DatePicker's own logic that it is using to update the dates and that's why this issue is occurring. 

To avoid this issue, you could make the change I mentioned above [sandbox example](https://codesandbox.io/s/carbon-date-picker-example-1-vc16x8) or, if state needs to be set in an effect, like say if that range is being fetched, then you can wait to render the dataPicker until that initialDateRange is set [sandbox example for that](https://codesandbox.io/s/carbon-date-picker-example-2-02ohf2?file=/src/index.js). 

Let me know if that makes sense or you have any more questions!

**Comment by JoelOtter** [comment] 2022-06-24 10:45
Thanks @abbeyhrt, that is indeed the issue. I ended up using a skeleton date picker until the date range is loaded, which solves the issue in the same way as your second example. Thanks so much for the help and the detailed response!

**Closed as completed** 2022-06-24 19:40 UTC
Labels: type: bug 🐛, status: help wanted 👐, severity: 2, component: date-picker
