### ISSUE TITLE
Zebra styles broken on Data Table component

### ISSUE THREAD

**Issue by andysherman2121** [carbon-design-system/carbon#5860] opened 2020-04-14 19:07 UTC
Zebra styles aren't working on specific types of the data table component; with batch expansion, with dynamic content, with expansion. 

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

 When selecting zebra styles on the above listed data table types, the background to every row becomes white. 

> Is this issue related to a specific component? 

Data Table

> What browser are you working in?

 Chrome

> What version of the Carbon Design System are you using? 

10.7.4

Step 1: Select either "with batch expansion", or "with dynamic content" or "with expansion"
Step 2: Under Knobs, select "with zebra styles" 

You'll see the rows aren't acting as intended, please let me know if you guys need any more info

**Comment by joshblack** [comment] 2020-04-14 20:59
Hi there @andysherman2121! 👋 Could you help us out by filling out the issue template with a link to a codesandbox and steps to reproduce?

**Comment by andysherman2121** [comment] 2020-04-14 21:51
Hey @joshblack Sure, will do! 
I added the steps to reproduce in the initial comment, let me know if you need any more info

**Comment by emyarod** [comment] 2020-04-14 21:57
related https://github.com/carbon-design-system/carbon/issues/3143

**Comment by aledavila** [comment] 2020-11-17 22:20
Reopening issue due to continued issues in production. Storybook seems to be showing correct zebra styles but for some reason breaks when using the component. It may be how storybook book shows the component(my fix was based on how it looked in storybook) vs how it actually renders in production. 
 
Production: 
<img width="1164" alt="Screen Shot 2020-11-17 at 4 13 07 PM" src="https://user-images.githubusercontent.com/12533409/99456950-d160aa00-28ef-11eb-8573-0e227309c29e.png">

I think the component itself needs a larger refactor.

**Comment by tw15egan** [comment] 2021-02-04 23:20
This is possibly resolved? I believe the deploy previews are using a production build

https://deploy-preview-7746--carbon-components-react.netlify.app/?path=/story/datatable-development--example

https://deploy-preview-7746--carbon-components-react.netlify.app/?path=/story/datatable-expansion--usage

**Comment by tw15egan** [comment] 2021-02-22 23:03
Closing as unable to reproduce

**Closed as completed by tw15egan** 2021-02-22 23:03 UTC
Labels: severity: 3, type: bug 🐛, component: data-table

**Comment by cbelsole** [comment] 2021-04-22 18:29
For those that come back to this issue. I was able to repro this by conditionally rendering the expanded row.


```tsx
tableRows.map(row => 
  <>
    <TableExpandRow></TableExpandRow>
    {row.isExpanded && <TableExpandedRow></TableExpandedRow>}
  </>
)
```

This makes the carbon styles miscount the rows leading to the missing light grey rows. The solution is to always render the expanded row. Carbon will take care of hiding and showing it.
