### ISSUE TITLE
[icon library] remove logo--google icon from repo and library

### ISSUE THREAD

**Issue by conradennis** [carbon-design-system/carbon#5221] opened 2020-01-30 19:04 UTC
Recently was brought to our attention that the [logo--google](url) icon in the [Brand > Social](url) category is not legally compliant and should be removed from the repo and as soon as possible.

Background: Google plus is no longer and active social platform (Google shut it down) and we do not need the Google G in the icon library.

DOD:
Remove the Google G from the icon library (on Carbon and on Design Language)

![73005623-400bce80-3dd7-11ea-8476-acf16dcb1d7b.png](https://images.zenhubusercontent.com/5df0070b833dd35d512c28a2/638d0663-fe2b-4619-af6d-221e6de7c246)

![73006456-afce8900-3dd8-11ea-89b6-7edb558df860.jpeg](https://images.zenhubusercontent.com/5df0070b833dd35d512c28a2/8d64c9d8-5988-4162-82b7-5d1db7a12a21)

**Comment by jnm2377** [comment] 2020-01-30 19:49
@conradennis I transferred this issue to the monorepo bc this needs to be updated in the icons package. The icon library is just consuming the package.

**Comment by tw15egan** [comment] 2020-01-30 22:41
Closing as it is a duplicate of https://github.com/carbon-design-system/carbon/issues/5153

**Closed as completed by tw15egan** 2020-01-30 22:41 UTC
Labels: type: bug 🐛
