### ISSUE TITLE
Add a possible to customize element ID's

### ISSUE THREAD

**Issue by abod-akhras** [carbon-design-system/carbon#9612] opened 2021-09-07 08:40 UTC
### Summary

We’ve few accessibility issues related to non-unique IDs of carbon elements, and that is because we’re rendering multiple DataTables.

So there should be a way to customize those id’s.

### Justification

This issue has been highlighted as Critical in the IBM Accessibility Checker tool
![image](https://user-images.githubusercontent.com/67692574/132313328-44a506a0-cffe-4674-9266-7a38269fa44e.png)

### Required functionality

Add an `id` props for every element that had an id OR remove the id altogether from those elements and just use classes OR suggest how we can fix this issue if we are rendering multiple components on the same page.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment] 2021-09-07 20:15
Hi @abod-ibm, could you provide a reproducible test case in [codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)? 

I'm not 100% sure what components you're running into issues with, but it appears in your screenshot that you're using `DataTable` with the `TableToolbarSearch`? `TableToolbarSearch` accepts `id` as a prop, or will attempt to use a generated unique id:

https://github.com/carbon-design-system/carbon/blob/8ce0b4c0e5547837888b4050fa8630a7692df79b/packages/react/src/components/DataTable/TableToolbarSearch.js#L103

**Comment by abod-ibm** [comment] 2021-09-09 21:07
Thanks for providing a detailed answer @tay1orjones, Closing the ticket now...

**Comment by abod-ibm** [comment] 2021-11-02 08:46
Hi @tay1orjones, is there a way to customize the `id` of the Select All CheckBox in the DataTable? as the accessibility checker tool reporting issues with non-unique ids, since we are rendering more than 1 DataTable in the page.
![image](https://user-images.githubusercontent.com/67692574/139813678-116369ec-ece6-475f-b201-91722611c88e.png)

I tried to pass the id like the below but that didn't work.
```
<TableSelectAll id={`select-all-checkbox-1`}/>
```

**Comment by abod-ibm** [comment] 2021-11-02 12:58
I was not able to reproduce this in [codesandsandbox](https://codesandbox.io/s/sweet-rain-5l5j8?file=/src/index.js:389-412), so the issue seems to be fixed in the latest carbon release.
We use @console/pal: v1.427.0

**Comment by abod-ibm** [comment] 2021-11-02 14:00
I've tried updating to the latest Pal version 1.465.2 but I am still unable to update the id through the props

**Closed as completed** 2021-11-02 14:04 UTC
Labels: status: needs more info, type: enhancement 💡, status: needs triage :female_detective:, status: waiting for maintainer response 💬
