### ISSUE TITLE
[Bug]: Button passing wrong props - v10

### ISSUE THREAD

**Issue by serhiiHalkovskyiIBM** [carbon-design-system/carbon#14173] opened 2023-07-10 19:08 UTC
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

v10.58.7

### React version

v16.8.0

### Description

When I use the Button component and pass some props to see a tooltip I see the next issue(see screenshots)
<img width="96" alt="image" src="https://github.com/carbon-design-system/carbon/assets/139164923/4bb7bb02-0e7e-49b6-9b7e-ae6aa580015d">
<img width="118" alt="image" src="https://github.com/carbon-design-system/carbon/assets/139164923/3d6b1120-473e-4073-8f58-1ce1df2477ab">

It doesn't matter what the props I pass. I noticed that styles order was set in a wrong way in my local version. If you compare the order styles in a storybook version with my local version, you'll see the difference in ordering the same styles. `transform` value was overwritten for a div block with `bx--assistive-text` class name. I'm wondering is there a bug on my end or on yours?
<img width="1728" alt="image" src="https://github.com/carbon-design-system/carbon/assets/139164923/2985e865-e0d3-467f-9cc2-02f00356e6ca">

carbon-components - v10.58.7
carbon-components-react - v7.59.8
react - v16.8.0

### Reproduction/example

-

### Steps to reproduce

-

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2023-07-11 13:57
Icon Button seems to be rendering correctly on the [v10 storybook](https://v7-react.carbondesignsystem.com/?path=/story/components-button--icon-button), so it looks like an issue on your end. Is the version possibly resolving to a lower carbon version through another dependency?

**Comment by serhiiHalkovskyiIBM** [comment] 2023-07-11 15:35
@tw15egan I tried different carbon versions. 
It stop working after version `carbon-components-react``7.34.0`. 
I found only this PR related to the button tooltip in that version - https://github.com/carbon-design-system/carbon/pull/8383

**Comment by tay1orjones** [comment] 2023-07-24 15:15
@serhiiHalkovskyiIBM could you reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx), and post the link back here? It's hard to know exactly what's going wrong without seeing the issue firsthand.

**Comment by serhiiHalkovskyiIBM** [comment] 2023-07-28 20:54
@tay1orjones I tried to reproduce it in a [sandbox](https://codesandbox.io/s/practical-hellman-gnjgwy?file=/package.json), but couldn't

**Comment by sstrubberg** [comment] 2023-09-25 20:39
Closing for now. Happy to re-open with a repro

**Closed as not planned by sstrubberg** 2023-09-25 20:39 UTC
Labels: version: 10, type: bug 🐛, status: needs triage :female_detective:, status: waiting for maintainer response 💬, status: needs reproduction
