### ISSUE TITLE
Handle numerous tabs in the table

### ISSUE THREAD

**Issue by Ragha100** [carbon-design-system/carbon#5799] opened 2020-04-03 08:39 UTC
Hi Team,

We are working on ISD web application, need some customisation option in the table format, currently this option is not available in the Carbon design. Tab experience that will suit our application, please look at the below example link which shows how to handle cases where there are numerous tabs.

Please provide design and code for this feature.

see the example (external website):
https://experience.sap.com/fiori-design-web/wp-content/uploads/sites/5/2018/06/IconTabBar-Interaction-Rearrange-Tabs-and-Overflow.gif

Thank & regards,
Raghavendar Rao (Raghu) Jukalkar
UX/UI Designer, Advanced Sales Analytics (Strategic Projects)

**Comment by asudoh** [comment] 2020-04-05 22:06
Hi 👋 we have a discussion of tab overflow support at #4758. Probably it's close to what you are looking for.

**Comment by Ragha100** [comment] 2020-04-06 08:58
Hi Team, adding additional details to take this forward.
![Screenshot 2020-04-06 at 2 21 08 PM](https://user-images.githubusercontent.com/56122875/78541154-cb133700-7812-11ea-918a-7b620b94713a.png)

**Comment by joshblack** [comment] 2020-04-08 17:22
Closing as a duplicate of #4758 which should tackle the overflow case outlined above!

**Closed as completed by joshblack** 2020-04-08 17:22 UTC
Labels: type: enhancement 💡
