### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by remyarahul** [carbon-design-system/carbon#11847] opened 2022-07-22 10:39 UTC
### Package

@carbon/icons-vue

### Package version

@carbon/icons-vue": "10.41.0"  @carbon/vue: "2.40.0"

### Description

Recently we have noticed no icons are loading in our Vue application.
We are using many icons from the above carbon icon-vue  package. svg path for the icons are empty on screen.
import Home32 from '@carbon/icons-vue/es/home/32';
import Search16 from '@carbon/icons-vue/es/search/16';
import Information16 from '@carbon/icons-vue/es/information/16';
import FolderAdd16 from '@carbon/icons-vue/es/folder--add/16';
import FolderDetails16 from '@carbon/icons-vue/es/folder--details/16';
import FolderDetails32 from '@carbon/icons-vue/es/folder--details/32';
import Edit16 from '@carbon/icons-vue/es/edit/16';
import { Delete16 } from '@carbon/icons-vue/es/trash-can/16';

Please find attached the screens from application.
[Icon-Defect.docx](https://github.com/carbon-design-system/carbon/files/9166982/Icon-Defect.docx)

Initial analysis :

[Lee Chase](https://app.slack.com/team/W3EGC5230)  [3:24 PM](https://americas-bi-ar-tribe.slack.com/archives/CAM5P6NR1/p1658483650507749)
Looking at this old CodeSandbox the icons are still working https://codesandbox.io/s/carbonvue-carbonicons-vue-cvbuttons-j69zk?file=/src/TestComponent.vue
If I switch to Vue 2.7 they stop. I can upgrade the Carbon dependencies but not Vue to 2.7.  I suspect this has something to do with the way Carbon Icons Vue tries to support both Vue 2 and Vue 3. I believe Remya is going to raise an issue with Carbon, but it may need one of you to debug/fix.

### Reproduction/example

https://codesandbox.io/s/carbonvue-carbonicons-vue-cvbuttons-j69zk?file=/src/TestComponent.vue

### Steps to reproduce

lee.chase@uk.ibm.com helped me test , ran this in test sandbox and icons are not loading
<template>
  <div>
    <cv-link href="javascript:void(0)">The following icon should be the color of this text.
      <Edit16/>
    </cv-link>
    <br>
    <br>
    <span class="green">This is just some text with an icon after it.
      <Edit16/>
    </span>

    <br>
    <br>
    <cv-button>Hello world
      <Edit16/>
    </cv-button>
    <br>
    <br>
    <cv-button :icon="MyEdit16">Hello world</cv-button>

    <br>
    <br>
    <cv-button :icon="anEdit16">Hello world</cv-button>

    <br>
    <br>
    <cv-button :icon="AddFilled16">Hello world</cv-button>
  </div>
</template>

<script>
import Edit16 from "@carbon/icons-vue/es/edit/16";
import AddFilled16 from "@carbon/icons-vue/es/add--filled/16";

export default {
  name: "TestComponent",
  components: { Edit16 },
  created() {
    this.anEdit16 = Edit16;
  },
  data() {
    return {
      AddFilled16
    };
  },
  computed: {
    MyEdit16() {
      return Edit16;
    }
  }
};
</script>

<style scoped>
.green {
  color: green;
}
</style>
Please find more details on slack channel thread : #carbon-vue 

Thank You,

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment] 2022-07-25 15:25
Hey @lee-chase! 👋  Could you tell us a bit more about what's going on here? As far as I can tell, `@carbon/icons-vue` isn't supporting v3 and I'm not sure where to begin troubleshooting.

**Comment by tay1orjones** [comment] 2022-07-27 13:40
Duplicate of https://github.com/carbon-design-system/carbon/issues/11836

**Comment by tay1orjones** [comment] 2022-07-27 13:40
I've got a fix up in https://github.com/carbon-design-system/carbon/pull/11855

**Closed as completed by tay1orjones** 2022-07-27 13:40 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, package: icons-vue

**Comment by remyarahul** [comment] 2022-07-27 18:27
HI @tay1orjones ,

Thank you for the updates . Please let me know if i can use teh versions below for testing application:
 "@carbon/icons-vue": "10.48.0",
    "@carbon/vue": "2.40.0",
    "carbon-components": "10.57.2",
    "vue": "2.7.2",
I tried to install application with these and still icons are failing to load.

Thanks,

**Comment by abbeyhrt** [comment] 2022-07-27 21:48
Hey @remyarahul We've fixed the issue in the PR that Taylor posted but we haven't released a new version of `@carbon/icons-vue` with the fix yet!  We will be releasing a release candidate with the fix included next Tuesday and can let you know what version includes the solution 👍

**Comment by remyarahul** [comment] 2022-07-28 08:17
Thank you @abbeyhrt 👍 will wait for updates on this ..

**Comment by remyarahul** [comment] 2022-08-03 05:35
hi , @abbeyhrt , Please let us know if the new version is release with fix?
Please also let me know the version. :)

**Comment by tw15egan** [comment] 2022-08-03 12:54
It is currently in RC status ([10.56.0-rc.0](https://www.npmjs.com/package/@carbon/icons-vue/v/10.56.0-rc.0)) and will be stable at the end of the week

**Comment by remyarahul** [comment] 2022-08-11 17:15
Hi @tw15egan , Please let me know if the version with Fix for the issue is released? thank you

**Comment by remyarahul** [comment] 2022-08-18 09:30
@abbeyhrt Hello, please any update on this new version with fix . Please let me know.. thank you

**Comment by tw15egan** [comment] 2022-08-18 12:28
It should be available now in version `10.56.0`. Since `@carbon/vue` may not have been updated ot use the new version, you may need to manually specify the `@carbon/icons-vue` resolution
