### ISSUE TITLE
[Bug]: DatePicker is not update month correctly

### ISSUE THREAD

**Issue by houhoucoop** [carbon-design-system/carbon#12732] opened 2022-11-28 02:38 UTC
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.17.0

### React version

v17.0.2

### Description

The component was compose with `<DatePicker>` and `<DatePickerInput>`, the calendar show the right date  if user change date or year in input box, bur if user change the date in input box, the date in calendar will change, but the month will keep the same.

<img width="316" alt="Screen Shot 2022-11-28 at 10 28 01 AM" src="https://user-images.githubusercontent.com/77039366/204179709-9c557bb7-f27a-4a7b-97b5-51823d758fc7.png">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://stackblitz.com/edit/github-9kdumn?file=src/App.jsx

### Steps to reproduce

1. Click the input box, it will open the date calendar
2. Change the year in input box, the year on calendar will change automatically
3. Change the data in input box, the date on calendar will change automatically
4. Change the month in input box, the month on calendar will **NOT** change

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment] 2022-11-28 19:50
Closing as a duplicate of https://github.com/carbon-design-system/carbon/issues/6730

**Closed as completed by tw15egan** 2022-11-28 19:50 UTC
Labels: type: bug 🐛, status: waiting for author's response 💬, status: needs triage :female_detective:
