### ISSUE TITLE
OverflowMenu near bottom of window pushes other content up

### ISSUE THREAD

**Issue by renmaddox** [carbon-design-system/carbon#6194] opened 2020-06-03 19:49 UTC
[Title]: If an OverflowMenu is near the bottom of the window, opening it can result in the rest of the window content being pushed up (and off the top of the window) to make room for the menu.

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Ideally, the menu would detect this scenario on open and render above instead of below. This could be a separate `direction` like `dynamic`.

**Comment by aledavila** [comment] 2020-07-17 15:30
Thank you for submitting this. This is something we would like to pursue. You are welcome to contribute this as well.

**Comment by sstrubberg** [comment] 2022-12-12 21:21
Dupe of #6551

**Closed as not planned by sstrubberg** 2022-12-12 21:21 UTC
Labels: type: enhancement 💡, status: help wanted 👐, component: overflow-menu, proposal: accepted, hacktoberfest
